Repository thoth-station/thoth-application, pull requests merged in 2020-06, with the labels that each got.

#27 Kafka setup in the thoth12 cluster
  core/overlays/test/configmaps.yaml
  core/overlays/test/secrets.enc.yaml
Labels: approved, size/L

#28 Add service accounts and variables
  init-job/base/argo-workflows/initialize-schema.yaml
  init-job/base/argo-workflows/register-indexes.yaml
  init-job/base/argo-workflows/solve-core-packages.yaml
  init-job/base/argo-workflows/solve-data-science-packages.yaml
Labels: approved, size/S

#24 Add trigger-integration
  adviser/base/argo-workflows/trigger-integration.yaml
  adviser/base/kustomization.yaml
  adviser/base/openshift-templates/adviser.yaml
Labels: approved, size/M

#15 Add Qeb-Hwt workflow
  adviser/base/argo-workflows/qeb-hwt-integration.yaml
  adviser/base/configmap.yaml
  adviser/base/kustomization.yaml
  adviser/base/openshift-templates/adviser.yaml
  adviser/base/openshift-templates/qeb-hwt.yaml
Labels: approved, size/L

#31 Add key ID
  .sops.yaml
  adviser/.sops.yaml
  slo-reporter/.sops.yaml
  unresolved-package-handler/.sops.yaml
Labels: approved, size/S

#32 Move qeb hwt
  adviser/base/kustomization.yaml
  qeb-hwt-github-app/base/argo-workflows/qeb-hwt-integration.yaml
  qeb-hwt-github-app/base/configmap.yaml
  qeb-hwt-github-app/base/kustomization.yaml
  qeb-hwt-github-app/base/openshift-templates/qeb-hwt.yaml
Labels: approved, size/S

#35 adding role bindings
  metrics-exporter/overlays/stage/kustomization.yaml
  metrics-exporter/overlays/stage/role_bindings.yaml
Labels: approved, size/M

#34 added a metrics-exporter-reader role to every stage namespace
  core/overlays/stage/kustomization.yaml
  core/overlays/stage/roles/kustomization.yaml
  core/overlays/stage/roles/metrics-exporter-reader.yaml
Labels: approved, size/L

#38 Keep wf for SLI
  adviser/base/openshift-templates/adviser.yaml
  qeb-hwt-github-app/base/openshift-templates/qeb-hwt.yaml
  solver/base/openshift-templates/solve_and_sync-template.yaml
Labels: approved, size/S

#39 Remove variables from metrics-exporter
  core/overlays/quicklab/configmaps.yaml
  core/overlays/stage/configmaps.yaml
  core/overlays/test/configmaps.yaml
  metrics-exporter/base/deploymentconfig.yaml
Labels: approved

#43 Use init-job SA to retrieve templates
  init-job/base/argo-workflows/initializer.yaml
Labels: approved, size/XS

#42 Add missing variables for init-job tasks
  init-job/base/argo-workflows/solve-core-packages.yaml
  init-job/base/argo-workflows/solve-data-science-packages.yaml
Labels: approved, size/M

#40 updated kafka certs
  core/overlays/test/secrets.enc.yaml
Labels: approved, size/L

#45 Provide workflow-role permission to agro-server sa
  core/overlays/test/argo-namespace-install.yaml
Labels: approved, size/M

#46 update adviser-template from adviser
  adviser/base/openshift-templates/adviser.yaml
Labels: approved, size/M

#47 use the workflow which are already present
  adviser/base/openshift-templates/adviser.yaml
Labels: approved, size/M

#48 Reduce parallelism
  core/overlays/test/configmaps.yaml
Labels: approved, size/XS

#49 Reduce parallelism more due to postgres PVC in test environment
  core/overlays/test/configmaps.yaml
Labels: approved, size/XS

#50 reduce parallelism to 6
  core/overlays/test/configmaps.yaml
Labels: approved, size/XS

#56 Add dependency-monkey OpenShift template and Argo workflow
  dependency-monkey/base/argo-workflows/dependency-monkey-template.yaml
  dependency-monkey/base/openshift-templates/dependencyMonkey-template.yaml
Labels: approved, size/L

#54 Introduce package-extract template
  package-extract/base/openshift-templates/packageExtract-template.yaml
Labels: approved, size/L
