Repository thoth-station/thoth-application, pull requests merged in 2020-07, with the labels that each got.

#59 support package-extract project with argocd
  package-extract/base/imagestream.yaml
  package-extract/base/kustomization.yaml
  package-extract/base/openshift-templates/package-extract.yaml
  package-extract/overlays/stage/imagestreamtag.yaml
  package-extract/overlays/stage/job-generate-name.yaml
  package-extract/overlays/stage/kustomization.yaml
  package-extract/overlays/stage/thoth-notification.yaml
  package-extract/overlays/test/imagestreamtag.yaml
  package-extract/overlays/test/job-generate-name.yaml
  package-extract/overlays/test/kustomization.yaml
  package-extract/overlays/test/thoth-notification.yaml
Labels: approved, size/L

#55 Add provenance-checker OpenShift template and Argo workflow
  provenance-checker/base/argo-workflows/provenance-check-template.yaml
  provenance-checker/base/openshift-templates/provenanceChecker-template.yaml
Labels: size/L

#62 Package extract bits
  package-extract/base/argo-workflows/package-extract.yaml
  package-extract/base/openshift-templates/package-extract.yaml
Labels: approved, size/M

#63 Dependency Monkey workflow bits
  dependency-monkey/base/argo-workflows/dependency-monkey-template.yaml
  dependency-monkey/base/openshift-templates/dependencyMonkey-template.yaml
Labels: approved, size/S

#64 Isis API is unset
  adviser/base/argo-workflows/advise.yaml
Labels: approved, size/XS

#57 Add buildlog-parser OpenShift template
  buildlog-parser/base/openshift-templates/buildlogParser-template.yaml
Labels: approved, size/M

#61 Fixes related to provenance-checker workflow
  provenance-checker/base/argo-workflows/provenance-check-template.yaml
  provenance-checker/base/openshift-templates/provenanceChecker-template.yaml
Labels: approved, size/S

#65 updated package-extract kustomize
  package-extract/base/kustomization.yaml
Labels: approved, size/XS

#66 sync fail due to no required params
  package-extract/base/openshift-templates/package-extract.yaml
Labels: approved, size/XS

#30 Add thoth-station/mi
  mi/.sops.yaml
  mi/README.md
  mi/base/cronjob.yaml
  mi/base/imagestream.yaml
  mi/base/kustomization.yaml
  mi/base/openshift-templates/scheduler-buildConfig-template.yaml
  mi/base/openshift-templates/scheduler-cronJob-template.yaml
  mi/base/openshift-templates/scheduler-imageStream-template.yaml
  mi/base/scheduler-repositories-configMap.yaml
  mi/overlays/test/imagestreamtag.yaml
  mi/overlays/test/job-generate-name.yaml
  mi/overlays/test/kustomization.yaml
  mi/overlays/test/thoth-notification.yaml
Labels: approved, size/L

#69 raise parallelism back to 10
  core/overlays/test/configmaps.yaml
Labels: approved, size/XS

#67 MI-scheduler
  mi-scheduler/.sops.yaml
  mi-scheduler/README.md
  mi-scheduler/base/configmaps.yaml
  mi-scheduler/base/cronjob.yaml
  mi-scheduler/base/imagestream.yaml
  mi-scheduler/base/kustomization.yaml
  mi-scheduler/overlays/test/imagestreamtag.yaml
  mi-scheduler/overlays/test/job-generate-name.yaml
  mi-scheduler/overlays/test/kustomization.yaml
  mi-scheduler/overlays/test/thoth-notification.yaml
  mi/base/cronjob.yaml
  mi/base/openshift-templates/scheduler-buildConfig-template.yaml
  mi/base/openshift-templates/scheduler-cronJob-template.yaml
  mi/base/openshift-templates/scheduler-imageStream-template.yaml
  mi/base/scheduler-repositories-configMap.yaml
  mi/overlays/test/imagestreamtag.yaml
Labels: approved, size/L

#72 Add revsolver component
  revsolver/base/imagestream.yaml
Labels: approved, size/XS

#76 setup basic for graph-refresh application in ocp
  graph-refresh/base/buildconfig.yaml
  graph-refresh/base/cronjob.yaml
  graph-refresh/base/imagestream.yaml
  graph-refresh/base/kustomization.yaml
  graph-refresh/overlays/stage/imagestreamtag.yaml
  graph-refresh/overlays/stage/job-generate-name.yaml
  graph-refresh/overlays/stage/kustomization.yaml
  graph-refresh/overlays/stage/thoth-notification.yaml
  graph-refresh/overlays/test/imagestreamtag.yaml
  graph-refresh/overlays/test/job-generate-name.yaml
  graph-refresh/overlays/test/kustomization.yaml
  graph-refresh/overlays/test/thoth-notification.yaml
Labels: approved, size/L

#77 include serviceaccount and roles for apps fucntion
  graph-refresh/base/kustomization.yaml
  graph-refresh/base/role.yaml
  graph-refresh/base/rolebindings.yaml
  graph-refresh/base/serviceaccount.yaml
Labels: approved, size/M

#78 Amun argo wf does not use infra ns and registry parameters
  amun/base/openshift-templates/inspection-with-cpu-workflow.yaml
  amun/base/openshift-templates/inspection-workflow.yaml
Labels: approved, size/S

#81 setup basic for package-releases application in ocp
  package-releases/README.md
  package-releases/base/buildconfig.yaml
  package-releases/base/cronjob.yaml
  package-releases/base/imagestream.yaml
  package-releases/base/kustomization.yaml
  package-releases/overlays/stage/imagestreamtag.yaml
  package-releases/overlays/stage/job-generate-name.yaml
  package-releases/overlays/stage/kustomization.yaml
  package-releases/overlays/stage/thoth-notification.yaml
  package-releases/overlays/test/imagestreamtag.yaml
  package-releases/overlays/test/job-generate-name.yaml
  package-releases/overlays/test/kustomization.yaml
  package-releases/overlays/test/thoth-notification.yaml
Labels: approved, size/L

#80 use only required roles for graph-refresh-job
  graph-refresh/base/role.yaml
  graph-refresh/base/rolebindings.yaml
Labels: approved, size/M

#82 setup basic for cve-update application in ocp
  cve-update/base/buildconfig.yaml
  cve-update/base/cronjob.yaml
  cve-update/base/imagestream.yaml
  cve-update/base/kustomization.yaml
  cve-update/overlays/stage/imagestreamtag.yaml
  cve-update/overlays/stage/job-generate-name.yaml
  cve-update/overlays/stage/kustomization.yaml
  cve-update/overlays/stage/thoth-notification.yaml
  cve-update/overlays/test/imagestreamtag.yaml
  cve-update/overlays/test/job-generate-name.yaml
  cve-update/overlays/test/kustomization.yaml
  cve-update/overlays/test/thoth-notification.yaml
Labels: approved, size/L

#83 Decrease beam width for adviser
  adviser/base/openshift-templates/adviser.yaml
Labels: approved, size/XS

#84 Add metadata.name to cronjob
  mi-scheduler/base/cronjob.yaml
Labels: approved, size/XS

#71 Prow roles and rolebinding needed CA perms
  prow/base/kustomization.yaml
  prow/overlays/cluster-admin/crds.yaml
  prow/overlays/cluster-admin/kustomization.yaml
  prow/overlays/cluster-admin/rolebindings.yaml
  prow/overlays/cluster-admin/roles.yaml
Labels: approved, size/XS

#85 Workflow revsolver
  revsolver/base/argo-workflows/revsolver-template.yaml
  revsolver/base/openshift-templates/revsolve_and_sync-template.yaml
Labels: approved, size/L

#86 Add graph-backup-job component
  graph-backup-job/base/cronjob.yaml
  graph-backup-job/base/imagestream.yaml
  graph-backup-job/base/kustomization.yaml
Labels: approved, size/L

#87 Add missing environment variables to revsolver
  revsolver/base/argo-workflows/revsolver-template.yaml
Labels: approved, size/M

#88 Add service account to let revsolver check registered solvers
  revsolver/base/argo-workflows/revsolver-template.yaml
  revsolver/base/role.yaml
  revsolver/base/rolebinding.yaml
  revsolver/base/serviceaccount.yaml
Labels: approved, size/M

#89 Increase deadline seconds for revsolver
  revsolver/base/argo-workflows/revsolver-template.yaml
Labels: approved, size/XS

#90 Increase CPU and decrease memory allocated for revsolver
  revsolver/base/argo-workflows/revsolver-template.yaml
Labels: approved, size/XS

#92 Fix typo
  revsolver/base/argo-workflows/revsolver-template.yaml
Labels: approved, size/XS

#91 use required roles for amun-api sa
  amun/base/imagestream.yaml
  amun/base/role.yaml
  amun/overlays/test/imagestreamtag.yaml
Labels: approved, size/L

#93 Thoth investigator (Consumer) Application
  core/base/imagestreams.yaml
  core/overlays/test/imagestreamtags.yaml
  investigator/README.md
  investigator/base/deploymentconfig.yaml
  investigator/base/kustomization.yaml
  investigator/overlays/test/job-generate-name.yaml
  investigator/overlays/test/kustomization.yaml
  investigator/overlays/test/thoth-notification.yaml
  unresolved-package-handler/README.md
  unresolved-package-handler/base/imagestream.yaml
  unresolved-package-handler/overlays/test/imagestreamtag.yaml
Labels: approved, size/M

#94 Add missing templates in adviser and use Investigator
  adviser/base/argo-workflows/investigate-unresolved-package.yaml
  adviser/base/argo-workflows/trigger-integration.yaml
  adviser/base/openshift-templates/adviser.yaml
  graph-sync/base/argo-workflows/sync-template.yaml
  graph-sync/base/kustomization.yaml
  graph-sync/base/openshift-templates/syncJob-template.yaml
  investigator/base/deploymentconfig.yaml
  package-update/base/deploymentconfig.yaml
Labels: approved, size/L

#96 use consistent naming convention
  investigator/overlays/test/thoth-notification.yaml
Labels: approved, size/XS

#99 enable argoserver sa to access secrets
  core/overlays/test/argo-namespace-install.yaml
Labels: approved, size/XS

#101 Fix storing of dockerfile artifact
  amun/base/argo-workflows/inspection-build-with-cpu.yaml
  amun/base/argo-workflows/inspection-build.yaml
Labels: approved, size/S

#102 adjust indentation and secret name
  adviser/base/argo-workflows/investigate-unresolved-package.yaml
  adviser/base/openshift-templates/adviser.yaml
Labels: approved, size/M

#105 change from block indicator to normal string
  amun/overlays/test/configmaps.yaml
Labels: size/S

#106 Schedule for every hour of each day in year
  mi-scheduler/base/cronjob.yaml
Labels: approved, size/XS

#107 imagestream required for mi scheduler workflows
  mi-scheduler/base/imagestream.yaml
  mi-scheduler/overlays/test/imagestreamtag.yaml
Labels: approved, size/S

#112 Reduce adviser's beam width
  adviser/base/argo-workflows/advise.yaml
  adviser/base/openshift-templates/adviser.yaml
Labels: approved, size/XS

#114 removed the result-api deployment
  management-api/base/deploymentconfig.yaml
  result-api/README.md
  result-api/application-frontend-stage.yaml
  result-api/base/configmaps.yaml
  result-api/base/deploymentconfigs.yaml
  result-api/base/imagestreams.yaml
  result-api/base/kustomization.yaml
  result-api/base/serviceaccounts.yaml
  result-api/base/services.yaml
  result-api/overlays/test/imagestreamtag.yaml
  result-api/overlays/test/job-generate-name.yaml
  result-api/overlays/test/kustomization.yaml
  result-api/overlays/test/thoth-notification.yaml
  user-api/base/deploymentconfig.yaml
Labels: approved, size/L

#115 replaced deploymentName with deployment-name
  advise-reporter/base/cronjob.yaml
  advise-reporter/base/deploymentconfig.yaml
  adviser/base/argo-workflows/advise.yaml
  core/overlays/quicklab/configmaps.yaml
  core/overlays/stage/configmaps.yaml
  core/overlays/test/configmaps.yaml
  cve-update/base/cronjob.yaml
  graph-refresh/base/cronjob.yaml
  graph-sync/base/argo-workflows/sync-template.yaml
  graph-sync/base/openshift-templates/syncJob-template.yaml
  init-job/base/argo-workflows/solve-core-packages.yaml
  init-job/base/argo-workflows/solve-data-science-packages.yaml
  management-api/base/deploymentconfig.yaml
  metrics-exporter/base/deploymentconfig.yaml
  package-releases/base/cronjob.yaml
  package-update/base/cronjob.yaml
  package-update/base/deploymentconfig.yaml
  revsolver/base/argo-workflows/revsolver-template.yaml
  slo-reporter/base/cronjob.yaml
  solver/base/argo-workflows/solver-template.yaml
  user-api/base/deploymentconfig.yaml
Labels: approved, size/M

#116 Use CM for database host
  advise-reporter/base/cronjob.yaml
  graph-sync/base/argo-workflows/sync-template.yaml
  management-api/base/deploymentconfig.yaml
  package-update/base/cronjob.yaml
Labels: approved, size/S

#117 Add amun-api-url env for management-API
  core/overlays/test/configmaps.yaml
  management-api/base/deploymentconfig.yaml
Labels: approved, size/XS

#108 Add mi workflow & template & config
  mi-scheduler/base/argo-workflows/mi-workflow-template.yaml
  mi-scheduler/base/configmaps.yaml
  mi-scheduler/base/cronjob.yaml
  mi-scheduler/base/openshift-templates/mi-run-template.yaml
Labels: approved, size/L

#103 added a sefkhet-abwy application with an ocp overlay
  sefkhet-abwy/base/deploymentconfig.yaml
  sefkhet-abwy/base/imagestream.yaml
  sefkhet-abwy/base/kustomization.yaml
  sefkhet-abwy/base/route.yaml
  sefkhet-abwy/base/service.yaml
  sefkhet-abwy/overlays/ocp/kustomization.yaml
  sefkhet-abwy/overlays/ocp/secret-generator.yaml
  sefkhet-abwy/overlays/ocp/secrets.enc.yaml
  sefkhet-abwy/overlays/ocp/ultrahook.yaml
Labels: approved, size/L

#53 initial commit of SI app
  security-indicators/README.md
  security-indicators/base/argo-workflows/aggregator-template.yaml
  security-indicators/base/argo-workflows/bandit-template.yaml
  security-indicators/base/argo-workflows/cloc-template.yaml
  security-indicators/base/argo-workflows/download-package-template.yaml
  security-indicators/base/imagestream.yaml
  security-indicators/base/kustomization.yaml
  security-indicators/base/security-indicators.yaml
  security-indicators/overlays/test/buildconfig.yaml
  security-indicators/overlays/test/imagestreamtag.yaml
  security-indicators/overlays/test/job-generate-name.yaml
  security-indicators/overlays/test/kustomization.yaml
  security-indicators/overlays/test/thoth-notification.yaml
Labels: approved, size/XL

#121 add another step to workflow to sync results
  security-indicators/base/security-indicators.yaml
Labels: approved, size/S

#122 include additional manifest for security indicators
  security-indicators/base/kustomization.yaml
  security-indicators/base/openshift-templates/security-indicators.yaml
  security-indicators/overlays/test/buildconfig.yaml
  security-indicators/overlays/test/imagestreamtag.yaml
Labels: size/M

#123 include additional manifest for mi indicators
  mi-scheduler/base/cronjob.yaml
  mi-scheduler/base/kustomization.yaml
Labels: size/S

#124 perms for mi scheduler to lookup on configmaps
  mi-scheduler/base/cronjob.yaml
  mi-scheduler/base/role.yaml
  mi-scheduler/base/role_binding.yaml
  mi-scheduler/base/serviceaccount.yaml
Labels: approved, size/M

#125 Do not restrict latest versions in adviser runs
  adviser/base/argo-workflows/advise.yaml
  adviser/base/openshift-templates/adviser.yaml
Labels: approved, size/S

#126 include the investigator manifest
  investigator/base/deploymentconfig.yaml
  investigator/base/kustomization.yaml
  investigator/base/role.yaml
  investigator/base/role_binding.yaml
  investigator/base/serviceaccount.yaml
Labels: approved, size/M

#130 sesheta-srcops token for mi workflow
  mi-scheduler/overlays/test/kustomization.yaml
  mi-scheduler/overlays/test/secret-generator.yaml
  mi-scheduler/overlays/test/secrets.enc.yaml
Labels: approved, size/M

#131 kebechet secret required for adviser
  adviser/overlays/test/secrets.enc.yaml
Labels: approved, size/L

#132 Add middletier and infra namespaces vars
  mi-scheduler/base/cronjob.yaml
Labels: approved, size/S

#128 Add missing variables to schedule solvers
  investigator/base/deploymentconfig.yaml
Labels: approved, size/M

#135 Missing env variables reporter
  advise-reporter/base/cronjob.yaml
Labels: approved, size/S

#138 keep adviser components together
  adviser/base/argo-workflows/dependency-monkey.yaml
  adviser/base/argo-workflows/provenance-check.yaml
  adviser/base/openshift-templates/dependency-monkey.yaml
  adviser/base/openshift-templates/provenance-checker.yaml
Labels: approved, size/XS

#141 patch imagestream in kustomize for argo
  core/overlays/test/kustomization.yaml
Labels: approved, size/XS

#140 updated MI scheduler role
  mi-scheduler/base/role.yaml
Labels: approved, size/S

#143 mi-scheduler need perms to view configmaps
  mi-scheduler/base/role.yaml
Labels: approved, size/XS

#145 Add GH access token to cronjob
  mi-scheduler/base/cronjob.yaml
Labels: approved, size/XS

#97 Add Kebechet-run results to adviser
  adviser/base/argo-workflows/kebechet-run-results.yaml
  adviser/base/openshift-templates/adviser.yaml
Labels: approved, size/M

#146 cve-update-job minor configuration updates
  cve-update/overlays/stage/imagestreamtag.yaml
  cve-update/overlays/stage/thoth-notification.yaml
  cve-update/overlays/test/buildconfig.yaml
  cve-update/overlays/test/imagestreamtag.yaml
  cve-update/overlays/test/kustomization.yaml
Labels: approved, size/S

#150 Feature/metrics service
  investigator/base/deploymentconfig.yaml
  package-update/base/deploymentconfig.yaml
  package-update/base/service.yaml
Labels: approved, size/S

#110 Documentation/readme
  README.md
Labels: approved, size/S

#152 Add workflow tasks to send SolvedPackage message
  solver/base/argo-workflows/parse_solver_inputs.yaml
  solver/base/openshift-templates/solve_and_sync-template.yaml
Labels: approved, size/M

#153 Add secrets to resources for `mi-scheduler`
  mi-scheduler/base/role.yaml
Labels: approved, size/XS

#154 use ceph based storage for postgresql
  core/overlays/graph-stage/postgresql.yaml
Labels: size/XS

#160 role_binding for management-api to schedule workflows
  management-api/base/role_binding.yaml
Labels: approved, size/S

#161 Fix configmap reference for Prometheus configuration
  adviser/base/argo-workflows/dependency-monkey.yaml
  adviser/base/argo-workflows/provenance-check.yaml
Labels: approved, size/S

#162 include workflows and template with argocd
  adviser/base/kustomization.yaml
Labels: approved, size/XS

#163 update the package-extract template
  package-extract/base/openshift-templates/package-extract.yaml
Labels: approved, size/XS

#164 place the package extract template in infra-stage
  package-extract/overlays/stage/kustomization.yaml
  package-extract/overlays/stage/put-into-infra-namespace.yaml
Labels: approved, size/S

#151 add image stream and WorkflowTemplate for thoth-messaging
  core/base/argo-workflows/send-message.yaml
  core/base/imagestreams.yaml
Labels: approved, size/M

#173 Remove unused configuration options from cm
  core/overlays/quicklab/configmaps.yaml
  core/overlays/stage/configmaps.yaml
  core/overlays/test/configmaps.yaml
  management-api/base/deploymentconfig.yaml
  user-api/base/deploymentconfig.yaml
Labels: approved, size/M

#171 Amun API URL used in dependency monkey needs scheme
  amun/overlays/test/configmaps.yaml
  core/overlays/test/configmaps.yaml
Labels: approved, size/XS

#172 place adviser templates in infra namespace
  adviser/overlays/stage/imagestreamtag.yaml
  adviser/overlays/stage/job-generate-name.yaml
  adviser/overlays/stage/kustomization.yaml
Labels: approved, size/S

#167 run package-extract notification from infra
  package-extract/overlays/stage/job-generate-name.yaml
Labels: approved, size/XS

#165 update of package-release
  package-releases/overlays/stage/imagestreamtag.yaml
  package-releases/overlays/stage/thoth-notification.yaml
  package-releases/overlays/test/buildconfig.yaml
  package-releases/overlays/test/imagestreamtag.yaml
  package-releases/overlays/test/kustomization.yaml
Labels: approved, size/XS

#174 Increase resources for pgbouncer and postgres
  core/overlays/graph-stage/pgbouncer.yaml
  core/overlays/graph-stage/postgresql.yaml
Labels: approved, size/S

#142 migrated build-watcher to deploy with kustomize and agrocd
  build-watcher/README.md
  build-watcher/base/configmap.yaml
  build-watcher/base/deploymentconfig.yaml
  build-watcher/base/imagestreamtag.yaml
  build-watcher/base/kustomization.yaml
  build-watcher/base/role.yaml
  build-watcher/base/role_binding.yaml
  build-watcher/base/serviceaccount.yaml
  build-watcher/overlays/amun-api/configmap.yaml
  build-watcher/overlays/amun-api/imagestreamtag.yaml
  build-watcher/overlays/amun-api/job-generate-name.yaml
  build-watcher/overlays/amun-api/kustomization.yaml
  build-watcher/overlays/amun-api/thoth-notification.yaml
  build-watcher/overlays/test/buildconfig.yaml
  build-watcher/overlays/test/configmap.yaml
Labels: approved, size/L

#119 Drop use-argo from configmaps
  advise-reporter/base/configmap.yaml
  adviser/base/configmap.yaml
  management-api/base/configmap.yaml
  qeb-hwt-github-app/base/configmap.yaml
  user-api/base/configmap.yaml
  user-api/base/deploymentconfig.yaml
Labels: approved, size/S

#176 Add view verb
  mi-scheduler/base/role.yaml
Labels: approved, size/XS

#177 Add missing yamls to kustomization
  mi-scheduler/base/kustomization.yaml
  mi-scheduler/base/role.yaml
Labels: approved, size/XS

#178 fix the role_bindings
  mi-scheduler/base/kustomization.yaml
Labels: approved, size/S

#170 manifest files for solvers stage deployment
  solver/base/argo-workflows/parse-solver-inputs.yaml
  solver/base/kustomization.yaml
  solver/base/openshift-templates/solve_and_sync-template.yaml
  solver/overlays/stage/imagestreamtag.yaml
  solver/overlays/stage/job-generate-name.yaml
  solver/overlays/stage/kustomization.yaml
  solver/overlays/stage/put-into-infra-namespace.yaml
  solver/overlays/stage/resources_patch.yaml
  solver/overlays/stage/thoth-notification.yaml
Labels: approved, size/L

#179 Change templates' specifications, remove view verb & add workflow ID
  mi-scheduler/base/argo-workflows/mi-workflow-template.yaml
  mi-scheduler/base/openshift-templates/mi-run-template.yaml
  mi-scheduler/base/role.yaml
Labels: approved, size/S

#181 Rectify ceph bucketname and prefix
  core/overlays/stage/configmaps.yaml
Labels: approved, size/XS

#182 upgrade postgresql pvc
  amun/overlays/test/configmaps.yaml
  core/overlays/graph-stage/postgresql.yaml
  mi-scheduler/base/role.yaml
Labels: approved, size/XS

#189 Amun workflow SA can get pods and configmaps
  amun/base/role.yaml
Labels: approved, size/XS

#186 add route for viewing metrics
  package-update/overlays/test/route.yaml
  package-update/overlays/test/service.yaml
Labels: approved, size/S

#183 MI scheduler required permissions
  mi-scheduler/base/cronjob.yaml
  mi-scheduler/base/openshift-templates/mi-run-template.yaml
  mi-scheduler/base/role_binding.yaml
Labels: approved, size/S

#185 pass parsed git service string to kebechet
  adviser/base/argo-workflows/kebechet-run-results.yaml
  adviser/base/argo-workflows/trigger-integration.yaml
  adviser/base/openshift-templates/adviser.yaml
Labels: approved, size/XS

#190 amun workflow requires pod logs access
  amun/base/role.yaml
Labels: approved, size/XS

#191 amun workflow requires pods patch access
  amun/base/role.yaml
Labels: approved, size/S

#194 Updated solver with new release
  solver/overlays/stage/imagestreamtag.yaml
  solver/overlays/test/imagestreamtag.yaml
Labels: size/S

#197 Provide workflow parallelism in workflow defaults section
  core/overlays/middletier-stage/configmaps.yaml
  core/overlays/quicklab/configmaps.yaml
  core/overlays/test/configmaps.yaml
Labels: approved, size/S

#195 amun stage deployment fixes
  amun/base/argo-workflows/inspection-run-with-cpu.yaml
  amun/base/argo-workflows/inspection-run.yaml
  amun/overlays/amun-inspection/argo-namespace-install.yaml
  amun/overlays/stage/kustomization.yaml
  amun/overlays/stage/secrets.enc.yaml
  amun/overlays/test/buildconfig.yaml
Labels: approved, size/L

#198 fixes required for smooth solver execution
  graph-sync/base/argo-workflows/sync-template.yaml
  metrics-exporter/base/deploymentconfig.yaml
  solver/base/argo-workflows/parse-solver-inputs.yaml
  solver/base/openshift-templates/solve_and_sync-template.yaml
Labels: approved, size/S

#199 Provide default TTL strategy
  core/overlays/middletier-stage/configmaps.yaml
  core/overlays/quicklab/configmaps.yaml
  core/overlays/test/configmaps.yaml
Labels: approved, size/XS

#200 upgrade workflow-controller with more memory
  core/overlays/middletier-stage/argo-namespace-install.yaml
Labels: approved, size/XS
