Repository thoth-station/thoth-application, pull requests merged in 2020-05, with the labels that each got.

#7 update thanos token secret required by slo-reporter
  slo-reporter/base/cronjob.yaml
  slo-reporter/overlays/test/configmap.yaml
  slo-reporter/overlays/test/secrets.enc.yaml
Labels: approved, size/M

#9 using the thoth-toolbox now...
  adviser/base/argo-workflows/advise.yaml
  adviser/base/argo-workflows/finished-webhook.yaml
  adviser/base/kustomization.yaml
  adviser/base/openshift-templates/adviser.yaml
Labels: size/L

#12 Use workflow helpers for trigger finished webhook
  adviser/README.md
  adviser/base/argo-workflows/finished-webhook.yaml
  adviser/base/imagestream.yaml
  adviser/overlays/test/imagestreamtag.yaml
Labels: approved, size/M

#17 Unresolved package handler
  unresolved-package-handler/.sops.yaml
  unresolved-package-handler/README.md
  unresolved-package-handler/base/deploymentconfig.yaml
  unresolved-package-handler/base/imagestream.yaml
  unresolved-package-handler/base/kustomization.yaml
  unresolved-package-handler/overlays/test/imagestreamtag.yaml
  unresolved-package-handler/overlays/test/job-generate-name.yaml
  unresolved-package-handler/overlays/test/kustomization.yaml
  unresolved-package-handler/overlays/test/thoth-notification.yaml
Labels: approved, size/L

#19 Modify solver template
  solver/base/argo-workflows/solver-template.yaml
  solver/base/kustomization.yaml
  solver/base/openshift-templates/solve_and_sync-template.yaml
Labels: size/S

#23 Allow imagestream to auto update image
  init-job/overlays/test/imagestreamtag.yaml
Labels: approved, size/XS
