Repository thoth-station/thoth-application, pull requests merged in 2020-09, with the labels that each got.

#345 Introduce a way to parametrize predictor configuration in DM
  adviser/base/argo-workflows/dependency-monkey.yaml
  adviser/base/openshift-templates/dependency-monkey.yaml
Labels: approved, size/XS

#346 Introduce a way to parametrize adviser's predictor
  adviser/base/argo-workflows/advise.yaml
  adviser/base/openshift-templates/adviser.yaml
Labels: approved, size/S

#347 Allow users to pick predictor to be used
  adviser/base/argo-workflows/dependency-monkey.yaml
  adviser/base/openshift-templates/dependency-monkey.yaml
Labels: approved, size/S

#348 Bump management-api to v0.7.0 in stage
  management-api/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#351 Revert "Revert "Bump management-api to v0.7.0 in stage""
  management-api/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#350 Fix propagation of predictor and predictor config to argo dag
  adviser/base/openshift-templates/adviser.yaml
  adviser/base/openshift-templates/dependency-monkey.yaml
Labels: approved, size/XS

#355 Provide secondsAfterCompletion in all workflows
  adviser/base/openshift-templates/adviser.yaml
  adviser/base/openshift-templates/dependency-monkey.yaml
  adviser/base/openshift-templates/provenance-checker.yaml
  buildlog-parser/base/openshift-templates/buildlogParser-template.yaml
  kebechet/base/openshift-templates/kebechet.yaml
  package-extract/base/openshift-templates/package-extract.yaml
  qeb-hwt-github-app/base/openshift-templates/qeb-hwt.yaml
  revsolver/base/openshift-templates/revsolve_and_sync-template.yaml
  solver/base/openshift-templates/solve_and_sync-template.yaml
Labels: approved, size/XS

#357 Bump metrics-exporter version to v0.8.7 in stage
  metrics-exporter/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#360 Move secrets and CM to core to be accessible by other components
  core/overlays/test/configmaps.yaml
  core/overlays/test/secrets.enc.yaml
  qeb-hwt-github-app/overlays/ocp/secrets.enc.yaml
Labels: approved, size/M

#358 Set rebumitPendingPods to all the workflows
  adviser/base/openshift-templates/adviser.yaml
  adviser/base/openshift-templates/dependency-monkey.yaml
  adviser/base/openshift-templates/provenance-checker.yaml
  amun/base/openshift-templates/inspection-with-cpu-workflow.yaml
  amun/base/openshift-templates/inspection-workflow.yaml
  buildlog-parser/base/openshift-templates/buildlogParser-template.yaml
  init-job/base/argo-workflows/initializer.yaml
  kebechet/base/openshift-templates/kebechet.yaml
  mi-scheduler/base/openshift-templates/mi-run-template.yaml
  package-extract/base/openshift-templates/package-extract.yaml
  qeb-hwt-github-app/base/openshift-templates/qeb-hwt.yaml
  revsolver/base/openshift-templates/revsolve_and_sync-template.yaml
  solver/base/openshift-templates/solve_and_sync-template.yaml
Labels: approved, size/S

#361 Move resubmit pending pods to task definitions
  adviser/base/openshift-templates/adviser.yaml
  adviser/base/openshift-templates/dependency-monkey.yaml
  adviser/base/openshift-templates/provenance-checker.yaml
  buildlog-parser/base/openshift-templates/buildlogParser-template.yaml
  init-job/base/argo-workflows/initializer.yaml
  kebechet/base/openshift-templates/kebechet.yaml
  mi-scheduler/base/openshift-templates/mi-run-template.yaml
  package-extract/base/openshift-templates/package-extract.yaml
  qeb-hwt-github-app/base/openshift-templates/qeb-hwt.yaml
  revsolver/base/openshift-templates/revsolve_and_sync-template.yaml
  security-indicators/base/openshift-templates/security-indicators.yaml
  solver/base/openshift-templates/solve_and_sync-template.yaml
Labels: approved, size/M

#362 Add resubmitPendingPods to all templates in workflow
  adviser/base/argo-workflows/advise.yaml
  adviser/base/argo-workflows/dependency-monkey.yaml
  adviser/base/argo-workflows/investigate-unresolved-package.yaml
  adviser/base/argo-workflows/kebechet-run-results.yaml
  adviser/base/argo-workflows/provenance-check.yaml
  adviser/base/argo-workflows/trigger-integration.yaml
  amun/base/argo-workflows/inspection-build-with-cpu.yaml
  amun/base/argo-workflows/inspection-build.yaml
  amun/base/argo-workflows/inspection-run-with-cpu.yaml
  amun/base/argo-workflows/inspection-run.yaml
  core/base/argo-workflows/send-message.yaml
  graph-sync/base/argo-workflows/sync-template.yaml
  init-job/base/argo-workflows/initialize-schema.yaml
  init-job/base/argo-workflows/register-indexes.yaml
  init-job/base/argo-workflows/solve-core-packages.yaml
  init-job/base/argo-workflows/solve-data-science-packages.yaml
  kebechet/base/argo-workflows/kebechet.yaml
  mi-scheduler/base/argo-workflows/mi-workflow-template.yaml
  package-extract/base/argo-workflows/package-extract.yaml
  qeb-hwt-github-app/base/argo-workflows/qeb-hwt-integration.yaml
  revsolver/base/argo-workflows/revsolver-template.yaml
  security-indicators/base/argo-workflows/aggregator-template.yaml
  security-indicators/base/argo-workflows/bandit-template.yaml
  security-indicators/base/argo-workflows/cloc-template.yaml
  security-indicators/base/argo-workflows/download-package-template.yaml
  solver/base/argo-workflows/parse-solver-inputs.yaml
  solver/base/argo-workflows/solver-template.yaml
Labels: approved, size/M

#363 Revert "Move resubmit pending pods to task definitions"
  adviser/base/openshift-templates/adviser.yaml
  adviser/base/openshift-templates/dependency-monkey.yaml
  adviser/base/openshift-templates/provenance-checker.yaml
  buildlog-parser/base/openshift-templates/buildlogParser-template.yaml
  init-job/base/argo-workflows/initializer.yaml
  kebechet/base/openshift-templates/kebechet.yaml
  mi-scheduler/base/openshift-templates/mi-run-template.yaml
  package-extract/base/openshift-templates/package-extract.yaml
  qeb-hwt-github-app/base/openshift-templates/qeb-hwt.yaml
  revsolver/base/openshift-templates/revsolve_and_sync-template.yaml
  security-indicators/base/openshift-templates/security-indicators.yaml
  solver/base/openshift-templates/solve_and_sync-template.yaml
Labels: approved, size/M

#364 Revert "Set rebumitPendingPods to all the workflows"
  adviser/base/openshift-templates/provenance-checker.yaml
  amun/base/openshift-templates/inspection-with-cpu-workflow.yaml
  amun/base/openshift-templates/inspection-workflow.yaml
Labels: approved, size/XS

#365 Remove resubmitPendingPods from openshift templates
  adviser/base/openshift-templates/adviser.yaml
  adviser/base/openshift-templates/dependency-monkey.yaml
  amun/base/openshift-templates/inspection-with-cpu-workflow.yaml
  amun/base/openshift-templates/inspection-workflow.yaml
  buildlog-parser/base/openshift-templates/buildlogParser-template.yaml
  kebechet/base/openshift-templates/kebechet.yaml
  mi-scheduler/base/openshift-templates/mi-run-template.yaml
  package-extract/base/openshift-templates/package-extract.yaml
  qeb-hwt-github-app/base/openshift-templates/qeb-hwt.yaml
  revsolver/base/openshift-templates/revsolve_and_sync-template.yaml
  security-indicators/base/openshift-templates/security-indicators.yaml
  solver/base/openshift-templates/solve_and_sync-template.yaml
Labels: approved, size/S

#366 fix spelling
  amun/base/argo-workflows/inspection-build-with-cpu.yaml
  amun/base/argo-workflows/inspection-run-with-cpu.yaml
  graph-sync/base/argo-workflows/sync-template.yaml
  init-job/base/argo-workflows/initialize-schema.yaml
  init-job/base/argo-workflows/register-indexes.yaml
  init-job/base/argo-workflows/solve-core-packages.yaml
  init-job/base/argo-workflows/solve-data-science-packages.yaml
  mi-scheduler/base/argo-workflows/mi-workflow-template.yaml
  package-extract/base/argo-workflows/package-extract.yaml
  revsolver/base/argo-workflows/revsolver-template.yaml
Labels: approved, size/M

#367 Add workflow metrics for solver
  solver/base/argo-workflows/solver-template.yaml
Labels: approved, size/S

#342 Send test environment SLO report to Thoth Team only
  slo-reporter/overlays/test/configmap.yaml
Labels: approved, kind/feature, size/XS

#368 Increase solver CPU resources and time allocated
  solver/base/argo-workflows/solver-template.yaml
Labels: approved, size/XS

#369 Always perform garbage collection of pods
  kebechet/base/openshift-templates/kebechet.yaml
  qeb-hwt-github-app/base/openshift-templates/qeb-hwt.yaml
  revsolver/base/openshift-templates/revsolve_and_sync-template.yaml
  security-indicators/base/openshift-templates/security-indicators.yaml
  solver/base/openshift-templates/solve_and_sync-template.yaml
Labels: approved, size/S

#370 Bump adviser to v0.16.0 in stage
  adviser/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#371 Revert "Bump adviser to v0.16.0 in stage"
  adviser/overlays/stage/imagestreamtag.yaml
Labels: size/XS

#354 Modify templates for component name and service
  solver/base/argo-workflows/parse-solver-inputs.yaml
  solver/base/openshift-templates/solve_and_sync-template.yaml
Labels: approved, size/S

#373 Reduce workflow parallelism to 1 in amun-inspection-stage
  amun/overlays/amun-inspection/configmaps.yaml
Labels: approved, size/XS

#374 Give 50 minutes to all workflows to finish
  adviser/base/openshift-templates/adviser.yaml
  adviser/base/openshift-templates/dependency-monkey.yaml
  adviser/base/openshift-templates/provenance-checker.yaml
  amun/base/openshift-templates/inspection-with-cpu-workflow.yaml
  amun/base/openshift-templates/inspection-workflow.yaml
  buildlog-parser/base/openshift-templates/buildlogParser-template.yaml
  init-job/base/argo-workflows/initializer.yaml
  kebechet/base/openshift-templates/kebechet.yaml
  mi-scheduler/base/openshift-templates/mi-run-template.yaml
  package-extract/base/openshift-templates/package-extract.yaml
  qeb-hwt-github-app/base/openshift-templates/qeb-hwt.yaml
  revsolver/base/argo-workflows/revsolver-template.yaml
  security-indicators/base/openshift-templates/security-indicators.yaml
  solver/base/argo-workflows/solver-template.yaml
  solver/base/openshift-templates/solve_and_sync-template.yaml
Labels: approved, size/S

#377 Clean up inspections after 3 days and increase active seconds
  amun/base/openshift-templates/inspection-with-cpu-workflow.yaml
  amun/base/openshift-templates/inspection-workflow.yaml
Labels: approved, size/S

#378 Increase parallelism for the current inspection batch
  amun/overlays/amun-inspection/configmaps.yaml
Labels: approved, size/XS

#379 Increase parallelism even more
  amun/overlays/amun-inspection/configmaps.yaml
Labels: approved, size/XS

#380 Increase parallelism even more
  amun/overlays/amun-inspection/configmaps.yaml
Labels: approved, size/XS

#381 Reduce parallelism in thoth-middletier-stage
  core/overlays/middletier-stage/configmaps.yaml
Labels: approved, size/XS

#382 Try to clean up workflows as soon as possible
  revsolver/base/openshift-templates/revsolve_and_sync-template.yaml
  solver/base/openshift-templates/solve_and_sync-template.yaml
Labels: approved, size/S

#383 Set default TTL in middletier to 10 seconds
  core/overlays/middletier-stage/configmaps.yaml
Labels: approved, size/XS

#375 Bump adviser to version 0.16.0 in stage
  adviser/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#386 updated kafka certs for stage and test
  core/overlays/stage/secrets.enc.yaml
  core/overlays/test/secrets.enc.yaml
Labels: approved, size/L

#387 Decrease inspection deadline
  amun/base/openshift-templates/inspection-with-cpu-workflow.yaml
  amun/base/openshift-templates/inspection-workflow.yaml
Labels: approved, size/XS

#388 Schedule graph-refresh each hour
  graph-refresh/base/cronjob.yaml
Labels: approved, size/XS

#390 Allow user-api to retrieve pod logs
  user-api/base/role.yaml
Labels: approved, size/XS

#391 patch the roles for pods logs
  user-api/base/role.yaml
Labels: approved, size/S

#393 patch the certs for kafka deployment
  core/overlays/stage/secrets.enc.yaml
  core/overlays/test/secrets.enc.yaml
Labels: approved, size/L

#394 Use solver in version 1.6.1 in stage environment
  solver/overlays/stage/imagestreamtag.yaml
Labels: approved, size/S

#397 Bump solver version to 1.6.2
  solver/overlays/stage/imagestreamtag.yaml
  solver/overlays/test/imagestreamtag.yaml
Labels: approved, size/S

#396 Decrease parallelism to 1 for the current batch
  amun/overlays/amun-inspection/configmaps.yaml
Labels: approved, size/XS

#401 bump parallelism for backend namespace
  core/overlays/backend-stage/configmaps.yaml
Labels: approved, size/XS

#399 Add tasks to solver workflow for Adviser Re Run messages
  core/base/argo-workflows/send-messages.yaml
  solver/base/argo-workflows/parse-solved-package.yaml
  solver/base/openshift-templates/solve_and_sync-template.yaml
Labels: approved, size/L

#402 Change variable name
  adviser/base/argo-workflows/kebechet-run-results.yaml
  adviser/base/argo-workflows/trigger-integration.yaml
  adviser/base/openshift-templates/adviser.yaml
Labels: approved, size/S

#404 Correct env variables and indentation
  core/base/argo-workflows/send-messages.yaml
  solver/base/argo-workflows/parse-solved-package.yaml
  solver/base/openshift-templates/solve_and_sync-template.yaml
Labels: approved, size/S

#405 include all argo workflows for solver in kustomize
  solver/base/kustomization.yaml
Labels: approved, size/XS

#406 include all argo workflows for core to kustomize
  core/base/kustomization.yaml
Labels: approved, size/XS

#403 Bumped kebechet to 1.05
  kebechet/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#410 Remove variable not required
  solver/base/argo-workflows/parse-solved-package.yaml
Labels: approved, size/XS

#411 Advise-reporter only producer
  advise-reporter/base/deploymentconfig.yaml
  advise-reporter/base/kustomization.yaml
  advise-reporter/base/route.yaml
  advise-reporter/base/service.yaml
Labels: approved, size/L

#412 Bump workflow helpers version to v0.1.7
  core/overlays/stage/imagestreamtags.yaml
Labels: approved, size/XS

#414 Use correct output file name
  core/base/argo-workflows/send-messages.yaml
  solver/base/argo-workflows/parse-solved-package.yaml
  solver/base/argo-workflows/parse-solver-inputs.yaml
  solver/base/openshift-templates/solve_and_sync-template.yaml
Labels: approved, size/M

#385 Bump user-api to v0.6.16 in stage
  user-api/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#415 Increase parallelism in backend namespace
  core/overlays/backend-stage/configmaps.yaml
Labels: approved, size/XS

#417 Retry solver and revsolver to bypass possible networking issues
  revsolver/base/argo-workflows/revsolver-template.yaml
  solver/base/argo-workflows/solver-template.yaml
Labels: approved, size/XS

#419 Add thoth repos to be checked
  prow/overlays/thoth-station/config.yaml
Labels: approved, size/XS

#420 Bump metrics-exporter version to v0.8.8
  metrics-exporter/overlays/stage/imagestreamtag.yaml
  metrics-exporter/overlays/test/imagestreamtag.yaml
Labels: approved, size/XS

#418 Bump nepthys version in ocp to 0.2.0
  nepthys/overlays/ocp/imagestreamtag.yaml
Labels: approved, size/XS

#430 Bump graph-sync version to v0.7.3
  core/overlays/test/imagestreamtags.yaml
Labels: approved, size/XS

#434 Improve readability
  security-indicators/base/openshift-templates/security-indicators.yaml
Labels: approved, size/M

#435 Rename output and more readability
  security-indicators/base/argo-workflows/aggregator-template.yaml
  security-indicators/base/openshift-templates/security-indicators.yaml
Labels: approved, size/M

#436 Bump version of metrics-exporter to v0.8.10
  metrics-exporter/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#437 Increase parallelism in middletier-stage
  core/overlays/middletier-stage/configmaps.yaml
Labels: approved, size/XS

#438 Increase parallelism in backend-stage
  core/overlays/backend-stage/configmaps.yaml
Labels: approved, size/XS

#441 Bump User API to v0.16.7 in stage environment
  user-api/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#425 initial modifications for turning to producer
  package-releases/base/kustomization.yaml
  package-releases/overlays/test/cronjob.yaml
  package-releases/overlays/test/kustomization.yaml
Labels: approved, size/L

#444 Updated cronjob to use producer
  graph-refresh/overlays/test/cronjob.yaml
  graph-refresh/overlays/test/imagestreamtag.yaml
Labels: approved, size/XS

#447 Add metrics and improve readability
  security-indicators/base/argo-workflows/aggregator-template.yaml
  security-indicators/base/argo-workflows/bandit-template.yaml
  security-indicators/base/argo-workflows/cloc-template.yaml
  security-indicators/base/openshift-templates/security-indicators.yaml
Labels: approved, size/M

#446 Bump adviser version to 0.17.0 in stage
  adviser/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#448 Hardcode predictor config to workaround parsing issue
  adviser/base/openshift-templates/adviser.yaml
Labels: approved, size/XS

#449 Increase parallelism in middletier even more
  core/overlays/middletier-stage/configmaps.yaml
Labels: approved, size/XS

#450 Increase parallelism in middletier even more
  core/overlays/middletier-stage/configmaps.yaml
Labels: approved, size/XS

#451 Revert "Hardcode predictor config to workaround parsing issue"
  adviser/base/openshift-templates/adviser.yaml
Labels: approved, size/XS

#453 setup kustomize manifest to handle graph-backup with argocd
  graph-backup-job/overlays/stage/cronjob.yaml
  graph-backup-job/overlays/stage/imagestreamtag.yaml
  graph-backup-job/overlays/stage/job-generate-name.yaml
  graph-backup-job/overlays/stage/kustomization.yaml
  graph-backup-job/overlays/stage/thoth-notification.yaml
  graph-backup-job/overlays/test/imagestreamtag.yaml
  graph-backup-job/overlays/test/job-generate-name.yaml
  graph-backup-job/overlays/test/kustomization.yaml
  graph-backup-job/overlays/test/thoth-notification.yaml
Labels: approved, size/L

#454 Add thoth config
  .thoth.yaml
  CHANGELOG.md
  version.py
Labels: approved, size/S

#455 Adjust version string based on the last version identifier
  version.py
Labels: approved, size/XS

#456 Move SI workflow to stage to start collecting SI
  graph-sync/overlays/stage/imagestreamtag.yaml
  security-indicators/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#458 Increase parallelism in middletier-stage
  core/overlays/middletier-stage/configmaps.yaml
Labels: approved, size/XS

#457 Bump version v0.2.1 for nepthys
  nepthys/overlays/ocp/imagestreamtag.yaml
Labels: approved, size/XS

#460 Bump version v1.0.6 for kebechet
  kebechet/overlays/prod/imagestreamtag.yaml
  kebechet/overlays/stage/imagestreamtag.yaml
  kebechet/overlays/test/imagestreamtag.yaml
Labels: approved, size/XS

#461 Revert ":ship: Bump version v1.0.6 for kebechet (#460)"
  kebechet/overlays/prod/imagestreamtag.yaml
  kebechet/overlays/stage/imagestreamtag.yaml
  kebechet/overlays/test/imagestreamtag.yaml
Labels: approved, size/XS

#462 Adjust env variable
  core/overlays/stage/configmaps.yaml
  core/overlays/test/configmaps.yaml
  slo-reporter/base/cronjob.yaml
Labels: approved, size/XS

#463 Bumped kebechet to 1.0.7
  kebechet/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#464 remove package update consumer deployment
  package-update/base/deploymentconfig.yaml
  package-update/base/kustomization.yaml
  package-update/base/route.yaml
  package-update/base/service.yaml
  package-update/overlays/stage/route.yaml
  package-update/overlays/stage/service.yaml
  package-update/overlays/test/route.yaml
  package-update/overlays/test/service.yaml
Labels: approved, size/L

#465 Use infra env variable
  metrics-exporter/base/deploymentconfig.yaml
Labels: approved, size/XS

#466 Revert "Bumped kebechet to 1.0.7"
  kebechet/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#467 Update argo to v.2.11.0
  core/overlays/test/argo-namespace-install.yaml
Labels: approved, size/XS

#468 Update kebechet to 1.0.8
  kebechet/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#470 Stop revsolver and security messages
  graph-refresh/overlays/test/cronjob.yaml
Labels: approved, size/XS

#471 enable argocli and wc to use local images
  core/overlays/test/argo-namespace-install.yaml
Labels: approved, size/M

#473 bump up resource for nepthys
  nepthys/base/cronjob.yaml
Labels: approved, size/XS

#472 Propagate deployment-name and Amun API url to Amun deploymentconfig
  amun/base/deploymentconfig.yaml
Labels: approved, size/XS

#474 bump metrics-exporter stage to v0.8.12
  metrics-exporter/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#475 Introduce workflow metrics for quality and latency
  adviser/base/argo-workflows/advise.yaml
  adviser/base/openshift-templates/adviser.yaml
  adviser/base/openshift-templates/dependency-monkey.yaml
  adviser/base/openshift-templates/provenance-checker.yaml
  revsolver/base/openshift-templates/revsolve_and_sync-template.yaml
  security-indicators/base/openshift-templates/security-indicators.yaml
  solver/base/argo-workflows/solver-template.yaml
  solver/base/openshift-templates/solve_and_sync-template.yaml
Labels: approved, size/L

#476 fix the argo imagestream lookup policy
  core/overlays/test/argo-namespace-install.yaml
Labels: approved, size/XS

#477 Minor adjustments and add metrics for qeb-hwt and kebechet
  kebechet/base/openshift-templates/kebechet.yaml
  qeb-hwt-github-app/base/openshift-templates/qeb-hwt.yaml
  revsolver/base/openshift-templates/revsolve_and_sync-template.yaml
  security-indicators/base/openshift-templates/security-indicators.yaml
  solver/base/openshift-templates/solve_and_sync-template.yaml
Labels: approved, size/M

#478 Bump version v0.2.2 for nepthys
  nepthys/overlays/ocp/imagestreamtag.yaml
Labels: approved, size/XS

#479 update argo workloads and metrics-exporter
  amun/overlays/amun-inspection/argo-namespace-install.yaml
  core/overlays/backend-stage/argo-namespace-install.yaml
  core/overlays/backend-stage/kustomization.yaml
  core/overlays/middletier-stage/argo-namespace-install.yaml
  core/overlays/middletier-stage/kustomization.yaml
  metrics-exporter/overlays/stage/imagestreamtag.yaml
Labels: approved, size/L

#483 remove non used manifest from kustomize manifest
  package-update/base/kustomization.yaml
Labels: approved, size/XS

#484 provenance clear non required configmap requirements
  adviser/base/argo-workflows/provenance-check.yaml
Labels: approved, size/XS

#485 Bump version v1.0.9 for kebechet
  kebechet/overlays/prod/imagestreamtag.yaml
  kebechet/overlays/stage/imagestreamtag.yaml
  kebechet/overlays/test/imagestreamtag.yaml
Labels: approved, size/XS

#490 fix configmap qeb-hwt-workflow usage
  adviser/base/argo-workflows/trigger-integration.yaml
  adviser/base/configmap.yaml
  adviser/base/kustomization.yaml
Labels: approved, size/S

#489 schedule package-update to run in stage
  package-update/base/cronjob.yaml
  package-update/overlays/test/cronjob.yaml
Labels: approved, size/XS

#488 include labels for revsolver workflow
  revsolver/base/openshift-templates/revsolve_and_sync-template.yaml
Labels: approved, size/XS

#494 Bump versions for qeb-hwt and user-api
  qeb-hwt-github-app/overlays/ocp/imagestreamtag.yaml
  user-api/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#496 maintain consistency in package update manifest files
  package-update/overlays/stage/kustomization.yaml
  package-update/overlays/stage/thoth-notification.yaml
  package-update/overlays/test/kustomization.yaml
  package-update/overlays/test/thoth-notification.yaml
  package-update/overlays/test/unsuspend-cronjob.yaml
Labels: approved, size/M

#495 Bump adviser to v0.18.0 in stage
  adviser/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#497 fix misspelled namespace name
  investigator/overlays/stage/role_binding.yaml
Labels: approved, size/XS

#498 updated role for investigator to view configmaps
  investigator/overlays/stage/role.yaml
Labels: approved, size/S

#500 Moved test crob-job to base and updated image tag
  graph-refresh/base/cronjob.yaml
  graph-refresh/overlays/stage/imagestreamtag.yaml
  graph-refresh/overlays/test/cronjob.yaml
Labels: approved, size/L

#501 add missing variables to list solvers
  graph-refresh/base/cronjob.yaml
Labels: approved, size/XS

#502 Bump investigator to v0.4.12
  core/overlays/stage/imagestreamtags.yaml
Labels: approved, size/XS

#503 Increase learning rate for Thoth (more messages)
  graph-refresh/base/cronjob.yaml
Labels: approved, size/XS

#505 Bump management-api to v0.7.2 to update schema
  management-api/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#506 Correct name of metrics
  kebechet/base/openshift-templates/kebechet.yaml
Labels: approved, size/XS

#509 Move package release producer to stage
  package-releases/base/cronjob.yaml
  package-releases/overlays/stage/imagestreamtag.yaml
  package-releases/overlays/test/cronjob.yaml
Labels: approved, size/L

#482 add parse-solver-output.yaml
  solver/overlays/test/argo-workflows/parse-solver-output.yaml
  solver/overlays/test/argo-workflows/solver-template.yaml
  solver/overlays/test/kustomization.yaml
  solver/overlays/test/openshift-templates/solve_and_sync-template.yaml
Labels: approved, size/L

#510 Add parameters to test Kafka user-api producer
  user-api/overlays/test/deploymentconfig.yaml
  user-api/overlays/test/kustomization.yaml
Labels: approved, size/L

#512 Increase parallelism in middletier-stage
  core/overlays/middletier-stage/configmaps.yaml
Labels: approved, size/XS

#513 Add backend namespace env to investigator to schedule workflows
  investigator/base/deploymentconfig.yaml
Labels: approved, size/XS

#515 patch roles for user-api to pull logs
  user-api/base/role.yaml
  user-api/overlays/stage/kustomization.yaml
  user-api/overlays/stage/put-into-backend-namespace.yaml
  user-api/overlays/stage/role-binding.yaml
Labels: approved, size/M

#514 Move user-api investigator Kafka based to stage
  core/overlays/stage/imagestreamtags.yaml
  user-api/base/deploymentconfig.yaml
  user-api/overlays/stage/imagestreamtag.yaml
  user-api/overlays/test/deploymentconfig.yaml
  user-api/overlays/test/kustomization.yaml
Labels: approved, size/L

#516 patch up kustomize config for solver
  solver/overlays/test/kustomization.yaml
Labels: approved, size/XS

#517 Move solver from test to base
  solver/base/argo-workflows/parse-solved-package.yaml
  solver/base/argo-workflows/parse-solver-inputs.yaml
  solver/base/argo-workflows/parse-solver-output.yaml
  solver/base/kustomization.yaml
  solver/base/openshift-templates/solve_and_sync-template.yaml
  solver/overlays/test/argo-workflows/solver-template.yaml
  solver/overlays/test/kustomization.yaml
  solver/overlays/test/openshift-templates/solve_and_sync-template.yaml
Labels: approved, size/XL
