Repository thoth-station/thoth-application, pull requests merged in 2020-10, with the labels that each got.

#518 Move to stage newer versions
  core/overlays/stage/configmaps.yaml
  core/overlays/stage/imagestreamtags.yaml
  core/overlays/test/configmaps.yaml
  graph-refresh/overlays/stage/imagestreamtag.yaml
  management-api/overlays/stage/imagestreamtag.yaml
  metrics-exporter/base/deploymentconfig.yaml
  metrics-exporter/overlays/stage/imagestreamtag.yaml
  slo-reporter/base/cronjob.yaml
  slo-reporter/overlays/stage/imagestreamtag.yaml
Labels: approved, size/M

#519 Adjust env name
  core/overlays/stage/configmaps.yaml
  core/overlays/test/configmaps.yaml
  metrics-exporter/base/deploymentconfig.yaml
Labels: approved, size/XS

#520 Bump multiple component releases to stage
  core/overlays/stage/imagestreamtags.yaml
  metrics-exporter/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#522 Release of version 2020.10.01
  CHANGELOG.md
  version.py
Labels: approved, bot, size/L

#523 Adjust GH template for calendar releases
  .github/ISSUE_TEMPLATE/calendar-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
Labels: approved, size/M

#525 remove the pre-fixed namespace
  slo-reporter/overlays/stage/kustomization.yaml
Labels: approved, size/XS

#526 include idh repo into prow config
  prow/overlays/thoth-station/config.yaml
Labels: approved, size/XS

#531 Bump metrics-exporter version to v0.8.16
  metrics-exporter/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#533 Do not schedule revsolver
  investigator/base/deploymentconfig.yaml
Labels: approved, size/XS

#530 Thoth does not SI analyze package that do not provide distro
  core/overlays/stage/imagestreamtags.yaml
  security-indicators/base/argo-workflows/download-package-template.yaml
  security-indicators/base/openshift-templates/security-indicators.yaml
  solver/base/openshift-templates/solve_and_sync-template.yaml
Labels: approved, size/M

#534 Remove test from image
  security-indicators/base/argo-workflows/download-package-template.yaml
Labels: approved, size/XS

#539 Bump investigator to v0.5.3
  core/overlays/stage/imagestreamtags.yaml
Labels: approved, size/XS

#537 Add parameter to CM in stage
  core/overlays/stage/configmaps.yaml
  slo-reporter/base/cronjob.yaml
Labels: approved, size/S

#543 Add missing parameter in core CM
  core/overlays/stage/configmaps.yaml
Labels: approved, size/XS

#540 Reduce scheduling from graph-refresh
  graph-refresh/base/cronjob.yaml
Labels: approved, size/XS

#541 Move CM to core so it is available to adviser and qeb-hwt
  core/base/configmaps.yaml
  core/overlays/stage/configmaps.yaml
  core/overlays/test/configmaps.yaml
  qeb-hwt-github-app/overlays/ocp/configmap.yaml
  qeb-hwt-github-app/overlays/ocp/kustomization.yaml
Labels: approved, size/M

#546 bump package-update resources and image tag
  advise-reporter/base/cronjob.yaml
  core/overlays/backend-stage/configmaps.yaml
  core/overlays/middletier-stage/configmaps.yaml
  core/overlays/prod/backend-prod/configmaps.yaml
  core/overlays/prod/middletier-prod/configmaps.yaml
  core/overlays/quicklab/configmaps.yaml
  core/overlays/test/configmaps.yaml
  package-update/base/cronjob.yaml
  package-update/overlays/prod/cronjob.yaml
  package-update/overlays/prod/imagestreamtag.yaml
  package-update/overlays/stage/cronjob.yaml
  package-update/overlays/stage/imagestreamtag.yaml
  package-update/overlays/test/cronjob.yaml
Labels: approved, size/M

#547 set initial delay for readiness probe for investigator consumer
  investigator/base/deploymentconfig.yaml
Labels: approved, size/XS

#548 Activate advise reporter in stage
  advise-reporter/base/cronjob.yaml
  advise-reporter/overlays/stage/cronjob.yaml
  advise-reporter/overlays/stage/imagestreamtag.yaml
  advise-reporter/overlays/test/cronjob.yaml
Labels: approved, size/S

#550 separate overlays based on environment
  qeb-hwt-github-app/overlays/stage/configmap.yaml
  qeb-hwt-github-app/overlays/stage/imagestreamtag.yaml
  qeb-hwt-github-app/overlays/stage/job-generate-name.yaml
  qeb-hwt-github-app/overlays/stage/kustomization.yaml
  qeb-hwt-github-app/overlays/stage/put-into-backend-namespace.yaml
  qeb-hwt-github-app/overlays/stage/put-into-infra-namespace.yaml
  qeb-hwt-github-app/overlays/stage/secret-generator.yaml
  qeb-hwt-github-app/overlays/stage/secrets.enc.yaml
  qeb-hwt-github-app/overlays/stage/thoth-notification.yaml
  qeb-hwt-github-app/overlays/stage/ultrahook-deployment.yaml
  qeb-hwt-github-app/overlays/test/configmap.yaml
  qeb-hwt-github-app/overlays/test/imagestreamtag.yaml
  qeb-hwt-github-app/overlays/test/job-generate-name.yaml
  qeb-hwt-github-app/overlays/test/kustomization.yaml
  qeb-hwt-github-app/overlays/test/secret-generator.yaml
  qeb-hwt-github-app/overlays/test/secrets.enc.yaml
  qeb-hwt-github-app/overlays/test/thoth-notification.yaml
  qeb-hwt-github-app/overlays/test/ultrahook-deployment.yaml
Labels: approved, hacktoberfest-accepted, size/XL

#551 update stage with kafka in thoth02 cluster
  core/overlays/stage/configmaps.yaml
  core/overlays/stage/secrets.enc.yaml
Labels: approved, size/L

#549 Qebhwt use send messages
  qeb-hwt-github-app/README.md
  qeb-hwt-github-app/overlays/test/argo-workflows/qeb-hwt-integration.yaml
  qeb-hwt-github-app/overlays/test/openshift-templates/qeb-hwt.yaml
Labels: approved, size/L

#552 Added customize change
  qeb-hwt-github-app/overlays/test/kustomization.yaml
Labels: approved, size/XS

#553 More metrics
  graph-refresh/overlays/stage/imagestreamtag.yaml
  package-releases/base/cronjob.yaml
  package-releases/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#556 allow metrics exporter to get imagestreams
  metrics-exporter/base/role.yaml
Labels: approved, size/S

#557 Add missing variable for adviser to send messages
  adviser/base/argo-workflows/investigate-unresolved-package.yaml
Labels: approved, size/S

#560 Add files to kustomize
  advise-reporter/overlays/stage/kustomization.yaml
  advise-reporter/overlays/test/kustomization.yaml
Labels: approved, size/XS

#562 Moved new templates to base
  core/overlays/stage/imagestreamtags.yaml
  qeb-hwt-github-app/base/argo-workflows/qeb-hwt-integration.yaml
  qeb-hwt-github-app/base/openshift-templates/qeb-hwt.yaml
  user-api/overlays/stage/imagestreamtag.yaml
Labels: approved, size/M

#565 bump nepthys image version v0.2.2-dev
  nepthys/overlays/ocp/imagestreamtag.yaml
Labels: approved, size/XS

#564 Added Kebechet run url templates
  kebechet/base/argo-workflows/kebechet-run-url.yaml
  kebechet/base/openshift-templates/kebechet-run-url.yaml
  kebechet/overlays/prod/kustomization.yaml
  kebechet/overlays/stage/kustomization.yaml
Labels: approved, size/L

#563 Bump nepthys to 0.2.3
  nepthys/overlays/ocp/imagestreamtag.yaml
Labels: approved, size/XS

#567 switch to kafka backed with amq streams for test instance
  core/overlays/test/configmaps.yaml
  core/overlays/test/secrets.enc.yaml
Labels: approved, size/L

#569 bump up nepthys version to v0.2.4
  nepthys/overlays/ocp/imagestreamtag.yaml
Labels: approved, size/XS

#570 switch to ocp kafka backed by amq streams in test
  core/overlays/test/configmaps.yaml
  core/overlays/test/secrets.enc.yaml
Labels: approved, size/L

#572 Dump slo-reporter to v0.5.9 in stage
  slo-reporter/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#576 Increase ingestion
  graph-refresh/base/cronjob.yaml
Labels: approved, size/XS

#573 setup kafka-protocol env var for all kafka using applications
  advise-reporter/base/cronjob.yaml
  adviser/base/argo-workflows/investigate-unresolved-package.yaml
  core/base/argo-workflows/send-message.yaml
  core/base/argo-workflows/send-messages.yaml
  core/overlays/stage/configmaps.yaml
  core/overlays/test/configmaps.yaml
  graph-refresh/base/cronjob.yaml
  investigator/base/deploymentconfig.yaml
  package-releases/base/cronjob.yaml
  package-update/base/cronjob.yaml
  user-api/base/deploymentconfig.yaml
Labels: approved, size/M

#574 re-arrange amun manifest based on deployment environments
  amun/overlays/amun-api/kustomization.yaml
  amun/overlays/stage/amun-api/configmaps.yaml
  amun/overlays/stage/amun-api/imagestreamtag.yaml
  amun/overlays/stage/amun-api/job-generate-name.yaml
  amun/overlays/stage/amun-api/kustomization.yaml
  amun/overlays/stage/amun-api/metrics-exporter-reader.yaml
  amun/overlays/stage/amun-api/put-into-inspection-namespace.yaml
  amun/overlays/stage/amun-api/role_binding.yaml
  amun/overlays/stage/amun-api/route.enc.yaml
  amun/overlays/stage/amun-api/secret-generator.yaml
  amun/overlays/stage/amun-api/secrets.enc.yaml
  amun/overlays/stage/amun-api/thoth-notification.yaml
  amun/overlays/stage/amun-inspection/argo-namespace-install.yaml
  amun/overlays/stage/amun-inspection/argo-ui-route.yaml
  amun/overlays/stage/amun-inspection/argo-workflow-controller-metrics.yaml
  amun/overlays/stage/amun-inspection/configmaps.yaml
  amun/overlays/stage/amun-inspection/job-generate-name.yaml
  amun/overlays/stage/amun-inspection/kustomization.yaml
  amun/overlays/stage/amun-inspection/metrics-exporter-reader.yaml
  amun/overlays/stage/amun-inspection/thoth-notification.yaml
  amun/overlays/stage/job-generate-name.yaml
  amun/overlays/stage/secrets.enc.yaml
  amun/overlays/stage/thoth-notification.yaml
Labels: approved, size/L

#578 re-arrange the core stage for consistency of manifests
  core/overlays/stage/backend-stage/argo-namespace-install.yaml
  core/overlays/stage/backend-stage/argo-ui-route.yaml
  core/overlays/stage/backend-stage/argo-workflow-controller-metrics.yaml
  core/overlays/stage/backend-stage/configmaps.yaml
  core/overlays/stage/backend-stage/job-generate-name.yaml
  core/overlays/stage/backend-stage/kustomization.yaml
  core/overlays/stage/backend-stage/thoth-notification.yaml
  core/overlays/stage/common/configmaps.yaml
  core/overlays/stage/common/imagestreamtags.yaml
  core/overlays/stage/common/kustomization.yaml
  core/overlays/stage/common/roles/kustomization.yaml
  core/overlays/stage/common/roles/metrics-exporter-reader.yaml
  core/overlays/stage/common/secret-generator.yaml
  core/overlays/stage/common/secrets.enc.yaml
  core/overlays/stage/frontend-stage/job-generate-name.yaml
  core/overlays/stage/frontend-stage/kustomization.yaml
  core/overlays/stage/frontend-stage/thoth-notification.yaml
  core/overlays/stage/graph-stage/job-generate-name.yaml
  core/overlays/stage/graph-stage/kustomization.yaml
  core/overlays/stage/graph-stage/pgbouncer.yaml
  core/overlays/stage/graph-stage/postgresql-metrics-exporter.yaml
  core/overlays/stage/graph-stage/postgresql.yaml
  core/overlays/stage/graph-stage/thoth-notification.yaml
  core/overlays/stage/infra-stage/job-generate-name.yaml
  core/overlays/stage/infra-stage/kustomization.yaml
  core/overlays/stage/infra-stage/thoth-notification.yaml
  core/overlays/stage/middletier-stage/argo-namespace-install.yaml
  core/overlays/stage/middletier-stage/argo-ui-route.yaml
  core/overlays/stage/middletier-stage/argo-workflow-controller-metrics.yaml
  core/overlays/stage/middletier-stage/configmaps.yaml
  core/overlays/stage/middletier-stage/job-generate-name.yaml
  core/overlays/stage/middletier-stage/kustomization.yaml
  core/overlays/stage/middletier-stage/thoth-notification.yaml
Labels: approved, size/S

#571 Adjust adviser workflow tasks
  advise-reporter/base/cronjob.yaml
  adviser/base/argo-workflows/parse_adviser_output.yaml
  adviser/base/openshift-templates/adviser.yaml
  core/overlays/stage/common/imagestreamtags.yaml
  solver/base/openshift-templates/solve_and_sync-template.yaml
Labels: approved, size/M

#580 enable qeb-hwt to access deployment-name from configmap
  qeb-hwt-github-app/base/deploymentconfig.yaml
  qeb-hwt-github-app/overlays/ocp/configmap.yaml
  qeb-hwt-github-app/overlays/ocp/imagestreamtag.yaml
  qeb-hwt-github-app/overlays/ocp/job-generate-name.yaml
  qeb-hwt-github-app/overlays/ocp/kustomization.yaml
  qeb-hwt-github-app/overlays/ocp/put-into-backend-namespace.yaml
  qeb-hwt-github-app/overlays/ocp/put-into-infra-namespace.yaml
  qeb-hwt-github-app/overlays/ocp/secret-generator.yaml
  qeb-hwt-github-app/overlays/ocp/secrets.enc.yaml
  qeb-hwt-github-app/overlays/ocp/thoth-notification.yaml
  qeb-hwt-github-app/overlays/ocp/ultrahook-deployment.yaml
Labels: approved, size/L

#581 include kebechet templates to the kustomize manifest
  kebechet/base/kustomization.yaml
Labels: approved, size/XS

#582 patch up the apiversion for postgresql metrics deployment
  core/overlays/prod/graph-prod/postgresql-metrics-exporter.yaml
  core/overlays/test/postgresql-metrics-exporter.yaml
Labels: approved, size/XS

#583 Add Kebechet administrator
  kebechet/base/argo-workflows/kebechet-administrator.yaml
  kebechet/base/kustomization.yaml
  kebechet/base/openshift-templates/kebechet-administrator.yaml
  kebechet/overlays/stage/kustomization.yaml
Labels: approved, size/L

#584 bump slo-reporter to v0.6.0
  slo-reporter/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#585 solvers confimap consistency across the environments
  core/base/configmaps.yaml
  core/overlays/ocp4-stage/common/configmaps.yaml
  core/overlays/prod/common/configmaps.yaml
  core/overlays/stage/common/configmaps.yaml
  core/overlays/test/configmaps.yaml
Labels: approved, size/M

#587 Updated the certs for route53
  amun/overlays/prod/amun-api/route.enc.yaml
  amun/overlays/stage/amun-api/route.enc.yaml
  amun/overlays/test/route.enc.yaml
  management-api/overlays/prod/route.enc.yaml
  management-api/overlays/stage/route.enc.yaml
  management-api/overlays/test/route.enc.yaml
  user-api/overlays/prod/route.enc.yaml
  user-api/overlays/stage/khemenu.route.enc.yaml
  user-api/overlays/stage/route.enc.yaml
  user-api/overlays/test/route.enc.yaml
Labels: approved, size/XL

#589 update the configmap with correct qebhwt urls
  core/overlays/stage/common/configmaps.yaml
  core/overlays/test/configmaps.yaml
Labels: approved, size/XS

#590 Add file to kustomization and remove old one
  adviser/base/argo-workflows/investigate-unresolved-package.yaml
  adviser/base/argo-workflows/parse-adviser-output.yaml
  adviser/base/kustomization.yaml
Labels: approved, hacktoberfest-accepted, size/M

#592 Bump adviser to v0.19.0 in stage
  adviser/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#586 confluent kafka deployment changes
  investigator/overlays/test/deploymentconfig.yaml
  investigator/overlays/test/kustomization.yaml
Labels: approved, do-not-merge/hold, hacktoberfest-accepted, kind/feature, size/L

#595 Release of version 2020.10.28
  CHANGELOG.md
  version.py
Labels: approved, bot, size/M

#593 make cve-update kafka producer
  cve-update/overlays/test/cronjob.yaml
  cve-update/overlays/test/kustomization.yaml
Labels: approved, size/L

#596 change bool to str value
  cve-update/overlays/test/cronjob.yaml
Labels: approved, size/XS

#597 migrate stage deployment to use ocp kafka
  core/overlays/stage/common/configmaps.yaml
  core/overlays/stage/common/secrets.enc.yaml
  cve-update/overlays/test/cronjob.yaml
Labels: approved, size/L

#599 Release of version 2020.10.29
  CHANGELOG.md
  version.py
Labels: approved, bot, size/S

#598 Bump adviser to 0.19.1 in stage
  adviser/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#591 Added an readme of kebechet components
  kebechet/README.md
Labels: approved, size/XS

#600 Increase packages considered while we have 1 solver running
  graph-refresh/base/cronjob.yaml
Labels: approved, size/XS

#603 Bump advise-reporter version to v0.4.6 in stage
  advise-reporter/base/cronjob.yaml
  advise-reporter/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS
