Repository thoth-station/thoth-application, pull requests merged in 2020-08, with the labels that each got.

#204 Remove not found exception from Sentry reports
  user-api/base/deploymentconfig.yaml
Labels: approved, size/XS

#205 use quay based images for argo workflow controller
  core/overlays/middletier-stage/argo-namespace-install.yaml
Labels: size/XS

#206 :arrow_up: increase workflow controller memory
  core/overlays/middletier-stage/argo-namespace-install.yaml
Labels: size/XS

#207 Decrease solver TTL
  solver/base/openshift-templates/solve_and_sync-template.yaml
Labels: approved, size/XS

#201 add many build configs for testing
  advise-reporter/overlays/test/buildConfig.yaml
  adviser/overlays/test/buildConfig.yaml
  build-watcher/overlays/test/buildConfig.yaml
  core/overlays/test/buildConfig.yaml
  graph-backup-job/overlays/test/buildConfig.yaml
  graph-refresh/overlays/test/buildConfig.yaml
  init-job/overlays/test/buildConfig.yaml
  kebechet/overlays/test/buildConfig.yaml
  management-api/overlays/test/buildConfig.yaml
  metrics-exporter/overlays/test/buildConfig.yaml
  mi-scheduler/overlays/test/buildConfig.yaml
  package-extract/overlays/test/buildConfig.yaml
  package-update/overlays/test/buildConfig.yaml
  revsolver/overlays/test/buildConfig.yaml
  security-indicators/overlays/test/buildConfig.yaml
  slo-reporter/overlays/test/buildConfig.yaml
Labels: approved, size/XL

#208 provide kafka-secrets for solver send message
  solver/base/openshift-templates/solve_and_sync-template.yaml
Labels: size/XS

#209 topic exists in thoth.messaging so use existing topic name
  solver/base/openshift-templates/solve_and_sync-template.yaml
Labels: approved, size/XS

#193 Resubmit pending pods in Amun inspections
  amun/base/openshift-templates/inspection-with-cpu-workflow.yaml
  amun/base/openshift-templates/inspection-workflow.yaml
Labels: approved, size/XS

#211 handle nepthy deployment with argocd
  nepthys/base/cronjob.yaml
  nepthys/base/imagestreamtag.yaml
  nepthys/base/kustomization.yaml
  nepthys/overlays/ocp/buildConfig.yaml
  nepthys/overlays/ocp/imagestreamtag.yaml
  nepthys/overlays/ocp/job-generate-name.yaml
  nepthys/overlays/ocp/kustomization.yaml
  nepthys/overlays/ocp/secret-generator.yaml
  nepthys/overlays/ocp/secrets.enc.yaml
  nepthys/overlays/ocp/thoth-notification.yaml
Labels: size/L

#212 updated sefkhet-abwy manifest files
  sefkhet-abwy/base/deploymentconfig.yaml
  sefkhet-abwy/base/route.yaml
  sefkhet-abwy/overlays/ocp/secrets.enc.yaml
  sefkhet-abwy/overlays/ocp/ultrahook.yaml
Labels: approved, size/L

#213 Adjust workflow logic
  solver/base/openshift-templates/solve_and_sync-template.yaml
Labels: approved, size/XS

#192 maintianing consistency in the configmaps
  core/overlays/stage/configmaps.yaml
  core/overlays/test/configmaps.yaml
Labels: size/S

#219 manifest files for advise-reporter stage deployment
  advise-reporter/overlays/stage/imagestreamtag.yaml
  advise-reporter/overlays/stage/job-generate-name.yaml
  advise-reporter/overlays/stage/kustomization.yaml
  advise-reporter/overlays/stage/thoth-notification.yaml
Labels: size/L

#218 maintain consistency in ceph bucket storage
  amun/overlays/stage/configmaps.yaml
  amun/overlays/test/configmaps.yaml
Labels: size/XS

#217 include cronjob manifest from sefkhet-abwy
  sefkhet-abwy/base/kustomization.yaml
  sefkhet-abwy/overlays/ocp/kustomization.yaml
  sefkhet-abwy/overlays/ocp/thoth-friday-scrum-cronjob.yaml
  sefkhet-abwy/overlays/ocp/thoth-scrum-cronjob.yaml
Labels: size/L

#222 role-binding required for the user-api stage deployment
  user-api/base/kustomization.yaml
  user-api/base/role.yaml
  user-api/overlays/stage/kustomization.yaml
  user-api/overlays/stage/put-into-infra-namespace.yaml
  user-api/overlays/stage/role-binding.yaml
  user-api/overlays/test/kustomization.yaml
  user-api/overlays/test/role-binding.yaml
Labels: size/L

#224 include adviser template in stage development
  adviser/base/argo-workflows/kebechet-run-results.yaml
  adviser/overlays/stage/kustomization.yaml
  adviser/overlays/stage/put-into-middletier-namespace.yaml
  adviser/overlays/stage/secrets.enc.yaml
  user-api/overlays/stage/kustomization.yaml
Labels: approved, size/L

#210 encrypt the routes with tls certs
  amun/.sops.yaml
  amun/overlays/stage/route.enc.yaml
  amun/overlays/test/route.enc.yaml
  management-api/.sops.yaml
  management-api/overlays/stage/route.enc.yaml
  management-api/overlays/stage/route.yaml
  management-api/overlays/test/route.enc.yaml
  management-api/overlays/test/route.yaml
  user-api/.sops.yaml
  user-api/overlays/stage/route.enc.yaml
  user-api/overlays/stage/route.yaml
  user-api/overlays/test/route.enc.yaml
  user-api/overlays/test/route.yaml
Labels: approved, size/XL

#226 role-binding required for the management-api stage deployment
  management-api/overlays/stage/kustomization.yaml
  management-api/overlays/stage/put-into-infra-namespace.yaml
  management-api/overlays/stage/role-binding.yaml
  management-api/overlays/test/kustomization.yaml
  management-api/overlays/test/role-binding.yaml
Labels: approved, size/S

#227 update amun stage imagestreamtag
  amun/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#233 Missing env variables for SLO-reporter
  core/overlays/test/configmaps.yaml
  slo-reporter/base/cronjob.yaml
Labels: approved, size/M

#229 fix workflow output resolve
  adviser/base/argo-workflows/trigger-integration.yaml
Labels: approved, size/S

#232 Add missing env variables for advise-reporter
  advise-reporter/base/cronjob.yaml
  core/overlays/test/configmaps.yaml
Labels: approved, size/S

#234 Adjust variable name for solver parsing
  solver/base/argo-workflows/parse-solver-inputs.yaml
Labels: approved, size/XS

#236 Allow the user-api to schedule workflow in backend
  user-api/overlays/stage/role-binding.yaml
Labels: approved, size/S

#237 manifest files in different directory are not fetched directly
  kebechet/base/kustomization.yaml
  kebechet/overlays/stage/kustomization.yaml
  kebechet/overlays/test/kustomization.yaml
Labels: approved, size/XS

#238 Fix the wrong spelling of the directory
  kebechet/base/kustomization.yaml
Labels: approved, size/XS

#230 Update Amun API in stage environment
  amun/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#239 investigater image is required by adviser in stage
  core/overlays/stage/imagestreamtags.yaml
  core/overlays/test/imagestreamtags.yaml
Labels: approved, size/S

#240 Fix mis-match of workflow-helper env vars
  adviser/base/argo-workflows/trigger-integration.yaml
  qeb-hwt-github-app/base/argo-workflows/qeb-hwt-integration.yaml
Labels: approved, size/XS

#241 thamos log requires user-api to have access for pod logs
  user-api/overlays/stage/role-binding.yaml
Labels: approved, size/S

#243 Rename file
  solver/base/argo-workflows/parse-solver-inputs.yaml
  solver/base/openshift-templates/solve_and_sync-template.yaml
Labels: approved, size/XS

#225 updated manifest files based on requirement
  advise-reporter/base/deploymentconfig.yaml
  advise-reporter/base/kustomization.yaml
  advise-reporter/base/service.yaml
  adviser/base/kustomization.yaml
  adviser/base/openshift-templates/adviser.yaml
  adviser/base/openshift-templates/dependency-monkey.yaml
  adviser/base/openshift-templates/provenance-checker.yaml
  amun/base/deploymentconfig.yaml
  amun/base/kustomization.yaml
  amun/base/service.yaml
  build-watcher/base/kustomization.yaml
  build-watcher/overlays/test/configmap.yaml
  core/base/kustomization.yaml
  core/overlays/graph-stage/pgbouncer.yaml
  core/overlays/graph-stage/postgresql.yaml
  core/overlays/test/kustomization.yaml
  core/overlays/test/pgbouncer.yaml
  core/overlays/test/postgresql.yaml
  graph-refresh/base/buildconfig.yaml
  investigator/base/deploymentconfig.yaml
  investigator/base/kustomization.yaml
  investigator/overlays/test/service.yaml
  management-api/base/deploymentconfig.yaml
  management-api/base/kustomization.yaml
  management-api/base/service.yaml
  metrics-exporter/base/deploymentconfig.yaml
  metrics-exporter/base/kustomization.yaml
  package-extract/base/kustomization.yaml
  package-update/overlays/test/service.yaml
  security-indicators/base/kustomization.yaml
  sefkhet-abwy-chatbot/base/deploymentconfig.yaml
  sefkhet-abwy-chatbot/base/kustomization.yaml
  sefkhet-abwy/base/deploymentconfig.yaml
  sefkhet-abwy/overlays/ocp/ultrahook.yaml
  user-api/base/deploymentconfig.yaml
  user-api/base/kustomization.yaml
  user-api/base/service.yaml
  user-api/overlays/paas/kustomization.yaml
  user-api/overlays/stage/kustomization.yaml
  user-api/overlays/test/kustomization.yaml
Labels: approved, size/L

#245 Provided required env vars for advise-reporter-consumer
  advise-reporter/base/deploymentconfig.yaml
Labels: approved, size/M

#246 updated qebhwt app with new url and minor fix
  qeb-hwt-github-app/base/configmap.yaml
  qeb-hwt-github-app/base/deploymentconfig.yaml
Labels: approved, size/XS

#247 deploy amun-api tag v0.7.6 to stage cluster
  amun/overlays/stage/imagestreamtag.yaml
  amun/overlays/test/kustomization.yaml
Labels: approved, size/XS

#253 Run just one workflow at the time
  amun/overlays/amun-inspection/argo-namespace-install.yaml
Labels: approved, size/XS

#251 Ignore validation errors on Amun API in Sentry
  amun/base/deploymentconfig.yaml
Labels: approved, size/XS

#248 updated qeb-hwt github app to be managed by kustomize
  qeb-hwt-github-app/base/argo-workflows/qeb-hwt-integration.yaml
  qeb-hwt-github-app/base/configmap.yaml
  qeb-hwt-github-app/base/deploymentconfig.yaml
  qeb-hwt-github-app/base/kustomization.yaml
  qeb-hwt-github-app/base/openshift-templates/qeb-hwt.yaml
  qeb-hwt-github-app/base/service.yaml
  qeb-hwt-github-app/overlays/ocp/configmap.yaml
  qeb-hwt-github-app/overlays/ocp/imagestreamtag.yaml
  qeb-hwt-github-app/overlays/ocp/job-generate-name.yaml
  qeb-hwt-github-app/overlays/ocp/kustomization.yaml
  qeb-hwt-github-app/overlays/ocp/put-into-backend-namespace.yaml
  qeb-hwt-github-app/overlays/ocp/put-into-infra-namespace.yaml
  qeb-hwt-github-app/overlays/ocp/secret-generator.yaml
  qeb-hwt-github-app/overlays/ocp/secrets.enc.yaml
  qeb-hwt-github-app/overlays/ocp/thoth-notification.yaml
  qeb-hwt-github-app/overlays/test/job-generate-name.yaml
  qeb-hwt-github-app/overlays/test/kustomization.yaml
  qeb-hwt-github-app/overlays/test/secrets.enc.yaml
Labels: approved, size/L

#249 updated the manifest file for deployment
  sefkhet-abwy/base/deploymentconfig.yaml
  sefkhet-abwy/base/imagestream.yaml
  sefkhet-abwy/overlays/ocp/configmap.yaml
  sefkhet-abwy/overlays/ocp/imagestreamtag.yaml
  sefkhet-abwy/overlays/ocp/job-generate-name.yaml
  sefkhet-abwy/overlays/ocp/kustomization.yaml
  sefkhet-abwy/overlays/ocp/thoth-notification.yaml
  sefkhet-abwy/overlays/ocp/ultrahook.yaml
Labels: approved, size/L

#254 Bump Amun version to 0.7.7
  amun/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#252 Bump adviser version to 0.14.0 in stage env
  adviser/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#255 manifest file for stage deployementof si indicator
  security-indicators/overlays/stage/imagestreamtag.yaml
  security-indicators/overlays/stage/job-generate-name.yaml
  security-indicators/overlays/stage/kustomization.yaml
  security-indicators/overlays/stage/put-into-infra-namespace.yaml
  security-indicators/overlays/stage/thoth-notification.yaml
Labels: approved, size/L

#259 patch role and rolebinding for graph-refresh
  graph-refresh/base/role.yaml
  graph-refresh/base/rolebindings.yaml
  graph-refresh/overlays/stage/rolebindings.yaml
  graph-refresh/overlays/test/rolebindings.yaml
Labels: approved, size/L

#250 :turtle: allow chat notification based upon the environment
  advise-reporter/overlays/test/job-generate-name.yaml
  adviser/overlays/test/job-generate-name.yaml
  amun/overlays/amun-api/job-generate-name.yaml
  amun/overlays/amun-api/kustomization.yaml
  amun/overlays/amun-api/thoth-notification.yaml
  amun/overlays/amun-inspection/job-generate-name.yaml
  amun/overlays/amun-inspection/kustomization.yaml
  amun/overlays/amun-inspection/thoth-notification.yaml
  amun/overlays/test/job-generate-name.yaml
  core/overlays/backend-stage/job-generate-name.yaml
  core/overlays/backend-stage/kustomization.yaml
  core/overlays/backend-stage/thoth-notification.yaml
  core/overlays/frontend-stage/job-generate-name.yaml
  core/overlays/frontend-stage/kustomization.yaml
  core/overlays/frontend-stage/thoth-notification.yaml
  core/overlays/graph-stage/job-generate-name.yaml
  core/overlays/graph-stage/kustomization.yaml
  core/overlays/graph-stage/thoth-notification.yaml
  core/overlays/middletier-stage/job-generate-name.yaml
  core/overlays/middletier-stage/kustomization.yaml
  core/overlays/middletier-stage/thoth-notification.yaml
  core/overlays/stage/job-generate-name.yaml
  core/overlays/test/job-generate-name.yaml
  core/overlays/test/kustomization.yaml
  core/overlays/test/thoth-notification.yaml
  cve-update/overlays/test/job-generate-name.yaml
  graph-refresh/overlays/test/job-generate-name.yaml
  graph-sync/overlays/test/job-generate-name.yaml
  init-job/overlays/test/job-generate-name.yaml
  investigator/overlays/test/job-generate-name.yaml
  kebechet/overlays/prod/job-generate-name.yaml
  management-api/overlays/test/job-generate-name.yaml
  metrics-exporter/overlays/stage/job-generate-name.yaml
  metrics-exporter/overlays/stage/kustomization.yaml
  metrics-exporter/overlays/stage/thoth-notification.yaml
  metrics-exporter/overlays/test/kustomization.yaml
  metrics-exporter/overlays/test/thoth-notification.yaml
  mi-scheduler/overlays/test/job-generate-name.yaml
  package-releases/overlays/test/job-generate-name.yaml
  slo-reporter/overlays/stage/kustomization.yaml
  slo-reporter/overlays/stage/thoth-notification.yaml
  slo-reporter/overlays/test/job-generate-name.yaml
  solver/overlays/test/job-generate-name.yaml
  user-api/overlays/stage/job-generate-name.yaml
  user-api/overlays/stage/kustomization.yaml
  user-api/overlays/stage/thoth-notification.yaml
  user-api/overlays/test/kustomization.yaml
  user-api/overlays/test/thoth-notification.yaml
Labels: approved, size/L

#260 Use Argo Workflows 2.9.5 in test environment
  core/overlays/test/argo-namespace-install.yaml
Labels: approved, size/XS

#261 Use Argo 2.9.5 for Amun
  amun/overlays/amun-inspection/argo-namespace-install.yaml
Labels: approved, size/XS

#263 Make pre-commit happy again
  qeb-hwt-github-app/base/route.yaml
Labels: approved, size/XS

#266 Use Amun v0.8.0 in stage environment
  amun/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#264 Bump image version for core images
  core/overlays/stage/imagestreamtags.yaml
  core/overlays/test/imagestreamtags.yaml
  graph-refresh/overlays/stage/imagestreamtag.yaml
  graph-refresh/overlays/test/imagestreamtag.yaml
Labels: approved, size/S

#268 revsolver deployment manifest files
  revsolver/base/argo-workflows/revsolver-template.yaml
  revsolver/base/kustomization.yaml
  revsolver/base/openshift-templates/revsolve_and_sync-template.yaml
  revsolver/base/rolebinding.yaml
  revsolver/overlays/stage/imagestreamtag.yaml
  revsolver/overlays/stage/job-generate-name.yaml
  revsolver/overlays/stage/kustomization.yaml
  revsolver/overlays/stage/put-into-infra-namespace.yaml
  revsolver/overlays/stage/rolebinding.yaml
  revsolver/overlays/stage/thoth-notification.yaml
  revsolver/overlays/test/buildConfig.yaml
  revsolver/overlays/test/imagestreamtag.yaml
  revsolver/overlays/test/job-generate-name.yaml
  revsolver/overlays/test/kustomization.yaml
  revsolver/overlays/test/rolebinding.yaml
  revsolver/overlays/test/thoth-notification.yaml
Labels: approved, size/L

#272 correction in deploymentconfig environment vars
  metrics-exporter/base/deploymentconfig.yaml
  metrics-exporter/overlays/test/buildConfig.yaml
Labels: approved, size/XS

#273 Included messaging image for test and stage deployment
  core/overlays/stage/imagestreamtags.yaml
  core/overlays/test/imagestreamtags.yaml
Labels: approved, size/S

#269 Bump Amun API in stage to 0.9.0
  amun/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#262 Use Argo 2.9.5 in middletier and backend namespace
  core/overlays/backend-stage/argo-namespace-install.yaml
  core/overlays/middletier-stage/argo-namespace-install.yaml
Labels: approved, size/S

#270 Attach khemenu host with stage deployment
  management-api/overlays/stage/kustomization.yaml
  management-api/overlays/test/kustomization.yaml
  user-api/overlays/stage/khemenu.route.enc.yaml
  user-api/overlays/stage/kustomization.yaml
  user-api/overlays/stage/secret-generator.yaml
  user-api/overlays/test/kustomization.yaml
Labels: approved, size/M

#279 Bump Amun API in stage version to 0.9.1
  amun/overlays/stage/imagestreamtag.yaml
Labels: size/XS

#278 Modify time schedule for SLO reporter
  slo-reporter/base/cronjob.yaml
Labels: approved, size/XS

#282 fix version v in test workflow-controller
  core/overlays/test/argo-namespace-install.yaml
Labels: approved, size/XS

#283 Bump Amun API in stage version to 0.9.2
  amun/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#284 move the metric exporter role to individual applications
  amun/base/kustomization.yaml
  amun/base/roles/kustomization.yaml
  amun/overlays/amun-api/kustomization.yaml
  amun/overlays/amun-api/metrics-exporter-reader.yaml
  amun/overlays/amun-inspection/kustomization.yaml
  amun/overlays/amun-inspection/metrics-exporter-reader.yaml
Labels: approved, size/L

#285 use prerelease image for testing purposes
  core/overlays/test/argo-namespace-install.yaml
Labels: approved, size/XS

#286 need argoexec
  core/overlays/test/argo-namespace-install.yaml
Labels: approved, size/XS

#288 Bump graph-sync stage to v0.7.2-dev
  graph-sync/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#297 Bump revsolver to v0.2.3 in stage environment
  revsolver/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#300 Remove env variable
  slo-reporter/base/cronjob.yaml
Labels: approved, size/XS

#301 Add/remove variables
  graph-refresh/base/cronjob.yaml
Labels: approved, size/M

#303 make many optional and add ability to pass dep. name
  core/base/argo-workflows/send-message.yaml
Labels: approved, size/S

#304 pass thoth_deployment name to send_message
  solver/base/openshift-templates/solve_and_sync-template.yaml
Labels: approved, size/XS

#305 Lower requirements for kebechet-run-results
  adviser/base/argo-workflows/kebechet-run-results.yaml
Labels: approved, size/XS

#306 lower argoexec resource requirement
  core/overlays/backend-stage/configmaps.yaml
Labels: approved, size/S

#307 Prepare environment before running resubmitted Amun inspections
  amun/base/argo-workflows/inspection-build-with-cpu.yaml
  amun/base/argo-workflows/inspection-build.yaml
Labels: approved, size/M

#309 remove duplicate env variables
  security-indicators/overlays/test/buildConfig.yaml
Labels: approved, size/XS

#311 on exit send message
  amun/base/openshift-templates/inspection-with-cpu-workflow.yaml
Labels: approved, size/M

#310 Adjust endpoint for metrics-exporter deployment
  core/overlays/stage/configmaps.yaml
Labels: approved, size/XS

#312 add more descriptive topic name
  amun/base/openshift-templates/inspection-with-cpu-workflow.yaml
Labels: approved, size/XS

#318 Increase parallelism to see how resources are handled
  amun/overlays/amun-inspection/configmaps.yaml
Labels: size/XS

#319 Increase parallelism in Argo workflows even more
  amun/overlays/amun-inspection/configmaps.yaml
Labels: size/XS

#317 Install Argo with fix-3791
  core/overlays/backend-stage/argo-namespace-install.yaml
  core/overlays/middletier-stage/argo-namespace-install.yaml
Labels: size/XS

#322 Bump Kebechet in stage to v0.6.1
  kebechet/overlays/stage/imagestreamtag.yaml
Labels: size/XS

#321 Bump adviser to v0.15.0 in stage environment
  adviser/overlays/stage/imagestreamtag.yaml
Labels: do-not-merge/hold, size/XS

#320 Bump user-api in stage to v0.6.11
  user-api/overlays/stage/imagestreamtag.yaml
Labels: approved, deployment_name/ocp-stage, size/XS

#315 Prepare service account for preparing environment
  amun/base/argo-workflows/inspection-build-with-cpu.yaml
  amun/base/argo-workflows/inspection-build.yaml
  amun/base/role.yaml
  amun/base/serviceaccount.yaml
  amun/overlays/stage/role_binding.yaml
  amun/overlays/test/role_binding.yaml
Labels: approved, size/M

#323 Propagate Kebechet in version 0.6.2 to stage
  kebechet/overlays/stage/imagestreamtag.yaml
Labels: approved, deployment_name/ocp-stage, size/XS

#324 Add missing variable for SLO-reporter
  slo-reporter/base/cronjob.yaml
Labels: size/XS

#326 Bump Kebechet to v1.0.2 in stage
  kebechet/overlays/stage/imagestreamtag.yaml
Labels: size/XS

#329 Correct variable name
  slo-reporter/base/cronjob.yaml
Labels: approved, size/XS

#328 Bump package-update version to 0.8.0
  package-update/overlays/test/imagestreamtag.yaml
Labels: approved, size/XS

#327 Add pacospace and fridex to OWNERS file
  OWNERS
Labels: approved, kind/feature, size/XS

#331 Bump kebechet to v1.0.3 in stage
  kebechet/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#333 Fix pre-commit issues reported
  slo-reporter/base/cronjob.yaml
Labels: approved, size/XS

#337 Revert "Bump kebechet to v1.0.3 in stage"
  kebechet/overlays/stage/imagestreamtag.yaml
Labels: size/XS

#336 Try to setup secondsAfterCompletion to clean up workflows
  core/overlays/backend-stage/configmaps.yaml
  core/overlays/middletier-stage/configmaps.yaml
  core/overlays/test/configmaps.yaml
Labels: approved, size/XS

#338 Bump adviser version in stage to v0.15.1
  adviser/overlays/stage/imagestreamtag.yaml
Labels: approved, deployment_name/ocp-stage, size/XS

#339 Bump user-api to v0.6.14 in stage environment
  user-api/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#340 Bump management-api to v0.6.4 in stage
  management-api/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#341 Bump Kebechet to version 1.0.4 in stage
  kebechet/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#344 Bump User API to v0.6.15 in stage
  user-api/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS
