Repository thoth-station/thoth-application, pull requests merged in 2020-12, with the labels that each got.

#686 Bump workflow-helpers version in stage to v0.3.1
  core/overlays/ocp4-stage/common/imagestreamtags.yaml
  core/overlays/stage/common/imagestreamtags.yaml
Labels: approved, size/XS

#687 Add graph-schema-update
  graph-schema-update/base/imagestream.yaml
  graph-schema-update/base/kustomization.yaml
  graph-schema-update/base/openshift-templates/schemaUpdateJob-template.yaml
  graph-schema-update/overlays/ocp4-stage/job-generate-name.yaml
  graph-schema-update/overlays/ocp4-stage/kustomization.yaml
  graph-schema-update/overlays/ocp4-stage/put-into-infra-namespace.yaml
  graph-schema-update/overlays/ocp4-stage/thoth-notification.yaml
  graph-schema-update/overlays/prod/job-generate-name.yaml
  graph-schema-update/overlays/prod/kustomization.yaml
  graph-schema-update/overlays/prod/put-into-infra-namespace.yaml
  graph-schema-update/overlays/prod/thoth-notification.yaml
  graph-schema-update/overlays/stage/job-generate-name.yaml
  graph-schema-update/overlays/stage/kustomization.yaml
  graph-schema-update/overlays/stage/put-into-infra-namespace.yaml
  graph-schema-update/overlays/stage/thoth-notification.yaml
  graph-schema-update/overlays/test/job-generate-name.yaml
  graph-schema-update/overlays/test/kustomization.yaml
  graph-schema-update/overlays/test/thoth-notification.yaml
Labels: approved, size/L

#688 Bump graph-sync to v0.8.0
  graph-sync/overlays/ocp4-stage/imagestreamtag.yaml
  graph-sync/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#691 Add more memory to adviser
  adviser/base/argo-workflows/advise.yaml
Labels: approved, size/XS

#693 Add more memory to adviser
  adviser/base/argo-workflows/advise.yaml
Labels: approved, size/XS

#689 Package module dont require build-check
  prow/overlays/thoth-station/config.yaml
Labels: approved, size/XS

#696 Disable all SI analysis
  graph-refresh/base/cronjob.yaml
  investigator/base/deploymentconfig.yaml
Labels: approved, size/XS

#697 bump graph-sync in stage to v0.8.1
  graph-sync/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#699 Kebechet bump in test
  kebechet/overlays/test/imagestreamtag.yaml
Labels: approved, sig/build, sig/cyborgs, size/XS

#698 Bump kebechet to v1.2.1 in ocp4
  kebechet/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#700 Revert "Bump kebechet to v1.2.1 in ocp4"
  kebechet/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, sig/devops, size/XS

#702 pause the data generation component for maintenance
  graph-refresh/overlays/ocp4-stage/cronjob.yaml
  package-releases/overlays/ocp4-stage/cronjob.yaml
  package-update/overlays/ocp4-stage/cronjob.yaml
Labels: approved, size/XS

#703 play the data generation components the maintenance is done
  graph-refresh/overlays/ocp4-stage/cronjob.yaml
  package-releases/overlays/ocp4-stage/cronjob.yaml
  package-update/overlays/ocp4-stage/cronjob.yaml
Labels: approved, size/XS

#705 fix the referencing to the correct image for kebechet workflow
  adviser/base/argo-workflows/kebechet-run-results.yaml
Labels: approved, size/XS

#704 Bumped kebechet in test
  kebechet/overlays/test/imagestreamtag.yaml
Labels: approved, size/XS

#707 Bumped in stage
  kebechet/overlays/ocp4-stage/imagestreamtag.yaml
  kebechet/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#706 increase the workflow parallelism for middletier
  core/overlays/ocp4-stage/middletier-stage/configmaps.yaml
Labels: approved, size/XS

#710 patch the correct url in qebhwt workflow configmap
  core/overlays/ocp4-stage/common/configmaps.yaml
Labels: approved, size/XS

#711 bump-graph-sync-to-0.8.4
  graph-sync/overlays/ocp4-stage/imagestreamtag.yaml
  graph-sync/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#713 patch the use of wrong secret in adviser workflow
  adviser/base/openshift-templates/adviser.yaml
Labels: approved, size/XS

#714 disable enlisting of encrypted secret and routes for cnv deployment
  amun/overlays/cnv-prod/amun-api/kustomization.yaml
  chat-notification/overlays/cnv-prod/kustomization.yaml
  core/overlays/cnv-prod/common/kustomization.yaml
  management-api/overlays/cnv-prod/kustomization.yaml
  user-api/overlays/cnv-prod/kustomization.yaml
Labels: approved, size/S

#715 Enable ocp stage to solve fedora solvers
  core/overlays/stage/common/configmaps.yaml
  graph-refresh/overlays/stage/cronjob.yaml
Labels: approved, size/XS

#716 updated certs for routes of thoth-station
  amun/overlays/cnv-prod/amun-api/route.enc.yaml
  amun/overlays/ocp4-stage/amun-api/route.enc.yaml
  amun/overlays/prod/amun-api/route.enc.yaml
  amun/overlays/stage/amun-api/route.enc.yaml
  amun/overlays/test/route.enc.yaml
  management-api/overlays/cnv-prod/route.enc.yaml
  management-api/overlays/ocp4-stage/route.enc.yaml
  management-api/overlays/prod/route.enc.yaml
  management-api/overlays/stage/route.enc.yaml
  management-api/overlays/test/route.enc.yaml
  user-api/overlays/cnv-prod/khemenu.route.enc.yaml
  user-api/overlays/cnv-prod/route.enc.yaml
  user-api/overlays/ocp4-stage/khemenu.route.enc.yaml
  user-api/overlays/ocp4-stage/route.enc.yaml
  user-api/overlays/prod/route.enc.yaml
  user-api/overlays/stage/khemenu.route.enc.yaml
  user-api/overlays/stage/route.enc.yaml
  user-api/overlays/test/route.enc.yaml
Labels: approved, sig/devops, size/XXL

#692 Add kebechet workflow, remove old processing step
  mi-scheduler/base/argo-workflows/mi-workflow-template.yaml
  mi-scheduler/base/openshift-templates/mi-run-template.yaml
Labels: approved, size/M

#717 Increase workflows scheduled
  graph-refresh/base/cronjob.yaml
Labels: approved, size/XS

#719 Increase workflows
  graph-refresh/base/cronjob.yaml
  mi-scheduler/base/argo-workflows/mi-workflow-template.yaml
Labels: approved, size/XS
