Repository thoth-station/thoth-application, pull requests merged in 2020-11, with the labels that each got.

#604 Set logging to WARNING for sentry_sdk.errors logger
  adviser/base/argo-workflows/advise.yaml
Labels: approved, size/XS

#606 Add additional wait before the resolver is terminated
  adviser/base/argo-workflows/advise.yaml
Labels: approved, size/XS

#607 Bump adviser to v0.20.0 in stage
  adviser/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#608 bump up nepthys version
  nepthys/overlays/ocp/imagestreamtag.yaml
Labels: approved, size/XS

#611 Amun API URL should include version
  core/overlays/ocp4-stage/common/configmaps.yaml
  core/overlays/prod/common/configmaps.yaml
  core/overlays/stage/common/configmaps.yaml
  core/overlays/test/configmaps.yaml
Labels: approved, size/XS

#612 bump up investigator and messaging versions
  core/overlays/stage/common/imagestreamtags.yaml
Labels: approved, size/XS

#613 update the investigator deploymentconfig wrt to new chnages
  investigator/base/deploymentconfig.yaml
Labels: approved, size/S

#615 revert back to old faust based investigator
  core/overlays/stage/common/imagestreamtags.yaml
  investigator/base/deploymentconfig.yaml
Labels: approved, size/S

#616 Bump management-api to v0.8.0 in stage
  management-api/overlays/stage/imagestreamtag.yaml
Labels: size/XS

#617 Bump management-api to v0.8.1 in stage
  management-api/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#619 Bump adviser to version 0.20.1 in stage
  adviser/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#621 Bump user-api to v0.7.0 in stage environment
  user-api/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#622 Revert "Bump user-api to v0.7.0 in stage environment"
  user-api/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#623 Downgrade user-api to v0.6.20 in stage environment
  user-api/overlays/test/imagestreamtag.yaml
Labels: approved, size/XS

#620 move tested cve-update kafka producer to base
  cve-update/base/cronjob.yaml
  cve-update/overlays/test/cronjob.yaml
  cve-update/overlays/test/kustomization.yaml
Labels: approved, size/L

#624 Use here-strings instead of here documents
  amun/base/argo-workflows/inspection-build-with-cpu.yaml
  amun/base/argo-workflows/inspection-build.yaml
Labels: approved, size/S

#625 Fix expansion of env variables
  amun/base/argo-workflows/inspection-build-with-cpu.yaml
  amun/base/argo-workflows/inspection-build.yaml
Labels: approved, size/XS

#626 Another try to fix expansion
  amun/base/argo-workflows/inspection-build-with-cpu.yaml
  amun/base/argo-workflows/inspection-build.yaml
Labels: approved, size/S

#627 Avoid expansion of envariables in here-documents
  amun/base/argo-workflows/inspection-build-with-cpu.yaml
  amun/base/argo-workflows/inspection-build.yaml
Labels: approved, size/XS

#480 add new workflow for graph-sync
  graph-sync/base/argo-workflows/sync-template.yaml
  graph-sync/base/openshift-templates/graph-sync.yaml
Labels: approved, size/L

#628 updated argo artifact secrets for amun instance
  amun/overlays/ocp4-stage/amun-api/secrets.enc.yaml
  amun/overlays/stage/amun-api/secrets.enc.yaml
Labels: approved, size/L

#630 update parallelism for middletier stage
  core/overlays/ocp4-stage/middletier-stage/configmaps.yaml
  core/overlays/stage/middletier-stage/configmaps.yaml
Labels: approved, size/XS

#631 Bump User API to v0.8.0 in stage
  user-api/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#633 update investigator stage to v0.5.6 to run with messaging v0.7.13
  core/overlays/stage/common/imagestreamtags.yaml
  core/overlays/test/imagestreamtags.yaml
Labels: approved, size/XS

#634 bump up graph-refresh job to v0.2.9
  graph-refresh/overlays/ocp4-stage/imagestreamtag.yaml
  graph-refresh/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#635 bump up package-update job to v0.8.4
  package-update/overlays/ocp4-stage/imagestreamtag.yaml
  package-update/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#638 add pre-commit & pytest for invectio
  prow/overlays/thoth-station/config.yaml
Labels: approved, size/XS

#640 Added Env variables needed for Githubapp
  kebechet/base/argo-workflows/kebechet-run-url.yaml
  kebechet/base/argo-workflows/kebechet.yaml
  kebechet/base/openshift-templates/kebechet-run-url.yaml
  kebechet/base/openshift-templates/kebechet.yaml
Labels: approved, size/M

#639 update kebechet secret with github app requirements
  kebechet/overlays/stage/secrets.enc.yaml
  kebechet/overlays/test/secrets.enc.yaml
Labels: size/L

#642 Bump Kebechet in test
  kebechet/overlays/test/imagestreamtag.yaml
Labels: approved, size/XS

#643 Keb GitHub
  kebechet/base/openshift-templates/kebechet-run-url.yaml
Labels: approved, size/XS

#644 Reduce beam width to reduce OOM risk
  adviser/base/argo-workflows/advise.yaml
Labels: approved, size/XS

#645 Beam reduce
  adviser/base/openshift-templates/adviser.yaml
Labels: approved, size/XS

#646 Decrease liveness to 20 mins for adviser
  adviser/base/argo-workflows/advise.yaml
Labels: approved, size/XS

#647 Give resolver more memory to compute results
  adviser/base/argo-workflows/advise.yaml
Labels: approved, size/XS

#648 Decrease beam width to 10000
  adviser/base/argo-workflows/advise.yaml
  adviser/base/openshift-templates/adviser.yaml
Labels: approved, size/XS

#649 Give adviser more memory and restore old configuration
  adviser/base/argo-workflows/advise.yaml
  adviser/base/openshift-templates/adviser.yaml
Labels: size/XS

#651 Bump adviser to 16Gi
  adviser/base/argo-workflows/advise.yaml
Labels: size/XS

#652 Raise adviser requests to 20Gi memory
  adviser/base/argo-workflows/advise.yaml
Labels: approved, size/XS

#653 set other solvers to be solved
  core/overlays/stage/common/configmaps.yaml
Labels: approved, size/XS

#655 stick to solvers based on f32 and ubi8
  solver/base/imagestreams.yaml
  solver/overlays/ocp4-stage/imagestreamtag.yaml
  solver/overlays/prod/imagestreamtag.yaml
  solver/overlays/stage/imagestreamtag.yaml
  solver/overlays/test/imagestreamtag.yaml
Labels: approved, size/L

#657 Add missing THOTH_ADVISER_DEV option
  adviser/base/openshift-templates/adviser.yaml
Labels: approved, size/XS

#665 Bump adviser to v0.21.0 in stage
  adviser/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#664 Bump keb
  kebechet/overlays/test/imagestreamtag.yaml
Labels: approved, size/XS

#666 set package dir for si cloc
  security-indicators/base/argo-workflows/cloc-template.yaml
Labels: approved, size/XS

#667 Bump kebechet in stage
  kebechet/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#668 Bumped kebechet
  kebechet/overlays/stage/imagestreamtag.yaml
  kebechet/overlays/test/imagestreamtag.yaml
Labels: approved, size/XS

#671 Reduce time after which adviser is cut off
  adviser/base/argo-workflows/advise.yaml
Labels: approved, size/XS

#672 Test pr 610
  kebechet/overlays/test/imagestreamtag.yaml
Labels: approved, size/XS

#673 update stage investigator to the latest version
  core/overlays/stage/common/imagestreamtags.yaml
  investigator/base/deploymentconfig.yaml
Labels: approved, size/S

#674 Revert "update stage investigator to the latest version"
  core/overlays/stage/common/imagestreamtags.yaml
  investigator/base/deploymentconfig.yaml
Labels: approved, size/S

#676 Updated kebechet image
  kebechet/overlays/stage/imagestreamtag.yaml
  kebechet/overlays/test/imagestreamtag.yaml
Labels: approved, size/XS

#677 Include fix-test image to check on the qebhwt issue
  qeb-hwt-github-app/overlays/test/imagestreamtag.yaml
Labels: approved, size/XS

#678 Bump adviser to version 0.21.1 in stage environment
  adviser/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#670 Reduce workflows to avoid Kafka limit for messages (Data Driven Engineering)
  graph-refresh/base/cronjob.yaml
Labels: approved, size/XS

#683 Reduce adviser memory to 2Gi
  adviser/base/argo-workflows/advise.yaml
Labels: approved, size/XS

#680 Bump SLO-reporter version to 0.7.0
  slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml
  slo-reporter/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#684 bump up management-api app version to v0.8.2
  management-api/overlays/ocp4-stage/imagestreamtag.yaml
  management-api/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#685 switch to ocp4 qebhwt webhook receiver from ocp
  qeb-hwt-github-app/overlays/stage/kustomization.yaml
Labels: approved, size/XS
