Repository thoth-station/thoth-application, pull requests merged in 2021-08, with the labels that each got.

#1866 Bump prescriptions to v0.5.1 in stage environment
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1867 Bump up the version of thoth station for v2021.08.02 release
  advise-reporter/overlays/cnv-prod/imagestreamtag.yaml
  advise-reporter/overlays/ocp4-stage/imagestreamtag.yaml
  adviser/overlays/cnv-prod/imagestreamtag.yaml
  adviser/overlays/test/imagestreamtag.yaml
  core/overlays/cnv-prod/common/imagestreamtags.yaml
  core/overlays/ocp4-stage/common/imagestreamtags.yaml
  core/overlays/test/imagestreamtags.yaml
  core/overlays/zero-test/imagestreamtags.yaml
  cve-update/overlays/cnv-prod/imagestreamtag.yaml
  cve-update/overlays/ocp4-stage/imagestreamtag.yaml
  graph-backup-job/overlays/cnv-prod/imagestreamtag.yaml
  graph-backup-job/overlays/ocp4-stage/imagestreamtag.yaml
  graph-backup-job/overlays/test/imagestreamtag.yaml
  graph-metrics-exporter/overlays/cnv-prod/imagestreamtag.yaml
  graph-metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
  graph-refresh/overlays/cnv-prod/imagestreamtag.yaml
  graph-refresh/overlays/ocp4-stage/imagestreamtag.yaml
  graph-sync/overlays/cnv-prod/imagestreamtag.yaml
  graph-sync/overlays/ocp4-stage/imagestreamtag.yaml
  kebechet/overlays/cnv-prod/imagestreamtag.yaml
  kebechet/overlays/ocp4-stage/imagestreamtag.yaml
  metrics-exporter/overlays/cnv-prod/imagestreamtag.yaml
  metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
  metrics-exporter/overlays/test/imagestreamtag.yaml
  package-releases/overlays/cnv-prod/imagestreamtag.yaml
  package-releases/overlays/ocp4-stage/imagestreamtag.yaml
  package-update/overlays/cnv-prod/imagestreamtag.yaml
  package-update/overlays/ocp4-stage/imagestreamtag.yaml
  revsolver/overlays/cnv-prod/imagestreamtag.yaml
  revsolver/overlays/ocp4-stage/imagestreamtag.yaml
  slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml
  slo-reporter/overlays/zero-prod-ocp4-stage/imagestreamtag.yaml
  solver/overlays/cnv-prod/imagestreamtag.yaml
  solver/overlays/ocp4-stage/imagestreamtag.yaml
  user-api/overlays/cnv-prod/imagestreamtag.yaml
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/M

#1868 update certs for the thoth routes
  amun/overlays/cnv-prod/amun-api/route.enc.yaml
  amun/overlays/ocp4-stage/amun-api/route.enc.yaml
  amun/overlays/test/route.enc.yaml
  management-api/overlays/cnv-prod/route.enc.yaml
  management-api/overlays/ocp4-stage/route.enc.yaml
  management-api/overlays/test/route.enc.yaml
  user-api/overlays/cnv-prod/route.enc.yaml
  user-api/overlays/ocp4-stage/route.enc.yaml
  user-api/overlays/test/route.enc.yaml
Labels: approved

#1870 patch back the stable version 1.2.4
  kebechet/overlays/cnv-prod/imagestreamtag.yaml
Labels: approved, size/XS

#1876 Increase liveness probe seconds on graph-refresh job
  graph-refresh/base/cronjob.yaml
Labels: approved, size/XS

#1877 Bump management-api to v0.17.9 in stage
  management-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1878 setup pulp tls route for serving
  pulp-opf/overlays/zero-prod/kustomization.yaml
  pulp-opf/overlays/zero-prod/routes.yaml
Labels: size/M, approved

#1879 Bump up the images based on the version update v2021.08.16
  kebechet/overlays/cnv-prod/imagestreamtag.yaml
  management-api/overlays/cnv-prod/imagestreamtag.yaml
  mi-scheduler/overlays/cnv-prod/imagestreamtag.yaml
  mi-scheduler/overlays/ocp4-stage/imagestreamtag.yaml
  mi-scheduler/overlays/test/imagestreamtag.yaml
Labels: size/S

#1875 updating to use ACME operator
  triage-party/overlays/zero-prod/kustomization.yaml
  triage-party/overlays/zero-prod/route.enc.yaml
  triage-party/overlays/zero-prod/route.yaml
  triage-party/overlays/zero-prod/secret-generator.yaml
Labels: approved, size/L

#1888 bump investigator to v0.14.3 to fix bug
  core/overlays/cnv-prod/common/imagestreamtags.yaml
  core/overlays/ocp4-stage/common/imagestreamtags.yaml
Labels: approved, size/XS

#1889 Bump graph-sync to v0.10.13 in stage environment
  graph-sync/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, priority/critical-urgent, size/XS

#1890 Bump graph-refresh to v0.3.13 in stage
  graph-refresh/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS, do-not-merge/hold, ok-to-test

#1891 Increase package-releases deadline to 4 hours
  package-releases/base/cronjob.yaml
Labels: approved, size/XS

#1896 Bump kebechet to fix issue
  kebechet/overlays/cnv-prod/imagestreamtag.yaml
  kebechet/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1883 Bump adviser to v0.39.0 in stage environment
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1884 Bump prescriptions to v0.6.0 in stage environment
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1894 Branch workflow with more resources if solver fails
  solver/base/argo-workflows/solver-template.yaml
  solver/base/openshift-templates/solve_and_sync-template.yaml
Labels: approved, size/L

#1899 Bump workflow-helpers to v0.8.8 to allow graph update and fix kebechet administrator
  core/overlays/cnv-prod/common/imagestreamtags.yaml
  core/overlays/ocp4-stage/common/imagestreamtags.yaml
Labels: approved, size/XS

#1898 Set deadline for solver containers
  solver/base/argo-workflows/solver-template.yaml
Labels: approved, size/XS

#1901 bump slo-reporter to v0.16.2 to fix enum issues
  slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml
  slo-reporter/overlays/zero-prod-ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1905 Add more memory for high resources solver branch
  solver/base/argo-workflows/solver-template.yaml
Labels: approved, size/XS

#1900 feat: Add exclude branches for branchprotect on Meteor repo
  prow/overlays/cnv-prod/config.yaml
Labels: approved, size/S

#1902 Bump adviser to v0.40.0 in stage environment
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1903 Bump prescriptions to v0.7.0 in stage environment
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1906 Bump slo-reporter to v0.17.0
  slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml
  slo-reporter/overlays/zero-prod-ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1909 increate memory for database in prod
  core/overlays/cnv-prod/graph-prod/postgresql.yaml
Labels: approved, size/XS, lgtm

#1825 Remove only-if-package-seen configuration option
  core/overlays/cnv-prod/common/configmaps.yaml
  core/overlays/ocp4-stage/common/configmaps.yaml
  core/overlays/quicklab/configmaps.yaml
  core/overlays/test/configmaps.yaml
  core/overlays/zero-test/configmaps.yaml
  package-releases/base/cronjob.yaml
  package-releases/overlays/cnv-prod/cronjob.yaml
Labels: approved, size/S

#1911 fix kebechet administrator workflow in prod
  core/overlays/cnv-prod/common/imagestreamtags.yaml
  core/overlays/ocp4-stage/common/imagestreamtags.yaml
Labels: approved, size/XS

#1910 Do not schedule kebechet admin in stage
  investigator/overlays/ocp4-stage/deploymentconfig.yaml
Labels: approved, size/L

#1913 Fix investigator triggering adviser v5
  core/overlays/cnv-prod/common/imagestreamtags.yaml
  core/overlays/ocp4-stage/common/imagestreamtags.yaml
  investigator/overlays/test/deploymentconfig.yaml
Labels: approved, size/XS

#1916 Enable patch for investigator stage
  investigator/overlays/ocp4-stage/kustomization.yaml
Labels: approved, size/XS

#1912 Update dashboards in prod
  grafana-dashboard/overlays/cnv-prod/thoth-kafka-argo-metrics.json
  grafana-dashboard/overlays/cnv-prod/thoth-knowledge-graph-content-metrics.json
  grafana-dashboard/overlays/cnv-prod/thoth-sli-slo.json
Labels: approved, size/XXL

#1897 bump graph-backup to v0.8.7 to fix issue
  graph-backup-job/overlays/cnv-prod/imagestreamtag.yaml
  graph-backup-job/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1917 Bump package-releases-job to v0.11.0 in stage environment
  package-releases/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1919 Reduce TTL for kebechet administrator
  kebechet/base/openshift-templates/kebechet-administrator.yaml
Labels: approved, size/XS

#1922 Bump adviser to v0.41.0 in stage environment
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS, do-not-merge/hold

#1933 Bump up the images based on the version update v2021.08.30
  adviser/overlays/cnv-prod/imagestreamtag.yaml
  core/overlays/zero-test/imagestreamtags.yaml
  graph-refresh/overlays/cnv-prod/imagestreamtag.yaml
  graph-sync/overlays/cnv-prod/imagestreamtag.yaml
  package-releases/overlays/cnv-prod/imagestreamtag.yaml
Labels: size/S
