Repository thoth-station/thoth-application, pull requests merged in 2021-01, with the labels that each got.

#720 Increase the amount of workflow to run in parallel for ocp middletier
  core/overlays/stage/middletier-stage/configmaps.yaml
Labels: approved, size/XS

#723 enable package release in ocp cluster
  package-releases/overlays/stage/cronjob.yaml
Labels: approved, size/XS

#721 use imagestream instead of direct pull from quay
  core/overlays/ocp4-stage/graph-stage/postgresql-metrics-exporter.yaml
Labels: approved, size/S

#722 updated secrets for cnv prod kafka apps
  core/overlays/cnv-prod/common/secrets.enc.yaml
Labels: approved, size/L

#727 utilize max storage size for database
  core/overlays/test/postgresql.yaml
Labels: approved, size/XS

#728 Bump metrics-exporter to v0.9.0 in stage
  metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
  metrics-exporter/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#729 Bump workflows helpers to v0.3.2
  core/overlays/ocp4-stage/common/imagestreamtags.yaml
  core/overlays/stage/common/imagestreamtags.yaml
Labels: approved, size/XS

#730 Bump Kebechet to 1.2.3
  kebechet/overlays/cnv-prod/imagestreamtag.yaml
  kebechet/overlays/ocp4-stage/imagestreamtag.yaml
  kebechet/overlays/stage/imagestreamtag.yaml
  kebechet/overlays/test/imagestreamtag.yaml
Labels: approved, size/S

#731 Bump workflow-helper to v0.3.3
  core/overlays/ocp4-stage/common/imagestreamtags.yaml
  core/overlays/stage/common/imagestreamtags.yaml
Labels: approved, size/XS

#732 bump up the version of management-api for stage systems
  management-api/overlays/ocp4-stage/imagestreamtag.yaml
  management-api/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#733 namespace specific roles are used in cnv cluster
  amun/overlays/cnv-prod/amun-api/role_binding.yaml
  graph-refresh/overlays/cnv-prod/rolebindings.yaml
  investigator/overlays/cnv-prod/role_binding.yaml
  management-api/overlays/cnv-prod/role-binding.yaml
  revsolver/overlays/cnv-prod/rolebinding.yaml
  user-api/overlays/cnv-prod/role-binding.yaml
Labels: approved, sig/devops, size/M

#734 bump up the latest version of management-api for stage systems
  management-api/overlays/ocp4-stage/imagestreamtag.yaml
  management-api/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#737 increase pvc size for the production database
  core/overlays/cnv-prod/graph-prod/postgresql.yaml
Labels: approved, sig/devops, size/XS

#739 Bump management-api to v0.9.0
  management-api/overlays/test/imagestreamtag.yaml
Labels: approved, size/XS

#742 bump adviser-reporter to v0.5.0
  advise-reporter/overlays/ocp4-stage/imagestreamtag.yaml
  advise-reporter/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#746 Bump user-api to v0.10.0 in test environment
  user-api/overlays/test/imagestreamtag.yaml
Labels: approved, size/XS

#749 Bump metrics-exporter in stage to v0.9.1
  metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
  metrics-exporter/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#750 deployment uses new env for config
  user-api/overlays/test/deploymentconfig.yaml
  user-api/overlays/test/kustomization.yaml
Labels: approved, size/L

#751 updated management-api role to allow creating jobs
  management-api/base/role.yaml
Labels: approved, size/S

#752 store the grafana dashboard json for maintainability
  grafana-dashboard/README.md
  grafana-dashboard/base/kustomization.yaml
  grafana-dashboard/overlays/cnv-prod/argocd.json
  grafana-dashboard/overlays/cnv-prod/thoth-kafka-argo-metrics.json
  grafana-dashboard/overlays/cnv-prod/thoth-knowledge-graph-content-metrics.json
  grafana-dashboard/overlays/cnv-prod/thoth-postgresql-metrics.json
  grafana-dashboard/overlays/cnv-prod/thoth-sli-slo.json
  grafana-dashboard/overlays/cnv-prod/thoth-user-api-metrics.json
  grafana-dashboard/overlays/cnv-prod/thoth-workflow-controllers-metrics.json
Labels: approved, kind/feature, sig/devops, size/XXL

#748 use ocp4-test deployment for test and turn on graph backup
  core/overlays/test/configmaps.yaml
  graph-backup-job/overlays/test/cronjob.yaml
  graph-backup-job/overlays/test/kustomization.yaml
  kebechet/overlays/test/configmap.yaml
  qeb-hwt-github-app/overlays/test/configmap.yaml
Labels: approved, kind/feature, sig/devops, size/M

#736 add a CronJob to normalize the labels of github organizations
  sefkhet-abwy/base/imagestream.yaml
  sefkhet-abwy/overlays/cnv-prod/ghproxy.yaml
  sefkhet-abwy/overlays/cnv-prod/imagestreamtag.yaml
  sefkhet-abwy/overlays/cnv-prod/job-generate-name.yaml
  sefkhet-abwy/overlays/cnv-prod/kustomization.yaml
  sefkhet-abwy/overlays/cnv-prod/new-label-normalizer.yaml
  sefkhet-abwy/overlays/cnv-prod/secret-generator.yaml
  sefkhet-abwy/overlays/cnv-prod/secrets.enc.yaml
  sefkhet-abwy/overlays/cnv-prod/thoth-notification.yaml
Labels: approved, size/L

#754 bump up the latest version of management-api
  management-api/overlays/ocp4-stage/imagestreamtag.yaml
  management-api/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#755 fix of argocli with respect to the deployment
  amun/overlays/cnv-prod/amun-inspection/argo-namespace-install.yaml
  amun/overlays/ocp4-stage/amun-inspection/argo-namespace-install.yaml
  amun/overlays/stage/amun-inspection/argo-namespace-install.yaml
Labels: approved, size/XS

#756 debug the out-of-sync issue with argocli image
  amun/overlays/stage/amun-inspection/argo-namespace-install.yaml
Labels: approved, size/XS

#757 debug the out-of-sync issue with argocli image
  amun/overlays/stage/amun-inspection/argo-namespace-install.yaml
Labels: approved, size/XS

#758 update to latest messaging
  advise-reporter/overlays/test/cronjob.yaml
  core/overlays/test/argo-workflows/send-message.yaml
  core/overlays/test/argo-workflows/send-messages.yaml
  core/overlays/test/kustomization.yaml
  package-releases/overlays/test/cronjob.yaml
  package-update/overlays/test/cronjob.yaml
Labels: approved, size/L

#761 Bump adviser to v0.22.0
  adviser/overlays/cnv-prod/imagestreamtag.yaml
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
  adviser/overlays/prod/imagestreamtag.yaml
  adviser/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#763 set the rolebinding for user-api to get pod logs
  user-api/overlays/test/role-binding.yaml
Labels: approved, size/S

#765 Bump advise reporter stage to v0.5.1
  advise-reporter/overlays/ocp4-stage/imagestreamtag.yaml
  advise-reporter/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#766 update env in cron template
  graph-refresh/overlays/test/cronjob.yaml
Labels: approved, size/L

#764 updated certs for the prod management-api
  management-api/overlays/cnv-prod/route.enc.yaml
Labels: approved, size/M

#767 Add environments needed for recent user-api with Kafka messaging
  user-api/base/deploymentconfig.yaml
  user-api/overlays/test/deploymentconfig.yaml
  user-api/overlays/test/kustomization.yaml
Labels: approved, size/L

#760 Bump user-api to v0.11.1 in stage environments
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
  user-api/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#768 Bump graph-sync to v0.9.0 in stage
  graph-sync/overlays/ocp4-stage/imagestreamtag.yaml
  graph-sync/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#770 Adjust all envs
  graph-sync/base/argo-workflows/sync-template.yaml
Labels: approved, size/XS

#771 Bump management api stage to v0.10.0
  management-api/overlays/ocp4-stage/imagestreamtag.yaml
  management-api/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#753 support the deployment of kafka for thoth
  kafka/base/kustomization.yaml
  kafka/base/route.yaml
  kafka/base/service.yaml
  kafka/base/thoth-kafka.yaml
  kafka/overlays/README.md
  kafka/overlays/ocp-stage/deployment.yaml
  kafka/overlays/ocp-stage/kustomization.yaml
  kafka/overlays/ocp4-stage/deployment.yaml
  kafka/overlays/ocp4-stage/kustomization.yaml
Labels: approved, sig/devops, size/L

#776 Bump slo-reporter stage to v0.8.1
  slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml
  slo-reporter/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#744 Bump investigator to v0.8.2 in stage environments
  core/overlays/ocp4-stage/common/imagestreamtags.yaml
  core/overlays/stage/common/imagestreamtags.yaml
Labels: approved, size/XS

#778 Bump package release to v0.9.0
  package-releases/overlays/ocp4-stage/imagestreamtag.yaml
  package-releases/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#780 fix the kustomize manifest for properly propogating cronjob
  graph-backup-job/overlays/test/kustomization.yaml
Labels: approved, size/XS

#781 Propagate new environment variables to build-watcher deployment
  build-watcher/base/configmap.yaml
  build-watcher/base/deploymentconfig.yaml
Labels: approved, size/M

#785 build-watcher deployment manifests for amun inspections
  build-watcher/base/deploymentconfig.yaml
  build-watcher/base/kustomization.yaml
  build-watcher/base/role.yaml
  build-watcher/overlays/amun-api/configmap.yaml
  build-watcher/overlays/amun-api/kustomization.yaml
  build-watcher/overlays/amun-api/put-into-inspection-namespace.yaml
  build-watcher/overlays/amun-api/role-binding.yaml
  build-watcher/overlays/amun-api/secret-generator.yaml
  build-watcher/overlays/amun-api/secrets.enc.yaml
Labels: approved, size/L

#787 updated sops encryption pattern and prow routes
  .sops.yaml
  prow/overlays/cnv-prod/routes.enc.yaml
Labels: approved, size/L

#735 Add build analysis workflow
  build-analysis/base/openshift-templates/build-analysis.yaml
  buildlog-parser/base/argo-workflows/buildlog-parser.yaml
  buildlog-parser/base/imagestream.yaml
  buildlog-parser/base/openshift-templates/buildlogParser-template.yaml
  buildlog-parser/overlays/cnv-prod/imagestreamtag.yaml
  buildlog-parser/overlays/cnv-prod/kustomization.yaml
  buildlog-parser/overlays/cnv-prod/thoth-notification.yaml
  buildlog-parser/overlays/ocp4-stage/imagestreamtag.yaml
  buildlog-parser/overlays/ocp4-stage/kustomization.yaml
  buildlog-parser/overlays/ocp4-stage/thoth-notification.yaml
  buildlog-parser/overlays/test/imagestreamtag.yaml
  buildlog-parser/overlays/test/kustomization.yaml
  buildlog-parser/overlays/test/thoth-notification.yaml
Labels: approved, size/XL

#788 fix the argument certificate in the route tls
  prow/overlays/cnv-prod/routes.enc.yaml
Labels: approved, size/L

#790 use the direct service hostname for s3 connection
  core/overlays/cnv-prod/common/configmaps.yaml
Labels: approved, size/XS

#791 upgrade of prod with stage versions
  advise-reporter/overlays/cnv-prod/imagestreamtag.yaml
  amun/overlays/cnv-prod/amun-api/configmaps.yaml
  core/overlays/cnv-prod/backend-prod/configmaps.yaml
  core/overlays/cnv-prod/common/imagestreamtags.yaml
  core/overlays/cnv-prod/middletier-prod/configmaps.yaml
  management-api/overlays/cnv-prod/imagestreamtag.yaml
  metrics-exporter/overlays/cnv-prod/imagestreamtag.yaml
  package-releases/overlays/cnv-prod/imagestreamtag.yaml
  slo-reporter/overlays/cnv-prod/imagestreamtag.yaml
Labels: approved, size/S

#783 Bump investigator stage to v0.9.0
  core/overlays/ocp4-stage/common/imagestreamtags.yaml
  core/overlays/stage/common/imagestreamtags.yaml
Labels: approved, sig/devops, sig/documentation, size/XS

#793 upgrade the investigator deploymentconfig
  investigator/base/deploymentconfig.yaml
Labels: approved, size/S

#794 Bump components versions to stage
  core/overlays/ocp4-stage/common/imagestreamtags.yaml
  core/overlays/stage/common/imagestreamtags.yaml
  management-api/overlays/ocp4-stage/imagestreamtag.yaml
  management-api/overlays/stage/imagestreamtag.yaml
  metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
  metrics-exporter/overlays/stage/imagestreamtag.yaml
Labels: approved, size/S

#782 Bump graph refresh v0.3.1
  graph-refresh/base/cronjob.yaml
  graph-refresh/overlays/ocp4-stage/imagestreamtag.yaml
  graph-refresh/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#798 suspend all data ingestion producers
  graph-refresh/overlays/ocp4-stage/cronjob.yaml
  package-releases/overlays/ocp4-stage/cronjob.yaml
  package-update/overlays/ocp4-stage/cronjob.yaml
Labels: approved, sig/devops, size/XS

#799 upgrade argo components to v2.12.5 to tackle ttl issues
  core/overlays/ocp4-stage/backend-stage/argo-namespace-install.yaml
  core/overlays/ocp4-stage/middletier-stage/argo-namespace-install.yaml
  core/overlays/test/argo-namespace-install.yaml
Labels: approved, sig/devops

#801 re-encrypt sefkhet secrets with updates sops
  sefkhet-abwy/overlays/cnv-prod/secrets.enc.yaml
Labels: approved, size/L

#802 re-encrypt kebechet and qebhwt secrets with updates sops
  kebechet/overlays/cnv-prod/secrets.enc.yaml
  qeb-hwt-github-app/overlays/cnv-prod/secrets.enc.yaml
Labels: approved, size/L

#803 restructure sefkhet-abwy to separate prod and stage
  sefkhet-abwy/base/deploymentconfig.yaml
  sefkhet-abwy/base/imagestream.yaml
  sefkhet-abwy/base/route.yaml
  sefkhet-abwy/base/service.yaml
  sefkhet-abwy/overlays/cnv-prod/configmap.yaml
  sefkhet-abwy/overlays/cnv-prod/imagestreamtag.yaml
  sefkhet-abwy/overlays/cnv-prod/kustomization.yaml
  sefkhet-abwy/overlays/cnv-prod/secrets.enc.yaml
  sefkhet-abwy/overlays/ocp/imagestreamtag.yaml
  sefkhet-abwy/overlays/ocp/kustomization.yaml
  sefkhet-abwy/overlays/ocp/ultrahook.yaml
Labels: approved, size/L

#740 updated the docs for creating a new component
  README.md
Labels: approved, area/documentation, sig/documentation, size/M

#806 Bump workflow-helpers stage to v0.4.0
  core/overlays/ocp4-stage/common/imagestreamtags.yaml
  core/overlays/stage/common/imagestreamtags.yaml
Labels: approved, sig/devops, size/XS

#807 Add env variables for metrics
  graph-schema-update/base/openshift-templates/graph-schema-update-job-template.yaml
  kebechet/base/argo-workflows/kebechet-administrator.yaml
  solver/base/argo-workflows/parse-solver-output.yaml
Labels: approved, size/S

#805 setting lgtm_acts_as_approve: false for all our repos
  prow/overlays/cnv-prod/plugins.yaml
Labels: approved, sig/devops, size/XS

#815 Bump SLO reporter stage to v0.8.2
  slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml
  slo-reporter/overlays/stage/imagestreamtag.yaml
Labels: approved, sig/devops, size/XS

#811 Bump package-extract to v1.1.0 in stage
  package-extract/overlays/ocp4-stage/imagestreamtag.yaml
  package-extract/overlays/stage/imagestreamtag.yaml
Labels: approved, lgtm, size/XS

#819 Bump SLO reporter in prod and change email recipient in stage
  slo-reporter/overlays/cnv-prod/configmap.yaml
  slo-reporter/overlays/cnv-prod/imagestreamtag.yaml
  slo-reporter/overlays/ocp4-stage/configmap.yaml
Labels: approved, size/XS

#812 add cronjob to sync all the labels
  prow/base/imagestreams.yaml
  prow/base/label_sync_job.yaml
  prow/overlays/cnv-prod/imagestreamtags.yaml
  prow/overlays/cnv-prod/kustomization.yaml
  prow/overlays/cnv-prod/label-sync-cronjob.yaml
  prow/overlays/cnv-prod/labels.yaml
  prow/overlays/cnv-prod/plugins.yaml
Labels: approved, sig/devops, size/XXL
