Repository thoth-station/thoth-application, pull requests merged in 2021-06, with the labels that each got.

#1111 allow cyborg to simple merge pr instead of squash for aiops
  prow/overlays/cnv-prod/config.yaml
Labels: approved, lgtm, size/XS

#1117 allow cyborg to simple merge pr instead of squash for thoth-station
  prow/overlays/cnv-prod/config.yaml
Labels: approved, lgtm, size/XS

#1223 turn the utility images into imagestreamtags
  prow/add-ist
  prow/base/imagestreams.yaml
  prow/overlays/cnv-prod/config.yaml
  prow/overlays/cnv-prod/imagestreamtags.yaml
Labels: approved, kind/feature, sig/devops, size/L

#1529 Bump management-api to v0.17.1 in stage environment
  management-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1542 Supply Prometheus URL to CVE update job
  cve-update/base/cronjob.yaml
Labels: approved, size/XS

#1544 add 'thamos_token' for user-api authentication
  kebechet/base/argo-workflows/kebechet-run-url.yaml
  kebechet/base/argo-workflows/kebechet.yaml
Labels: approved, size/S

#1545 Bump CVE update job to v0.3.0 in stage environment
  cve-update/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1518 Use solver v1.9.0 in prod environment
  solver/overlays/cnv-prod/imagestreamtag.yaml
Labels: approved, size/XS

#1531 Deploy user-api v0.25.2 to stage environment
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1532 Bump Kebechet to v1.3.0 in stage environment
  kebechet/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1541 Bump adviser to v0.31.0 in stage environment
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1548 Bump graph-backup-job to v0.8.4 in stage environment
  graph-backup-job/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1549 Bump graph-refresh to v0.3.7 in stage environment
  graph-refresh/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1551 Bump management-api to v0.17.2 in stage environment
  management-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1560 Archive logs to have them accessible to users
  core/overlays/ocp4-stage/backend-stage/configmaps.yaml
  core/overlays/quicklab/configmaps.yaml
  core/overlays/test/configmaps.yaml
  core/overlays/zero-test/configmaps.yaml
Labels: approved, size/XS

#1552 Increase memory and CPU for the CVE update job
  cve-update/base/cronjob.yaml
Labels: approved, size/XS

#1559 Allow argo role list pod logs
  core/overlays/cnv-prod/backend-prod/argo-namespace-install.yaml
  core/overlays/ocp4-stage/backend-stage/argo-namespace-install.yaml
  core/overlays/quicklab/argo-namespace-install.yaml
  core/overlays/test/argo-namespace-install.yaml
  core/overlays/zero-test/argo-namespace-install.yaml
Labels: approved, size/M

#1500 Add merge cronjob
  mi-scheduler/base/cronjob.yaml
  mi-scheduler/overlays/cnv-prod/cronjob.yaml
  mi-scheduler/overlays/ocp4-stage/cronjob.yaml
  mi-scheduler/overlays/test/cronjob.yaml
Labels: approved, size/L

#1566 wrong env var used for ca location
  cve-update/base/cronjob.yaml
Labels: approved, size/XS

#1540 Make structured logging configurable
  advise-reporter/base/cronjob.yaml
  advise-reporter/overlays/test/cronjob.yaml
  adviser/base/argo-workflows/advise.yaml
  adviser/base/argo-workflows/kebechet-run-results.yaml
  adviser/base/argo-workflows/provenance-check.yaml
  amun/base/deploymentconfig.yaml
  amun/overlays/test/deploymentconfig.yaml
  build-watcher/base/deploymentconfig.yaml
  buildlog-parser/base/argo-workflows/buildlog-parser.yaml
  core/base/argo-workflows/send-messages.yaml
  core/overlays/cnv-prod/common/configmaps.yaml
  core/overlays/ocp4-stage/common/configmaps.yaml
  core/overlays/quicklab/configmaps.yaml
  core/overlays/test/configmaps.yaml
  core/overlays/zero-test/configmaps.yaml
  cve-update/base/cronjob.yaml
  graph-backup-job/base/cronjob.yaml
  graph-refresh/base/cronjob.yaml
  graph-schema-update/base/openshift-templates/graph-schema-update-job-template.yaml
  graph-sync/base/argo-workflows/sync-template.yaml
  graph-sync/base/openshift-templates/syncJob-template.yaml
  init-job/base/argo-workflows/solve-core-packages.yaml
  init-job/base/argo-workflows/solve-data-science-packages.yaml
  integration-tests/base/cronjob.yaml
  investigator/base/deploymentconfig.yaml
  investigator/overlays/test/deploymentconfig.yaml
  investigator/overlays/zero-test/deploymentconfig.yaml
  investigator_message_metrics/base/deploymentconfig.yaml
  investigator_message_metrics/overlays/test/deploymentconfig.yaml
  kebechet/base/argo-workflows/kebechet-administrator.yaml
  kebechet/base/argo-workflows/kebechet-run-url.yaml
  kebechet/base/argo-workflows/kebechet.yaml
  kebechet/overlays/bot/kebechet-aicoe-cronjob.yaml
  kebechet/overlays/bot/kebechet-thoth-cronjob.yaml
  management-api/base/deploymentconfig.yaml
  metrics-exporter/base/deploymentconfig.yaml
  package-releases/base/cronjob.yaml
  package-update/base/cronjob.yaml
  prescription-sync-job/base/cronjob.yaml
  prow/overlays/cnv-prod/config.yaml
  purge-job/base/argo-workflows/purge-template.yaml
  qeb-hwt-github-app/base/argo-workflows/qeb-hwt-integration.yaml
  qeb-hwt-github-app/base/deploymentconfig.yaml
  qeb-hwt-github-app/overlays/test/argo-workflows/qeb-hwt-integration.yaml
  revsolver/base/argo-workflows/revsolver-template.yaml
  sefkhet-abwy/base/deploymentconfig.yaml
  slo-reporter/base/cronjob.yaml
  slo-reporter/overlays/ocp4-stage/cronjob.yaml
  slo-reporter/overlays/zero-prod-ocp4-stage/cronjob.yaml
  solver/base/argo-workflows/parse-solver-output.yaml
  solver/base/argo-workflows/solver-template.yaml
  solver/overlays/test/argo-workflows/solver-template.yaml
  user-api/base/deploymentconfig.yaml
Labels: approved, size/L

#1607 update the certs for the services
  amun/overlays/cnv-prod/amun-api/route.enc.yaml
  amun/overlays/ocp4-stage/amun-api/route.enc.yaml
  amun/overlays/test/route.enc.yaml
  management-api/overlays/cnv-prod/route.enc.yaml
  management-api/overlays/ocp4-stage/route.enc.yaml
  management-api/overlays/test/route.enc.yaml
  prow/overlays/cnv-prod/routes.enc.yaml
  user-api/overlays/cnv-prod/khemenu.route.enc.yaml
  user-api/overlays/cnv-prod/route.enc.yaml
  user-api/overlays/ocp4-stage/khemenu.route.enc.yaml
  user-api/overlays/ocp4-stage/route.enc.yaml
  user-api/overlays/test/route.enc.yaml
Labels: approved, size/XXL

#1608 Fix the amun argo workflow setup
  amun/base/kustomization.yaml
  amun/overlays/cnv-prod/amun-api/argo-workflows/send-messages.yaml
  amun/overlays/cnv-prod/amun-api/kustomization.yaml
  amun/overlays/ocp4-stage/amun-api/argo-workflows/send-messages.yaml
  amun/overlays/ocp4-stage/amun-api/kustomization.yaml
Labels: approved, size/M

#1609 Adjusted the argo deployment for stage services
  core/overlays/ocp4-stage/backend-stage/argo-deployments.yaml
  core/overlays/ocp4-stage/backend-stage/argo-imagestreams.yaml
  core/overlays/ocp4-stage/backend-stage/argo-mangement.yaml
  core/overlays/ocp4-stage/backend-stage/argo-namespace-install.yaml
  core/overlays/ocp4-stage/backend-stage/argo-ui-controller.yaml
  core/overlays/ocp4-stage/backend-stage/argo-workflow-controller.yaml
  core/overlays/ocp4-stage/backend-stage/kustomization.yaml
  core/overlays/ocp4-stage/middletier-stage/argo-deployments.yaml
  core/overlays/ocp4-stage/middletier-stage/argo-imagestreams.yaml
  core/overlays/ocp4-stage/middletier-stage/argo-mangement.yaml
  core/overlays/ocp4-stage/middletier-stage/argo-namespace-install.yaml
  core/overlays/ocp4-stage/middletier-stage/argo-ui-controller.yaml
  core/overlays/ocp4-stage/middletier-stage/argo-workflow-controller.yaml
  core/overlays/ocp4-stage/middletier-stage/kustomization.yaml
Labels: approved, size/XL

#1547 Bump revsolver to v0.2.5 in stage environment
  revsolver/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1610 Refactor the argo setup for thoth services
  amun/overlays/cnv-prod/amun-inspection/argo-deployments.yaml
  amun/overlays/cnv-prod/amun-inspection/argo-imagestreams.yaml
  amun/overlays/cnv-prod/amun-inspection/argo-management.yaml
  amun/overlays/cnv-prod/amun-inspection/argo-namespace-install.yaml
  amun/overlays/cnv-prod/amun-inspection/argo-ui-controller.yaml
  amun/overlays/cnv-prod/amun-inspection/argo-workflow-controller.yaml
  amun/overlays/cnv-prod/amun-inspection/kustomization.yaml
  amun/overlays/ocp4-stage/amun-inspection/argo-deployments.yaml
  amun/overlays/ocp4-stage/amun-inspection/argo-imagestreams.yaml
  amun/overlays/ocp4-stage/amun-inspection/argo-management.yaml
  amun/overlays/ocp4-stage/amun-inspection/argo-namespace-install.yaml
  amun/overlays/ocp4-stage/amun-inspection/argo-ui-controller.yaml
  amun/overlays/ocp4-stage/amun-inspection/argo-ui-route.yaml
  amun/overlays/ocp4-stage/amun-inspection/argo-workflow-controller.yaml
  amun/overlays/ocp4-stage/amun-inspection/kustomization.yaml
  core/overlays/cnv-prod/backend-prod/argo-deployments.yaml
  core/overlays/cnv-prod/backend-prod/argo-imagestreams.yaml
  core/overlays/cnv-prod/backend-prod/argo-management.yaml
  core/overlays/cnv-prod/backend-prod/argo-namespace-install.yaml
  core/overlays/cnv-prod/backend-prod/argo-ui-controller.yaml
  core/overlays/cnv-prod/backend-prod/argo-ui-route.yaml
  core/overlays/cnv-prod/backend-prod/argo-workflow-controller.yaml
  core/overlays/cnv-prod/backend-prod/kustomization.yaml
  core/overlays/cnv-prod/middletier-prod/argo-deployments.yaml
  core/overlays/cnv-prod/middletier-prod/argo-imagestreams.yaml
  core/overlays/cnv-prod/middletier-prod/argo-management.yaml
  core/overlays/cnv-prod/middletier-prod/argo-namespace-install.yaml
  core/overlays/cnv-prod/middletier-prod/argo-ui-controller.yaml
  core/overlays/cnv-prod/middletier-prod/argo-ui-route.yaml
  core/overlays/cnv-prod/middletier-prod/argo-workflow-controller.yaml
  core/overlays/cnv-prod/middletier-prod/kustomization.yaml
  core/overlays/ocp4-stage/backend-stage/argo-management.yaml
  core/overlays/ocp4-stage/backend-stage/kustomization.yaml
  core/overlays/ocp4-stage/middletier-stage/argo-management.yaml
  core/overlays/ocp4-stage/middletier-stage/kustomization.yaml
  core/overlays/test/argo-deployments.yaml
  core/overlays/test/argo-imagestreams.yaml
  core/overlays/test/argo-management.yaml
  core/overlays/test/argo-namespace-install.yaml
  core/overlays/test/argo-ui-controller.yaml
  core/overlays/test/argo-workflow-controller.yaml
  core/overlays/test/kustomization.yaml
  core/overlays/zero-test/argo-deployments.yaml
  core/overlays/zero-test/argo-imagestreams.yaml
  core/overlays/zero-test/argo-management.yaml
  core/overlays/zero-test/argo-namespace-install.yaml
  core/overlays/zero-test/argo-role.yaml
  core/overlays/zero-test/argo-ui-controller.yaml
  core/overlays/zero-test/argo-workflow-controller.yaml
  core/overlays/zero-test/kustomization.yaml
Labels: approved, size/XXL

#1612 Bump up the version of stage thoth services
  core/overlays/ocp4-stage/common/imagestreamtags.yaml
  core/overlays/test/imagestreamtags.yaml
  core/overlays/zero-test/imagestreamtags.yaml
  graph-sync/overlays/ocp4-stage/imagestreamtag.yaml
  graph-sync/overlays/test/imagestreamtag.yaml
  metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
  package-releases/overlays/ocp4-stage/imagestreamtag.yaml
  package-releases/overlays/test/imagestreamtag.yaml
Labels: approved, size/S

#1613 Bump thoth production services with updated versions
  advise-reporter/overlays/cnv-prod/imagestreamtag.yaml
  core/overlays/cnv-prod/common/imagestreamtags.yaml
  cve-update/overlays/cnv-prod/imagestreamtag.yaml
  graph-backup-job/overlays/cnv-prod/imagestreamtag.yaml
  graph-refresh/overlays/cnv-prod/imagestreamtag.yaml
  graph-sync/overlays/cnv-prod/imagestreamtag.yaml
  management-api/overlays/cnv-prod/imagestreamtag.yaml
  metrics-exporter/overlays/cnv-prod/imagestreamtag.yaml
  package-releases/overlays/cnv-prod/imagestreamtag.yaml
  revsolver/overlays/cnv-prod/imagestreamtag.yaml
  user-api/overlays/cnv-prod/imagestreamtag.yaml
Labels: approved, size/S

#1614 Bump thoth production services with updated versions
  adviser/overlays/cnv-prod/imagestreamtag.yaml
Labels: approved, size/XS

#1533 Bump Kebechet to v1.3.0 in prod
  kebechet/overlays/cnv-prod/imagestreamtag.yaml
Labels: approved, size/XS

#1621 Reduce the cpu limit for metrics-exporter
  metrics-exporter/overlays/cnv-prod/resources_patch.yaml
Labels: approved, size/XS

#1620 set resource limit for prow jobs
  .prow.yaml
Labels: approved, size/S

#1625 revert back to kebechet v1.2.4
  kebechet/overlays/cnv-prod/imagestreamtag.yaml
Labels: approved, size/XS

#1629 Supply a path to labels.json location to take labels into account
  adviser/base/argo-workflows/advise.yaml
Labels: approved, size/XS

#1631 Pass configured solvers in a deployment to adviser
  adviser/base/argo-workflows/advise.yaml
Labels: approved, size/XS

#1632 Bump user-api to v0.26.0 in stage environment
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1642 Bump metrics-exporter to v0.14.6 to fix bug
  metrics-exporter/overlays/cnv-prod/imagestreamtag.yaml
  metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1638 Bump Kebechet to v1.3.1 in stage environment
  kebechet/overlays/cnv-prod/imagestreamtag.yaml
  kebechet/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1639 Bump graph-refresh job to v0.3.8 in stage environment
  graph-refresh/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1640 Bump graph-sync-job to v0.10.9 in stage environment
  graph-sync/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1637 Bump adviser to v0.33.0 in stage environment
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1641 Add increased timeout seconds
  mi-scheduler/base/argo-workflows/mi-workflow-template.yaml
Labels: approved, lgtm, size/XS

#1643 add retry strategy for installation update
  kebechet/base/argo-workflows/update_keb_installation.yaml
Labels: approved, size/XS

#1645 Bump management-api to v0.17.3 in stage environment
  management-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1652 Rollback Kebechet due to bug
  kebechet/overlays/cnv-prod/imagestreamtag.yaml
Labels: approved, size/XS

#1655 add new template param for package update advises
  adviser/base/argo-workflows/advise.yaml
  adviser/base/openshift-templates/adviser.yaml
Labels: approved, lgtm, size/S

#1550 Bump Amun API to v0.9.5 in stage environment
  amun/overlays/ocp4-stage/amun-api/imagestreamtag.yaml
Labels: approved, size/XS

#1647 increase the resource for kustomize prow job
  .prow.yaml
Labels: approved, size/XS

#1517 Add solver-f34-py39 to CNV prod
  solver/base/imagestreams.yaml
  solver/overlays/cnv-prod/imagestreamtag.yaml
Labels: approved, priority/critical-urgent, size/S

#1659 bump version of Adviser v0.33.1 in stage
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1661 Fix env variable breaking cronjob SLO reporter
  slo-reporter/overlays/zero-prod-ocp4-stage/cronjob.yaml
Labels: approved, size/XS

#1660 updates from the template project
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: approved, bot, size/XS

#1663 Set timeoute under the step specification
  mi-scheduler/base/argo-workflows/mi-workflow-template.yaml
  mi-scheduler/base/openshift-templates/mi-run-template.yaml
Labels: approved, size/XS

#1665 Block security indicator step to resolve stacks without si
  adviser/base/argo-workflows/advise.yaml
Labels: approved, size/XS

#1667 deploy triage-party #1649
  triage-party/overlays/zero-prod/kustomization.yaml
  triage-party/overlays/zero-prod/pcache.yaml
Labels: approved, size/XS

#1668 Switch to thoth-station triage-party image
  triage-party/overlays/zero-prod/imagestreamtags.yaml
Labels: approved, size/XS

#1250 introduce GitHub release notes prescription job
  prescriptions-gh-release-notes-job/base/openshift-templates/prescriptions-gh-release-notes.yaml
Labels: approved, kind/demo, lgtm, size/L

#1685 Bump adviser to v0.33.2 in prod and stage environments
  adviser/overlays/cnv-prod/imagestreamtag.yaml
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, lgtm, size/XS

#1681 Bump version of Kebechet v1.3.2 in stage
  kebechet/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, lgtm, size/XS

#1691 Suspend prescription-sync-job in all deployments
  prescription-sync-job/overlays/cnv-prod/cronjob.yaml
  prescription-sync-job/overlays/ocp4-stage/cronjob.yaml
  prescription-sync-job/overlays/test/cronjob.yaml
Labels: approved, size/XS

#1696 Bump up all apps which are related to the messaging update
  amun/overlays/cnv-prod/amun-api/message-imagestream.yaml
  amun/overlays/ocp4-stage/amun-api/message-imagestream.yaml
  amun/overlays/test/message-imagestream.yaml
  core/overlays/cnv-prod/common/imagestreamtags.yaml
  core/overlays/ocp4-stage/common/imagestreamtags.yaml
  core/overlays/zero-test/imagestreamtags.yaml
  graph-refresh/overlays/cnv-prod/imagestreamtag.yaml
  graph-refresh/overlays/ocp4-stage/imagestreamtag.yaml
  package-releases/overlays/cnv-prod/imagestreamtag.yaml
  package-releases/overlays/ocp4-stage/imagestreamtag.yaml
  package-update/overlays/cnv-prod/imagestreamtag.yaml
  package-update/overlays/ocp4-stage/imagestreamtag.yaml
  user-api/overlays/cnv-prod/imagestreamtag.yaml
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/M

#1646 Configure solver rules in init-job
  init-job/base/argo-workflows/initialize-schema.yaml
Labels: approved, lgtm, size/XS

#1682 Bump version of Kebechet v1.3.2 in prod
  kebechet/overlays/cnv-prod/imagestreamtag.yaml
Labels: approved, size/XS

#1697 enable all deployment environments to have new solvers
  solver/overlays/ocp4-stage/imagestreamtag.yaml
  solver/overlays/test/imagestreamtag.yaml
Labels: approved, size/M

#1698 Enable fedora34 python 3.9 data ingestion in prod
  core/overlays/cnv-prod/common/configmaps.yaml
Labels: approved, size/XS

#1699 set the required env vars for triage-party
  triage-party/base/deployment.yaml
Labels: approved, size/XS

#1694 Add image streams for prescriptions
  adviser/base/imagestream.yaml
  adviser/overlays/cnv-prod/imagestreamtag.yaml
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
  adviser/overlays/test/imagestreamtag.yaml
Labels: approved, lgtm, size/M

#1701 Disable prescriptions before adding prescriptions with dir structure
  adviser/base/argo-workflows/advise.yaml
Labels: approved, lgtm, size/S

#1702 Bump metrics-exporter to v0.15.0
  metrics-exporter/overlays/cnv-prod/imagestreamtag.yaml
  metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, lgtm, size/XS

#1706 Bump adviser to v0.34.0 in stage environment
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, lgtm, size/XS

#1708 Bump graph-sync-job to v0.10.9 in prod environment
  graph-sync/overlays/cnv-prod/imagestreamtag.yaml
Labels: approved, size/XS

#1705 Make prescriptions v0.0.1 available in stage and prod environments
  adviser/overlays/cnv-prod/imagestreamtag.yaml
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, lgtm, size/XS

#1707 Bump adviser container to v0.34.0 in prod environment
  adviser/overlays/cnv-prod/imagestreamtag.yaml
Labels: approved, lgtm, size/XS

#1510 add peribolos for thoth-station
  prow/overlays/cnv-prod/kustomization.yaml
  prow/overlays/cnv-prod/org_thoth-station.yaml
  prow/overlays/cnv-prod/peribolos.yaml
Labels: approved, lgtm, size/XXL

#1712 update the ssl certs for investigator
  core/overlays/cnv-prod/common/secrets.enc.yaml
  investigator/overlays/cnv-prod/deploymentconfig.yaml
  investigator/overlays/cnv-prod/kustomization.yaml
Labels: approved, size/L

#1713 Add increased timeout to workflow template (12k seconds)
  mi-scheduler/base/argo-workflows/mi-workflow-template.yaml
Labels: approved, size/XS

#1693 Decommission prescription-sync-job
  prescription-sync-job/base/cronjob.yaml
  prescription-sync-job/base/imagestream.yaml
  prescription-sync-job/base/kustomization.yaml
  prescription-sync-job/overlays/cnv-prod/cronjob.yaml
  prescription-sync-job/overlays/cnv-prod/imagestreamtag.yaml
  prescription-sync-job/overlays/cnv-prod/job-generate-name.yaml
  prescription-sync-job/overlays/cnv-prod/kustomization.yaml
  prescription-sync-job/overlays/cnv-prod/thoth-notification.yaml
  prescription-sync-job/overlays/ocp4-stage/cronjob.yaml
  prescription-sync-job/overlays/ocp4-stage/imagestreamtag.yaml
  prescription-sync-job/overlays/ocp4-stage/job-generate-name.yaml
  prescription-sync-job/overlays/ocp4-stage/kustomization.yaml
  prescription-sync-job/overlays/ocp4-stage/thoth-notification.yaml
  prescription-sync-job/overlays/test/cronjob.yaml
  prescription-sync-job/overlays/test/imagestreamtag.yaml
  prescription-sync-job/overlays/test/job-generate-name.yaml
  prescription-sync-job/overlays/test/kustomization.yaml
  prescription-sync-job/overlays/test/thoth-notification.yaml
Labels: approved, lgtm, size/L

#1716 setup the investigator message metrics for prod
  investigator_message_metrics/overlays/zero-prod/deploymentconfig.yaml
  investigator_message_metrics/overlays/zero-prod/kustomization.yaml
Labels: approved, size/L

#1718 bump up module with messaging update
  advise-reporter/overlays/cnv-prod/imagestreamtag.yaml
  advise-reporter/overlays/ocp4-stage/imagestreamtag.yaml
  user-api/overlays/cnv-prod/imagestreamtag.yaml
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1695 Make prescriptions available to the adviser container
  adviser/base/argo-workflows/advise.yaml
Labels: approved, lgtm, size/S

#1720 fix the slo-reporter configmap and cronjob
  slo-reporter/overlays/zero-prod-ocp4-stage/configmap.yaml
  slo-reporter/overlays/zero-prod-ocp4-stage/cronjob.yaml
Labels: approved, size/M

#1723 Add merge flags to run and workflow templates
  mi-scheduler/base/argo-workflows/mi-workflow-template.yaml
  mi-scheduler/base/openshift-templates/mi-run-template.yaml
Labels: approved, size/S

#1724 updated the sa for the prescription release notes
  prescriptions-gh-release-notes-job/base/openshift-templates/prescriptions-gh-release-notes.yaml
Labels: approved, size/XS

#1726 Add missing template for Kebechet administrator
  kebechet/overlays/cnv-prod/kustomization.yaml
  kebechet/overlays/ocp4-stage/kustomization.yaml
Labels: approved, lgtm, size/S

#1725 Make repository parameter not required
  mi-scheduler/base/openshift-templates/mi-run-template.yaml
Labels: approved, lgtm, size/XS

#1719 Introduce graph-metrics-exporter Cronjob
  graph-metrics-exporter/base/cronjob.yaml
  graph-metrics-exporter/base/imagestream.yaml
  graph-metrics-exporter/base/kustomization.yaml
  graph-metrics-exporter/overlays/cnv-prod/cronjob.yaml
  graph-metrics-exporter/overlays/cnv-prod/imagestreamtag.yaml
  graph-metrics-exporter/overlays/cnv-prod/job-generate-name.yaml
  graph-metrics-exporter/overlays/cnv-prod/kustomization.yaml
  graph-metrics-exporter/overlays/cnv-prod/thoth-notification.yaml
  graph-metrics-exporter/overlays/ocp4-stage/cronjob.yaml
  graph-metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
  graph-metrics-exporter/overlays/ocp4-stage/job-generate-name.yaml
  graph-metrics-exporter/overlays/ocp4-stage/kustomization.yaml
  graph-metrics-exporter/overlays/ocp4-stage/thoth-notification.yaml
  graph-metrics-exporter/overlays/test/cronjob.yaml
  graph-metrics-exporter/overlays/test/imagestreamtag.yaml
  graph-metrics-exporter/overlays/test/job-generate-name.yaml
  graph-metrics-exporter/overlays/test/kustomization.yaml
  graph-metrics-exporter/overlays/test/thoth-notification.yaml
Labels: approved, size/L

#1728 Bump metrics-expoter to v0.16.0
  metrics-exporter/overlays/cnv-prod/imagestreamtag.yaml
  metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
Labels: size/XS

#1743 fix of the volume usage in the workflow
  adviser/base/argo-workflows/advise.yaml
Labels: approved, size/S

#1745 fix of the volume placement in the workflow
  adviser/base/argo-workflows/advise.yaml
  adviser/base/openshift-templates/adviser.yaml
Labels: approved, size/XS

#1754 Reduce the resource usage based on comsumption
  solver/base/argo-workflows/solver-template.yaml
Labels: approved, size/XS

#1755 Introduce pulp-pypi-sync-job
  core/base/configmaps.yaml
  pulp-pypi-sync-job/base/cronjob.yaml
  pulp-pypi-sync-job/base/imagestream.yaml
  pulp-pypi-sync-job/base/kustomization.yaml
  pulp-pypi-sync-job/overlays/cnv-prod/cronjob.yaml
  pulp-pypi-sync-job/overlays/cnv-prod/imagestreamtag.yaml
  pulp-pypi-sync-job/overlays/cnv-prod/job-generate-name.yaml
  pulp-pypi-sync-job/overlays/cnv-prod/kustomization.yaml
  pulp-pypi-sync-job/overlays/cnv-prod/thoth-notification.yaml
  pulp-pypi-sync-job/overlays/ocp4-stage/cronjob.yaml
  pulp-pypi-sync-job/overlays/ocp4-stage/imagestreamtag.yaml
  pulp-pypi-sync-job/overlays/ocp4-stage/job-generate-name.yaml
  pulp-pypi-sync-job/overlays/ocp4-stage/kustomization.yaml
  pulp-pypi-sync-job/overlays/ocp4-stage/thoth-notification.yaml
  pulp-pypi-sync-job/overlays/test/cronjob.yaml
  pulp-pypi-sync-job/overlays/test/imagestreamtag.yaml
  pulp-pypi-sync-job/overlays/test/job-generate-name.yaml
  pulp-pypi-sync-job/overlays/test/kustomization.yaml
  pulp-pypi-sync-job/overlays/test/thoth-notification.yaml
Labels: lgtm, size/L

#1744 Fix MEGE typo into MERGE
  mi-scheduler/base/openshift-templates/mi-run-template.yaml
Labels: approved

#1727 Add latest tags to cronjobs
  mi-scheduler/base/cronjob.yaml
Labels: approved, size/XS

#1756 bump metrics-exporter to v0.16.1
  metrics-exporter/overlays/cnv-prod/imagestreamtag.yaml
  metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1759 Update dashboards
  grafana-dashboard/overlays/cnv-prod/thoth-knowledge-graph-content-metrics.json
  grafana-dashboard/overlays/cnv-prod/thoth-sli-slo.json
Labels: approved, size/XXL

#1760 set the resource based on the usage
  metrics-exporter/base/deploymentconfig.yaml
  metrics-exporter/overlays/cnv-prod/deploymentconfig.yaml
Labels: approved, size/XS

#1762 set more timeout sec for graph schema update
  graph-schema-update/base/openshift-templates/graph-schema-update-job-template.yaml
Labels: approved, size/XS

#1758 Decrease TTL to 300 for pods
  adviser/base/openshift-templates/adviser.yaml
  package-extract/base/openshift-templates/package-extract.yaml
Labels: approved, size/S

#1765 Mi scheduler/schedule aicoe aiops
  mi-scheduler/base/configmaps.yaml
Labels: approved, size/XS

#1768 Bump integration-tests to v0.8.3
  integration-tests/overlays/cnv-prod-ocp4-stage/imagestreamtag.yaml
  integration-tests/overlays/ocp4-stage/imagestreamtag.yaml
  prow/overlays/cnv-prod/config.yaml
Labels: approved, size/XS

#1770 bump graph-metrics-exporter to v0.5.1
  graph-metrics-exporter/overlays/cnv-prod/imagestreamtag.yaml
  graph-metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1771 Bump SLO reporter to v0.15.0
  slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml
  slo-reporter/overlays/zero-prod-ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1773 fix: Enable on repo prow for AICoE
  prow/overlays/cnv-prod/config.yaml
Labels: approved, size/XS

#1772 pause the data ingestion for the storage issue
  graph-refresh/overlays/cnv-prod/cronjob.yaml
  package-releases/overlays/cnv-prod/cronjob.yaml
  package-update/overlays/cnv-prod/cronjob.yaml
Labels: approved, size/XS

#1761 Remove qeb-hwt app
  qeb-hwt-github-app/README.md
  qeb-hwt-github-app/base/argo-workflows/qeb-hwt-integration.yaml
  qeb-hwt-github-app/base/deploymentconfig.yaml
  qeb-hwt-github-app/base/imagestream.yaml
  qeb-hwt-github-app/base/kustomization.yaml
  qeb-hwt-github-app/base/openshift-templates/qeb-hwt.yaml
  qeb-hwt-github-app/base/route.yaml
  qeb-hwt-github-app/base/service.yaml
  qeb-hwt-github-app/overlays/cnv-prod/configmap.yaml
  qeb-hwt-github-app/overlays/cnv-prod/imagestreamtag.yaml
  qeb-hwt-github-app/overlays/cnv-prod/job-generate-name.yaml
  qeb-hwt-github-app/overlays/cnv-prod/kustomization.yaml
  qeb-hwt-github-app/overlays/cnv-prod/put-into-backend-namespace.yaml
  qeb-hwt-github-app/overlays/cnv-prod/put-into-infra-namespace.yaml
  qeb-hwt-github-app/overlays/cnv-prod/secret-generator.yaml
  qeb-hwt-github-app/overlays/cnv-prod/secrets.enc.yaml
  qeb-hwt-github-app/overlays/cnv-prod/thoth-notification.yaml
  qeb-hwt-github-app/overlays/ocp4-stage/configmap.yaml
  qeb-hwt-github-app/overlays/ocp4-stage/imagestreamtag.yaml
  qeb-hwt-github-app/overlays/ocp4-stage/job-generate-name.yaml
  qeb-hwt-github-app/overlays/ocp4-stage/kustomization.yaml
  qeb-hwt-github-app/overlays/ocp4-stage/put-into-backend-namespace.yaml
  qeb-hwt-github-app/overlays/ocp4-stage/put-into-infra-namespace.yaml
  qeb-hwt-github-app/overlays/ocp4-stage/secret-generator.yaml
  qeb-hwt-github-app/overlays/ocp4-stage/secrets.enc.yaml
  qeb-hwt-github-app/overlays/ocp4-stage/thoth-notification.yaml
  qeb-hwt-github-app/overlays/ocp4-stage/ultrahook-deployment.yaml
  qeb-hwt-github-app/overlays/test/argo-workflows/qeb-hwt-integration.yaml
  qeb-hwt-github-app/overlays/test/configmap.yaml
  qeb-hwt-github-app/overlays/test/imagestreamtag.yaml
  qeb-hwt-github-app/overlays/test/job-generate-name.yaml
  qeb-hwt-github-app/overlays/test/kustomization.yaml
  qeb-hwt-github-app/overlays/test/openshift-templates/qeb-hwt.yaml
  qeb-hwt-github-app/overlays/test/secret-generator.yaml
  qeb-hwt-github-app/overlays/test/secrets.enc.yaml
  qeb-hwt-github-app/overlays/test/thoth-notification.yaml
  qeb-hwt-github-app/overlays/test/ultrahook-deployment.yaml
Labels: approved, lgtm, size/XXL

#1774 Stop SLO-reporter test
  slo-reporter/overlays/test/cronjob.yaml
Labels: approved, size/XS

#1775 Remove last bits of qeb-hwt
  adviser/base/argo-workflows/trigger-integration.yaml
  adviser/base/openshift-templates/adviser.yaml
  core/base/configmaps.yaml
  core/overlays/cnv-prod/common/configmaps.yaml
  core/overlays/ocp4-stage/common/configmaps.yaml
  core/overlays/test/configmaps.yaml
  core/overlays/zero-test/configmaps.yaml
  docs/environments.md
  prow/overlays/cnv-prod/labels.yaml
  prow/overlays/cnv-prod/org_thoth-station.yaml
Labels: approved, lgtm, size/L

#1776 pause the data ingestion for the stage cluster
  advise-reporter/overlays/ocp4-stage/cronjob.yaml
  cve-update/overlays/ocp4-stage/cronjob.yaml
  graph-refresh/overlays/ocp4-stage/cronjob.yaml
  package-releases/overlays/ocp4-stage/cronjob.yaml
  package-update/overlays/ocp4-stage/cronjob.yaml
  slo-reporter/overlays/ocp4-stage/cronjob.yaml
Labels: approved, size/S

#1777 resume the data ingestion for the prod
  graph-refresh/overlays/cnv-prod/cronjob.yaml
  package-releases/base/cronjob.yaml
  package-update/overlays/cnv-prod/cronjob.yaml
Labels: approved, size/XS

#1778 Bump reporter to v0.10.0
  advise-reporter/overlays/cnv-prod/imagestreamtag.yaml
  advise-reporter/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1779 Bump package-extract to v1.2.0 in stage environment
  package-extract/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1611 Adding first community repo labels
  prow/overlays/cnv-prod/labels_operate-first.yaml
Labels: approved, lgtm, lifecycle/active, ok-to-test, priority/important-soon, size/M

#1780 chore: Remove label_sync for AICoE and OperateFirst
  prow/overlays/cnv-prod/kustomization.yaml
  prow/overlays/cnv-prod/label-sync-cronjob.yaml
  prow/overlays/cnv-prod/labels_aicoe.yaml
  prow/overlays/cnv-prod/labels_operate-first.yaml
Labels: approved, size/XL
