Repository thoth-station/thoth-application, pull requests merged in 2021-05, with the labels that each got.

#1217 missing new tag in test for advise-reporter
  advise-reporter/overlays/test/imagestreamtag.yaml
Labels: approved, size/XS

#1220 Bump up versions of thoth components in stage
  core/overlays/ocp4-stage/common/imagestreamtags.yaml
  core/overlays/test/imagestreamtags.yaml
  core/overlays/zero-test/imagestreamtags.yaml
  graph-backup-job/overlays/ocp4-stage/imagestreamtag.yaml
  graph-backup-job/overlays/test/imagestreamtag.yaml
  graph-refresh/overlays/ocp4-stage/imagestreamtag.yaml
  graph-refresh/overlays/test/imagestreamtag.yaml
  graph-sync/overlays/ocp4-stage/imagestreamtag.yaml
  graph-sync/overlays/test/imagestreamtag.yaml
  metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
  metrics-exporter/overlays/test/imagestreamtag.yaml
Labels: approved, size/S

#1219 Reduce the time to live 15 mins instead
  core/overlays/cnv-prod/backend-prod/configmaps.yaml
Labels: approved, size/XS

#1222 Expand db pvc size
  core/overlays/cnv-prod/graph-prod/postgresql.yaml
Labels: size/XS

#1225 enable argo serviceAccount to get pod logs
  core/overlays/cnv-prod/backend-prod/argo-role.yaml
  core/overlays/cnv-prod/middletier-prod/argo-role.yaml
  core/overlays/zero-test/argo-role.yaml
Labels: approved, lgtm, size/M

#1229 updated the correct variable for the provenance fix
  adviser/base/openshift-templates/provenance-checker.yaml
Labels: approved, size/XS

#1233 quotes added to the when expression for correct value substitution
  adviser/base/openshift-templates/adviser.yaml
Labels: approved, size/XS

#1234 fix the quotes in advise when expression
  adviser/base/openshift-templates/adviser.yaml
Labels: approved, size/XS

#1236 Add graph-namespace to configmaps
  core/overlays/cnv-prod/common/configmaps.yaml
  core/overlays/ocp4-stage/common/configmaps.yaml
  core/overlays/quicklab/configmaps.yaml
  core/overlays/test/configmaps.yaml
  core/overlays/zero-test/configmaps.yaml
Labels: approved, size/XS

#1237 Add graph namespace to management-api
  management-api/base/deploymentconfig.yaml
Labels: approved, size/XS

#1208 Introduce purge-job
  purge-job/base/argo-workflows/purge-template.yaml
  purge-job/base/imagestream.yaml
  purge-job/base/kustomization.yaml
  purge-job/base/openshift-templates/purge.yaml
  purge-job/overlays/cnv-prod/imagestreamtag.yaml
  purge-job/overlays/cnv-prod/job-generate-name.yaml
  purge-job/overlays/cnv-prod/kustomization.yaml
  purge-job/overlays/cnv-prod/put-into-infra-namespace.yaml
  purge-job/overlays/cnv-prod/thoth-notification.yaml
  purge-job/overlays/ocp4-stage/imagestreamtag.yaml
  purge-job/overlays/ocp4-stage/job-generate-name.yaml
  purge-job/overlays/ocp4-stage/kustomization.yaml
  purge-job/overlays/ocp4-stage/put-into-infra-namespace.yaml
  purge-job/overlays/ocp4-stage/thoth-notification.yaml
  purge-job/overlays/test/imagestreamtag.yaml
  purge-job/overlays/test/job-generate-name.yaml
  purge-job/overlays/test/kustomization.yaml
  purge-job/overlays/test/thoth-notification.yaml
Labels: approved, size/XL

#1239 Bump management-api to v0.16.0 in stage
  management-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1242 feat: Add incident labels
  prow/overlays/cnv-prod/labels_operate-first.yaml
Labels: approved, lgtm, size/S

#1241 Enable revsolver
  graph-refresh/base/cronjob.yaml
  investigator/base/deploymentconfig.yaml
  revsolver/overlays/cnv-prod/imagestreamtag.yaml
  revsolver/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1243 Fix accessing pod log from amun namespace by management-api
  management-api/base/role.yaml
  management-api/overlays/cnv-prod/kustomization.yaml
  management-api/overlays/cnv-prod/role-binding.yaml
Labels: approved, size/S

#1244 Fix accessing pod log from different namespace by user-api
  user-api/base/role.yaml
  user-api/overlays/cnv-prod/kustomization.yaml
  user-api/overlays/cnv-prod/role-binding.yaml
Labels: approved, size/S

#1245 Remove explicit stating the default value from purge templates
  purge-job/base/openshift-templates/purge.yaml
Labels: approved, size/XS

#1247 Fix accessing pod log from amun namespace by management-api in stage
  management-api/overlays/ocp4-stage/kustomization.yaml
  management-api/overlays/ocp4-stage/role-binding.yaml
Labels: approved, size/XS

#1246 correct the role name for user-api pods log access
  user-api/base/role.yaml
  user-api/overlays/cnv-prod/kustomization.yaml
  user-api/overlays/cnv-prod/role-binding.yaml
  user-api/overlays/ocp4-stage/kustomization.yaml
  user-api/overlays/ocp4-stage/role-binding.yaml
Labels: approved, size/S

#1255 update zero-test messaging
  core/overlays/zero-test/imagestreamtags.yaml
Labels: approved, size/XS

#1260 Tweak MCTS heat up phase
  adviser/base/argo-workflows/advise.yaml
Labels: approved, size/XS

#1261 Tweak MCTS heat up phase
  adviser/base/argo-workflows/advise.yaml
Labels: approved, size/XS

#1263 Bump adviser to v0.30.0 in stage
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1264 Bump adviser to v0.30.0 in prod
  adviser/overlays/cnv-prod/imagestreamtag.yaml
Labels: approved, size/XS

#1269 Separate zero-test overlay investigator as it uses non cluster role
  investigator/overlays/zero-test/deploymentconfig.yaml
  investigator/overlays/zero-test/job-generate-name.yaml
  investigator/overlays/zero-test/kustomization.yaml
  investigator/overlays/zero-test/role.yaml
  investigator/overlays/zero-test/role_binding.yaml
  investigator/overlays/zero-test/route.yaml
  investigator/overlays/zero-test/service.yaml
  investigator/overlays/zero-test/thoth-notification.yaml
Labels: approved, size/L

#1265 Setup alertmanager for thoth services alerting
  monitoring/base/alertmanager-monitoring.yaml
  monitoring/base/github-receiver.yaml
  monitoring/base/kustomization.yaml
  monitoring/base/prometheus-rules.yaml
  monitoring/overlays/cnv-prod/kustomization.yaml
  monitoring/overlays/cnv-prod/secret-generator.yaml
  monitoring/overlays/cnv-prod/secrets.enc.yaml
Labels: approved, size/L

#1279 Add new alerts for prod
  monitoring/base/prometheus-rules.yaml
Labels: approved, size/M

#1282 bump metrics exporter to v0.14.4
  metrics-exporter/overlays/cnv-prod/imagestreamtag.yaml
  metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
  metrics-exporter/overlays/test/imagestreamtag.yaml
Labels: approved, size/XS

#1277 add service discovery annotations/labels to user-api
  user-api/base/deploymentconfig.yaml
Labels: approved, size/S

#1284 bump slo-reporter to v0.14.2
  slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml
  slo-reporter/overlays/test/imagestreamtag.yaml
  slo-reporter/overlays/zero-prod-ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1295 update test image streams to latest releases
  adviser/overlays/test/imagestreamtag.yaml
  core/overlays/zero-test/imagestreamtags.yaml
Labels: approved, size/XS

#1301 setup nooba based ceph for prow
  prow/overlays/cnv-prod/s3-bucket-claim.yaml
Labels: approved, size/S

#1323 Arrange the prow images in alphabetical order
  prow/overlays/cnv-prod/imagestreamtags.yaml
Labels: approved, size/L

#1300 Set limits on the prow deployments based on usage
  prow/base/crier.yaml
  prow/base/deck.yaml
  prow/base/deploymentconfig.yaml
  prow/base/ghproxy.yaml
  prow/base/hook.yaml
  prow/base/label_sync_job.yaml
  prow/base/needs-rebase.yaml
  prow/base/prow-controller-manager.yaml
  prow/base/sinker.yaml
  prow/base/statusreconciler.yaml
  prow/base/tide.yaml
Labels: approved, size/M

#1238 keb admin workflow was failing
  core/base/argo-workflows/send-messages.yaml
  kebechet/base/argo-workflows/update_keb_installation.yaml
  kebechet/base/openshift-templates/kebechet-administrator.yaml
Labels: approved, size/M

#1329 update the prow ceph bucket cerds
  prow/overlays/cnv-prod/secrets.enc.yaml
Labels: size/L

#1333 restructure the monitoring to automate the monitoring
  monitoring/base/alertmanager.yaml
  monitoring/base/kustomization.yaml
  monitoring/base/prometheus-rules.yaml
  monitoring/base/prometheusrule.yaml
  monitoring/overlays/cnv-prod/alerting-rules.yaml
  monitoring/overlays/cnv-prod/github-receiver.yaml
  monitoring/overlays/cnv-prod/kustomization.yaml
  monitoring/overlays/cnv-prod/secrets.enc.yaml
Labels: approved, size/L

#1339 Increase memory for solvers to 2Gi
  solver/base/argo-workflows/solver-template.yaml
Labels: approved, size/XS

#1350 Reduce the time to live 15-30 mins for backend workflows
  adviser/base/openshift-templates/adviser.yaml
  adviser/base/openshift-templates/dependency-monkey.yaml
  adviser/base/openshift-templates/provenance-checker.yaml
  kebechet/base/openshift-templates/kebechet-administrator.yaml
  kebechet/base/openshift-templates/kebechet-run-url.yaml
  kebechet/base/openshift-templates/kebechet.yaml
  qeb-hwt-github-app/base/openshift-templates/qeb-hwt.yaml
Labels: approved, size/M

#1351 Sync the image that was missed in the automation
  advise-reporter/overlays/ocp4-stage/imagestreamtag.yaml
  advise-reporter/overlays/test/imagestreamtag.yaml
  amun/overlays/ocp4-stage/amun-api/imagestreamtag.yaml
  amun/overlays/ocp4-stage/amun-api/message-imagestream.yaml
  amun/overlays/test/imagestreamtag.yaml
  amun/overlays/test/message-imagestream.yaml
  core/overlays/ocp4-stage/common/imagestreamtags.yaml
  core/overlays/test/imagestreamtags.yaml
  core/overlays/zero-test/imagestreamtags.yaml
  graph-refresh/overlays/ocp4-stage/imagestreamtag.yaml
  management-api/overlays/test/imagestreamtag.yaml
  mi-scheduler/overlays/ocp4-stage/imagestreamtag.yaml
  revsolver/overlays/test/imagestreamtag.yaml
  solver/overlays/ocp4-stage/imagestreamtag.yaml
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
  user-api/overlays/test/imagestreamtag.yaml
Labels: approved, size/M

#1340 Raise solvers on exit code propagating a signal from operating system
  solver/base/argo-workflows/solver-template.yaml
Labels: approved, size/XS

#1355 set name of service port as metrics for the components
  amun/base/service.yaml
  amun/overlays/cnv-prod/amun-inspection/argo-namespace-install.yaml
  amun/overlays/cnv-prod/amun-inspection/argo-workflow-controller-metrics.yaml
  core/overlays/cnv-prod/backend-prod/argo-namespace-install.yaml
  core/overlays/cnv-prod/backend-prod/argo-workflow-controller-metrics.yaml
  core/overlays/cnv-prod/graph-prod/postgresql-metrics-exporter.yaml
  core/overlays/cnv-prod/middletier-prod/argo-namespace-install.yaml
  core/overlays/cnv-prod/middletier-prod/argo-workflow-controller-metrics.yaml
  investigator/overlays/cnv-prod/service.yaml
  management-api/base/service.yaml
  metrics-exporter/base/service.yaml
  user-api/base/service.yaml
Labels: approved, size/M

#1409 set the workflow template in the inspection namespace
  amun/overlays/ocp4-stage/amun-api/kustomization.yaml
Labels: approved, size/XS

#1410 Bump solvers to v1.9.0 in stage environment
  solver/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1431 Bump SLO-reporter to v0.14.3
  slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml
  slo-reporter/overlays/zero-prod-ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1436 include elyra aidevsecops to prow
  prow/overlays/cnv-prod/config.yaml
Labels: approved, size/XS
