Repository thoth-station/thoth-application, pull requests merged in 2021-12, with the labels that each got.

#2174 Update mi-scheduler to v1.7.2
  mi-scheduler/overlays/test/imagestreamtag.yaml
Labels: approved, size/XS

#2175 Adjust SLO-reporter CM
  slo-reporter/overlays/moc-prod-ocp4-stage/configmap.yaml
Labels: approved, size/S

#2177 set up the smaug thanos token for slo-reportor
  slo-reporter/overlays/moc-prod-ocp4-stage/secrets.enc.yaml
Labels: approved, size/L

#2176 Bump purge job to v0.1.0 in stage environment
  purge-job/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS, lgtm

#2180 Bump up the images based on the version update v2021.12.06
  adviser/overlays/aws-prod/imagestreamtag.yaml
  adviser/overlays/moc-prod/imagestreamtag.yaml
  slo-reporter/overlays/moc-prod-ocp4-stage/imagestreamtag.yaml
  slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml
  user-api/overlays/aws-prod/imagestreamtag.yaml
  user-api/overlays/moc-prod/imagestreamtag.yaml
  user-api/overlays/rick-test/imagestreamtag.yaml
Labels: size/S

#2189 Bump SLO reporter to v0.19.0
  slo-reporter/overlays/moc-prod-ocp4-stage/imagestreamtag.yaml
  slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2187 Add PyPI specific handlers for prescriptions-refresh
  prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-pypi.yaml
  prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh.yaml
Labels: approved, size/L

#2197 Patch prow instance with the s3 connection from smaug cluster
  prow/base/statusreconciler.yaml
  prow/base/tide.yaml
  prow/overlays/smaug/config.yaml
  prow/overlays/smaug/secrets.enc.yaml
Labels: approved, size/L

#2195 fixing field label with double apps
  core/overlays/moc-prod/frontend-prod/service-monitor.yaml
Labels: approved, size/XS

#2200 Patch moc prod ceph bucket in smaug cluster
  core/overlays/moc-prod/common/secrets.enc.yaml
Labels: approved, size/L

#2185 adding documentation of Thoth-alerting
  README.md
Labels: approved, size/S

#2192 Prescriptions refresh PyPI artifact size requires connection to the database
  prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-pypi.yaml
Labels: approved, size/S

#2194 Bump prescriptions-refresh-job to v0.5.0 in moc
  prescriptions-refresh-job/overlays/moc/imagestreamtag.yaml
Labels: approved, size/XS

#2199 Bump adviser to v0.49.0 in stage environment
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2202 Bump user-api to v0.29.1 in stage
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2203 Explicit pipeline configuration and prescritpions are disjoint
  adviser/base/argo-workflows/dependency-monkey.yaml
Labels: approved, size/XS

#2186 remove double apps from field label scraped in Thanos for user-API in Smaug
  grafana-dashboard/overlays/moc-prod/thoth-sli-slo.json
  slo-reporter/overlays/moc-prod-ocp4-stage/configmap.yaml
Labels: approved, size/XS

#2191 add keb-update step to base template
  kebechet/base/openshift-templates/kebechet.yaml
  kebechet/overlays/test/kebechet.yaml
  kebechet/overlays/test/kustomization.yaml
Labels: size/L

#2207 Revert the kebechet update installation due errors
  kebechet/base/openshift-templates/kebechet.yaml
Labels: size/XS

#2211 Patch the prescriptions refresh job for deployment
  prescriptions-refresh-job/base/kustomization.yaml
Labels: approved, size/XS

#2204 Bump package-extract to v1.3.0 in stage environment
  package-extract/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2212 Patch the smaug cluster postgresql pvc to default ceph based storage
  core/overlays/moc-prod/graph-prod/postgresql.yaml
Labels: approved, size/XS

#2213 Patch the smaug cluster kafka certs due to updates
  core/overlays/moc-prod/common/secrets.enc.yaml
Labels: approved, size/L

#2214 Freeze the db dump of smaug cluster
  graph-backup-job/overlays/moc-prod/cronjob.yaml
Labels: approved, size/XS

#2215 Freeze the data ingestion on balrog prod cluster
  cve-update/overlays/aws-prod/cronjob.yaml
  graph-backup-job/overlays/aws-prod/cronjob.yaml
  graph-refresh/overlays/aws-prod/cronjob.yaml
  package-update/overlays/aws-prod/cronjob.yaml
Labels: approved, size/S

#2217 adding uids, fixing json formatting, updating datasources and versioning
  grafana-dashboard/overlays/aws-prod/argocd.json
  grafana-dashboard/overlays/aws-prod/thoth-kafka-argo-metrics.json
  grafana-dashboard/overlays/aws-prod/thoth-knowledge-graph-content-metrics.json
  grafana-dashboard/overlays/aws-prod/thoth-postgresql-metrics.json
  grafana-dashboard/overlays/aws-prod/thoth-service-metrics.json
  grafana-dashboard/overlays/aws-prod/thoth-sli-slo.json
  grafana-dashboard/overlays/aws-prod/thoth-user-api-metrics.json
  grafana-dashboard/overlays/aws-prod/thoth-workflow-controllers-metrics.json
  grafana-dashboard/overlays/moc-prod/argocd.json
  grafana-dashboard/overlays/moc-prod/thoth-kafka-argo-metrics.json
  grafana-dashboard/overlays/moc-prod/thoth-knowledge-graph-content-metrics.json
  grafana-dashboard/overlays/moc-prod/thoth-postgresql-metrics.json
  grafana-dashboard/overlays/moc-prod/thoth-service-metrics.json
  grafana-dashboard/overlays/moc-prod/thoth-sli-slo.json
  grafana-dashboard/overlays/moc-prod/thoth-user-api-metrics.json
  grafana-dashboard/overlays/moc-prod/thoth-workflow-controllers-metrics.json
Labels: approved, size/XXL

#2210 setting up balrog alerting-rules
  monitoring/overlays/aws-prod/alerting-rules.yaml
  monitoring/overlays/aws-prod/kustomization.yaml
  monitoring/overlays/aws-prod/secret-generator.yaml
  monitoring/overlays/aws-prod/secrets.enc.yaml
Labels: approved, size/L

#2218 Bump up the images based on the version update v2021.12.20
  adviser/overlays/aws-prod/imagestreamtag.yaml
  adviser/overlays/moc-prod/imagestreamtag.yaml
  mi-scheduler/overlays/moc-prod/imagestreamtag.yaml
  mi-scheduler/overlays/ocp4-stage/imagestreamtag.yaml
  mi-scheduler/overlays/rick-test/imagestreamtag.yaml
  package-extract/overlays/aws-prod/imagestreamtag.yaml
  package-extract/overlays/moc-prod/imagestreamtag.yaml
  prescriptions-refresh-job/overlays/moc/imagestreamtag.yaml
  security-indicators/overlays/aws-prod/imagestreamtag.yaml
  security-indicators/overlays/moc-prod/imagestreamtag.yaml
  security-indicators/overlays/ocp4-stage/imagestreamtag.yaml
  user-api/overlays/aws-prod/imagestreamtag.yaml
  user-api/overlays/moc-prod/imagestreamtag.yaml
  user-api/overlays/rick-test/imagestreamtag.yaml
Labels: size/M, approved

#2224 Bump graph-sync-job to v0.10.18 in stage environment
  graph-sync/overlays/ocp4-stage/common/imagestreamtag.yaml
Labels: approved, size/XS

#2223 Enable the transfer-issue prow plugin
  prow/overlays/smaug/plugins.yaml
Labels: approved, size/XS

#2225 Update cronjob apiversion to batch/v1
  advise-reporter/base/cronjob.yaml
  advise-reporter/overlays/aws-prod/cronjob.yaml
  advise-reporter/overlays/moc-prod/cronjob.yaml
  advise-reporter/overlays/ocp4-stage/cronjob.yaml
  advise-reporter/overlays/test/cronjob.yaml
  cve-update/base/cronjob.yaml
  cve-update/overlays/aws-prod/cronjob.yaml
  cve-update/overlays/moc-prod/cronjob.yaml
  cve-update/overlays/ocp4-stage/cronjob.yaml
  cve-update/overlays/test/cronjob.yaml
  graph-backup-job/base/cronjob.yaml
  graph-backup-job/overlays/aws-prod/cronjob.yaml
  graph-backup-job/overlays/moc-prod/cronjob.yaml
  graph-backup-job/overlays/ocp4-stage/cronjob.yaml
  graph-backup-job/overlays/test/cronjob.yaml
  graph-metrics-exporter/base/cronjob.yaml
  graph-metrics-exporter/overlays/aws-prod/cronjob.yaml
  graph-metrics-exporter/overlays/moc-prod/cronjob.yaml
  graph-metrics-exporter/overlays/ocp4-stage/cronjob.yaml
  graph-metrics-exporter/overlays/test/cronjob.yaml
  graph-refresh/base/cronjob.yaml
  graph-refresh/overlays/aws-prod/cronjob.yaml
  graph-refresh/overlays/moc-prod/cronjob.yaml
  graph-refresh/overlays/ocp4-stage/cronjob.yaml
  graph-refresh/overlays/test/cronjob.yaml
  integration-tests/base/cronjob.yaml
  integration-tests/overlays/moc-prod-ocp4-stage/cronjob.yaml
  integration-tests/overlays/ocp4-stage/cronjob.yaml
  integration-tests/overlays/test/cronjob.yaml
  kebechet/overlays/bot/kebechet-aicoe-cronjob.yaml
  kebechet/overlays/bot/kebechet-thoth-cronjob.yaml
  mi-scheduler/base/cronjob.yaml
  mi-scheduler/overlays/moc-prod/cronjob.yaml
  mi-scheduler/overlays/ocp4-stage/cronjob.yaml
  mi-scheduler/overlays/rick-test/cronjob.yaml
  mi-scheduler/overlays/test/cronjob.yaml
  nepthys/base/cronjob.yaml
  package-releases/base/cronjob.yaml
  package-releases/overlays/aws-prod/cronjob.yaml
  package-releases/overlays/moc-prod/cronjob.yaml
  package-releases/overlays/ocp4-stage/cronjob.yaml
  package-releases/overlays/test/cronjob.yaml
  package-update/base/cronjob.yaml
  package-update/overlays/aws-prod/cronjob.yaml
  package-update/overlays/moc-prod/cronjob.yaml
  package-update/overlays/ocp4-stage/cronjob.yaml
  package-update/overlays/test/cronjob.yaml
  prow/base/branchprotector.yaml
  prow/overlays/smaug/unsuspend_branchprotector.yaml
  pulp-pypi-sync-job/base/cronjob.yaml
  pulp-pypi-sync-job/overlays/moc/cronjob.yaml
  pulp-pypi-sync-job/overlays/test/cronjob.yaml
  sefkhet-abwy/overlays/bot/thoth-friday-scrum-cronjob.yaml
  sefkhet-abwy/overlays/bot/thoth-scrum-cronjob.yaml
  sefkhet-abwy/overlays/moc/new-label-normalizer.yaml
  slo-reporter/base/cronjob.yaml
  slo-reporter/overlays/moc-prod-ocp4-stage/cronjob.yaml
  slo-reporter/overlays/ocp4-stage/cronjob.yaml
  slo-reporter/overlays/test/cronjob.yaml
Labels: approved, size/L

#2227 Increase number of seconds allowed package-extract to run
  package-extract/base/argo-workflows/package-extract.yaml
Labels: approved, size/XS

#2222 Bump user-api to v0.30.0 in stage environment
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2228 Increase memory requirements for package-extract
  package-extract/base/argo-workflows/package-extract.yaml
Labels: approved, size/XS

#2231 Bump up version for managment-api
  management-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2233 Include investigator required env vars for the doc builds
  nepthys/base/cronjob.yaml
Labels: approved, size/XS

#2234 Bump up the resources for nepthys
  nepthys/base/cronjob.yaml
Labels: approved, size/XS

#2236 Bump up the images based on the storgae v0.62.1 update
  core/overlays/ocp4-stage/common/imagestreamtags.yaml
  cve-update/overlays/ocp4-stage/imagestreamtag.yaml
  graph-backup-job/overlays/ocp4-stage/imagestreamtag.yaml
  graph-metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
  graph-refresh/overlays/ocp4-stage/imagestreamtag.yaml
  metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
  package-releases/overlays/ocp4-stage/imagestreamtag.yaml
  package-releases/overlays/test/imagestreamtag.yaml
Labels: approved, size/S
