Repository thoth-station/thoth-application, pull requests merged in 2021-09, with the labels that each got.

#1938 use GitHub app authentication present in secrets
  adviser/base/argo-workflows/kebechet-run-results.yaml
  adviser/base/openshift-templates/adviser.yaml
Labels: approved, size/S

#1937 Enable CVE update job in stage
  cve-update/overlays/ocp4-stage/cronjob.yaml
Labels: approved, size/XS

#1931 Enable ingesting Fedora:34+Python 3.9 data in stage environment
  core/overlays/ocp4-stage/common/configmaps.yaml
Labels: approved, size/XS

#1927 Add manifests needed for prescriptions-refresh
  prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-gh.yaml
  prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh.yaml
  prescriptions-refresh-job/base/imagestream.yaml
  prescriptions-refresh-job/base/kustomization.yaml
  prescriptions-refresh-job/overlays/ocp4-stage/cronworkflow.yaml
  prescriptions-refresh-job/overlays/ocp4-stage/imagestreamtag.yaml
  prescriptions-refresh-job/overlays/ocp4-stage/job-generate-name.yaml
  prescriptions-refresh-job/overlays/ocp4-stage/kustomization.yaml
  prescriptions-refresh-job/overlays/ocp4-stage/put-into-middletier-namespace.yaml
  prescriptions-refresh-job/overlays/ocp4-stage/thoth-notification.yaml
  prescriptions-refresh-job/overlays/test/cronworkflow.yaml
  prescriptions-refresh-job/overlays/test/imagestreamtag.yaml
  prescriptions-refresh-job/overlays/test/job-generate-name.yaml
  prescriptions-refresh-job/overlays/test/kustomization.yaml
  prescriptions-refresh-job/overlays/test/thoth-notification.yaml
  prescriptions-refresh-job/overlays/zero-prod/cronworkflow.yaml
  prescriptions-refresh-job/overlays/zero-prod/imagestreamtag.yaml
  prescriptions-refresh-job/overlays/zero-prod/job-generate-name.yaml
  prescriptions-refresh-job/overlays/zero-prod/kustomization.yaml
  prescriptions-refresh-job/overlays/zero-prod/put-into-middletier-namespace.yaml
  prescriptions-refresh-job/overlays/zero-prod/thoth-notification.yaml
Labels: size/XL

#1941 Fix panels colours behaviour in Grafana dashboard
  grafana-dashboard/overlays/cnv-prod/thoth-sli-slo.json
Labels: approved

#1944 update the prow ceph bucket for the instance
  prow/base/statusreconciler.yaml
  prow/base/tide.yaml
  prow/overlays/smaug/config.yaml
  prow/overlays/smaug/secrets.enc.yaml
Labels: size/L

#1946 Exclude branches created for prescription updates
  prow/overlays/smaug/config.yaml
Labels: approved, size/XS

#1904 Increase activeDeadlineSeconds for package-releases
  package-releases/base/cronjob.yaml
Labels: approved, size/XS

#1951 Turn off JSON logging in test environment
  core/overlays/zero-test/configmaps.yaml
Labels: approved, size/XS

#1952 Turn off JSON logging in stage environment
  core/overlays/ocp4-stage/common/configmaps.yaml
Labels: approved, size/XS

#1954 Unsuspend cronjobs
  mi-scheduler/overlays/test/cronjob.yaml
Labels: approved, size/XS

#1955 Add tide to AICoE tutorials repo
  prow/overlays/smaug/config.yaml
Labels: approved, size/XS

#1953 Update cve-update job to v0.4.0 in stage environment
  cve-update/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1956 Bump investigator to v0.15.0 in stage environment
  core/overlays/ocp4-stage/common/imagestreamtags.yaml
Labels: approved, size/XS

#1958 Bump up the version of thoth station for v2021.09.13 release
  advise-reporter/overlays/cnv-prod/imagestreamtag.yaml
  advise-reporter/overlays/ocp4-stage/imagestreamtag.yaml
  adviser/overlays/cnv-prod/imagestreamtag.yaml
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
  adviser/overlays/test/imagestreamtag.yaml
  core/overlays/cnv-prod/common/imagestreamtags.yaml
  core/overlays/ocp4-stage/common/imagestreamtags.yaml
  core/overlays/test/imagestreamtags.yaml
  core/overlays/zero-test/imagestreamtags.yaml
  cve-update/overlays/cnv-prod/imagestreamtag.yaml
  cve-update/overlays/test/imagestreamtag.yaml
  graph-backup-job/overlays/cnv-prod/imagestreamtag.yaml
  graph-backup-job/overlays/ocp4-stage/imagestreamtag.yaml
  graph-backup-job/overlays/test/imagestreamtag.yaml
  graph-metrics-exporter/overlays/cnv-prod/imagestreamtag.yaml
  graph-metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
  graph-metrics-exporter/overlays/test/imagestreamtag.yaml
  graph-refresh/overlays/cnv-prod/imagestreamtag.yaml
  graph-refresh/overlays/ocp4-stage/imagestreamtag.yaml
  graph-refresh/overlays/test/imagestreamtag.yaml
  graph-sync/overlays/cnv-prod/imagestreamtag.yaml
  graph-sync/overlays/ocp4-stage/imagestreamtag.yaml
  graph-sync/overlays/test/imagestreamtag.yaml
  management-api/overlays/cnv-prod/imagestreamtag.yaml
  management-api/overlays/ocp4-stage/imagestreamtag.yaml
  management-api/overlays/test/imagestreamtag.yaml
  metrics-exporter/overlays/cnv-prod/imagestreamtag.yaml
  metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
  metrics-exporter/overlays/test/imagestreamtag.yaml
  mi-scheduler/overlays/cnv-prod/imagestreamtag.yaml
  mi-scheduler/overlays/ocp4-stage/imagestreamtag.yaml
  mi-scheduler/overlays/test/imagestreamtag.yaml
  mi-scheduler/overlays/zero-test/imagestreamtag.yaml
  package-releases/overlays/cnv-prod/imagestreamtag.yaml
  package-releases/overlays/ocp4-stage/imagestreamtag.yaml
  package-releases/overlays/test/imagestreamtag.yaml
  package-update/overlays/cnv-prod/imagestreamtag.yaml
  package-update/overlays/ocp4-stage/imagestreamtag.yaml
  package-update/overlays/test/imagestreamtag.yaml
  prescriptions-refresh-job/overlays/ocp4-stage/imagestreamtag.yaml
  prescriptions-refresh-job/overlays/test/imagestreamtag.yaml
  prescriptions-refresh-job/overlays/zero-prod/imagestreamtag.yaml
  revsolver/overlays/cnv-prod/imagestreamtag.yaml
  revsolver/overlays/ocp4-stage/imagestreamtag.yaml
  revsolver/overlays/test/imagestreamtag.yaml
  slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml
  slo-reporter/overlays/test/imagestreamtag.yaml
  slo-reporter/overlays/zero-prod-ocp4-stage/imagestreamtag.yaml
  user-api/overlays/cnv-prod/imagestreamtag.yaml
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
  user-api/overlays/test/imagestreamtag.yaml
Labels: approved, size/L

#1950 Start using prescriptions from pickle file
  adviser/base/argo-workflows/advise.yaml
  adviser/base/argo-workflows/dependency-monkey.yaml
  adviser/base/imagestream.yaml
  adviser/overlays/cnv-prod/imagestreamtag.yaml
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
  adviser/overlays/test/imagestreamtag.yaml
Labels: size/M, approved

#1957 Migrate chatbot to moc overlays for new cluster deployment
  sefkhet-abwy-chatbot/overlays/cnv-prod/route53.enc.yaml
  sefkhet-abwy-chatbot/overlays/moc/imagestreamtag.yaml
  sefkhet-abwy-chatbot/overlays/moc/kustomization.yaml
  sefkhet-abwy-chatbot/overlays/moc/route53.enc.yaml
  sefkhet-abwy-chatbot/overlays/moc/secret-generator.yaml
  sefkhet-abwy-chatbot/overlays/moc/secrets.enc.yaml
Labels: approved, size/L

#1962 Setup milestone 2021.09.27 for new sprint
  prow/overlays/smaug/plugins.yaml
Labels: approved, size/XS

#1966 update Keb to latest minor version
  kebechet/overlays/cnv-prod/imagestreamtag.yaml
  kebechet/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1970 Bump adviser to v0.43.0 in stage environment
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1964 add sesheta-srcops secrets
  sesheta-srcops/overlays/smaug/configmaps.yaml
  sesheta-srcops/overlays/smaug/kustomization.yaml
  sesheta-srcops/overlays/smaug/secret-generator.yaml
  sesheta-srcops/overlays/smaug/secrets.enc.yaml
Labels: approved, size/L

#1973 convert zero-test environment to rick-test
  core/overlays/rick-test/argo-deployments.yaml
  core/overlays/rick-test/argo-imagestreams.yaml
  core/overlays/rick-test/argo-management.yaml
  core/overlays/rick-test/argo-role.yaml
  core/overlays/rick-test/argo-ui-controller.yaml
  core/overlays/rick-test/argo-workflow-controller.yaml
  core/overlays/rick-test/argo-workflows/send-message.yaml
  core/overlays/rick-test/argo-workflows/send-messages.yaml
  core/overlays/rick-test/buildConfig.yaml
  core/overlays/rick-test/configmaps.yaml
  core/overlays/rick-test/imagestreamtags.yaml
  core/overlays/rick-test/job-generate-name.yaml
  core/overlays/rick-test/kustomization.yaml
  core/overlays/rick-test/pgbouncer.yaml
  core/overlays/rick-test/postgresql-metrics-exporter.yaml
  core/overlays/rick-test/postgresql.yaml
  core/overlays/rick-test/secret-generator.yaml
  core/overlays/rick-test/secrets.enc.yaml
  core/overlays/rick-test/thoth-notification.yaml
  mi-scheduler/overlays/rick-test/buildConfig.yaml
  mi-scheduler/overlays/rick-test/cronjob.yaml
  mi-scheduler/overlays/rick-test/imagestreamtag.yaml
  mi-scheduler/overlays/rick-test/job-generate-name.yaml
  mi-scheduler/overlays/rick-test/kustomization.yaml
  mi-scheduler/overlays/rick-test/role-binding.yaml
  mi-scheduler/overlays/rick-test/secret-generator.yaml
  mi-scheduler/overlays/rick-test/secrets.enc.yaml
  mi-scheduler/overlays/rick-test/thoth-notification.yaml
Labels: approved, size/S

#1976 Bump adviser to v0.44.0 in stage environment
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1977 Bump up the graph-backup-job to version v0.8.9
  graph-backup-job/overlays/cnv-prod/imagestreamtag.yaml
  graph-backup-job/overlays/ocp4-stage/imagestreamtag.yaml
  graph-backup-job/overlays/test/imagestreamtag.yaml
Labels: approved, size/XS

#1978 Propagate information about authenticated advise to adviser
  adviser/base/argo-workflows/advise.yaml
  adviser/base/openshift-templates/adviser.yaml
Labels: approved, size/XS

#1979 Add Pep's key to sops
  .sops.yaml
  amun/.sops.yaml
  management-api/.sops.yaml
  mi-scheduler/.sops.yaml
  sefkhet-abwy-chatbot/.sops.yaml
  user-api/.sops.yaml
Labels: approved, size/S

#1982 update keb to latest patch
  kebechet/overlays/cnv-prod/imagestreamtag.yaml
  kebechet/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1981 Bump metrics-exporter to v0.18.3 in stage environment
  metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1980 Bump graph-refresh in stage to v0.3.15
  graph-refresh/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1984 migrate triage-party to new cluster
  sefkhet-abwy/overlays/moc/secrets.enc.yaml
  sefkhet-abwy/overlays/ocp/secrets.enc.yaml
  triage-party/overlays/moc/config.yaml
  triage-party/overlays/moc/imagestreamtags.yaml
  triage-party/overlays/moc/kustomization.yaml
  triage-party/overlays/moc/pcache.yaml
  triage-party/overlays/moc/route.yaml
  triage-party/overlays/moc/secret-generator.yaml
  triage-party/overlays/moc/secrets.enc.yaml
  triage-party/overlays/zero-prod/secrets.enc.yaml
Labels: approved, size/XL

#1991 Bump package-release in stage to v0.11.3
  package-releases/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1993 setup prow on the data-driven-development repo
  prow/overlays/smaug/config.yaml
Labels: approved, size/XS
