Repository thoth-station/thoth-application, pull requests merged in 2021-02, with the labels that each got.

#826 Update/Add dashboards
  grafana-dashboard/overlays/cnv-prod/thoth-knowledge-graph-content-metrics.json
  grafana-dashboard/overlays/cnv-prod/thoth-postgresql-metrics.json
  grafana-dashboard/overlays/cnv-prod/thoth-service-metrics.json
Labels: approved, sig/devops, size/XXL

#824 Bump graph-backup-job stage to v0.8.0 to have metrics
  graph-backup-job/overlays/ocp4-stage/imagestreamtag.yaml
  graph-backup-job/overlays/stage/imagestreamtag.yaml
Labels: approved, sig/devops, size/XS

#829 Make pre-commit happy
  grafana-dashboard/overlays/cnv-prod/thoth-service-metrics.json
Labels: approved, size/XS

#828 Bump workflow helpers to v0.4.1
  core/overlays/ocp4-stage/common/imagestreamtags.yaml
  core/overlays/stage/common/imagestreamtags.yaml
Labels: approved, size/XS

#804 use a postsync hook job for deployment trigger
  user-api/overlays/test/deployment-trigger.yaml
Labels: approved, size/S

#833 Bump graph-sync to v0.10.0 in stage
  graph-sync/overlays/ocp4-stage/imagestreamtag.yaml
  graph-sync/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#836 Provide APP_SCRIPT envornmnet variable to run the application
  package-extract/base/argo-workflows/package-extract.yaml
Labels: size/XS

#838 Bump metrics-exporter stage to v0.10.2
  metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
  metrics-exporter/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#832 Bump Kebechet to v1.2.4
  kebechet/overlays/ocp4-stage/imagestreamtag.yaml
  kebechet/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#841 Bump SLO-reporter to v0.8.3 in stage and prod
  slo-reporter/overlays/cnv-prod/imagestreamtag.yaml
  slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml
  slo-reporter/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#839 Bump Management API in stage
  management-api/overlays/ocp4-stage/imagestreamtag.yaml
  management-api/overlays/stage/imagestreamtag.yaml
Labels: approved, sig/devops, size/XS

#835 Bump adviser to v0.23.0 in stage
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
  adviser/overlays/stage/imagestreamtag.yaml
Labels: approved, sig/devops, size/XS

#844 Bump advise-reporter to have all metrics
  advise-reporter/overlays/ocp4-stage/imagestreamtag.yaml
  advise-reporter/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#837 Create a document documenting the release procedure
  thoth_release_procedure.md
Labels: approved, size/S

#823 Extend provenance checker workflow with new steps
  adviser/base/argo-workflows/parse-provenance-checker-output.yaml
  adviser/base/kustomization.yaml
  adviser/base/openshift-templates/provenance-checker.yaml
  core/overlays/cnv-prod/common/imagestreamtags.yaml
  core/overlays/ocp4-stage/common/imagestreamtags.yaml
  core/overlays/stage/common/imagestreamtags.yaml
Labels: approved, sig/devops, sig/docs, sig/user-experience, size/M

#845 Bump package-extract to v1.1.2 in stage
  package-extract/overlays/ocp4-stage/imagestreamtag.yaml
  package-extract/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#846 bump up the latest version of graph-refresh
  graph-refresh/overlays/ocp4-stage/imagestreamtag.yaml
  graph-refresh/overlays/stage/imagestreamtag.yaml
  graph-refresh/overlays/test/imagestreamtag.yaml
Labels: approved, size/XS

#840 Bump User API to v0.17.0 in stage environment
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
  user-api/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#850 Bump graph-sync to v0.10.1 to address solver syncing issues
  graph-sync/overlays/ocp4-stage/imagestreamtag.yaml
  graph-sync/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#852 bump the version of graph-sycn in stage
  advise-reporter/overlays/test/imagestreamtag.yaml
  graph-sync/overlays/ocp4-stage/imagestreamtag.yaml
  graph-sync/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#853 upgrade: bump the version of messaging in stage
  core/overlays/ocp4-stage/common/imagestreamtags.yaml
  core/overlays/stage/common/imagestreamtags.yaml
Labels: approved, size/XS

#857 remove all the obsolete prow overlays
  prow/overlays/aicoe-infra-prod/config.yaml
  prow/overlays/aicoe-infra-prod/kustomization.yaml
  prow/overlays/aicoe-infra-prod/plugins.yaml
  prow/overlays/gke/kustomization.yaml
  prow/overlays/thoth-station/config.yaml
  prow/overlays/thoth-station/kustomization.yaml
  prow/overlays/thoth-station/plugins.yaml
Labels: approved, sig/devops, size/XL

#858 add keb metadata for internal trigger context
  kebechet/base/argo-workflows/kebechet-run-url.yaml
  kebechet/base/openshift-templates/kebechet-run-url.yaml
Labels: approved, size/S

#849 Document Thoth's S2I and solver procedure
  thoth_s2i_procedure.md
Labels: approved, area/documentation, kind/documentation, size/M

#860 upgrade prod database size
  core/overlays/cnv-prod/graph-prod/postgresql.yaml
Labels: approved, size/XS

#866 debug argo worflow limits with investigator limits
  investigator/overlays/ocp4-stage/deploymentconfig.yaml
  investigator/overlays/ocp4-stage/kustomization.yaml
Labels: approved, size/S

#868 Debug amun api
  amun/overlays/test/deploymentconfig.yaml
  amun/overlays/test/inspection-with-cpu-workflow.yaml
  amun/overlays/test/inspection-workflow.yaml
  amun/overlays/test/kustomization.yaml
Labels: approved, size/XL

#873 Bump adviser to v0.24.1 in stage environments
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
  adviser/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#875 Bump User API to v0.18.0 in stage
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
  user-api/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#872 Update package-update-job to v0.8.7 in stage
  package-update/overlays/ocp4-stage/imagestreamtag.yaml
  package-update/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#877 Update cronjob for the components with variable changes
  package-releases/overlays/ocp4-stage/cronjob.yaml
  package-update/overlays/ocp4-stage/cronjob.yaml
Labels: approved, size/L

#878 Debug the workflow limit with graph-refresh job
  core/overlays/ocp4-stage/common/configmaps.yaml
  graph-refresh/overlays/ocp4-stage/cronjob.yaml
Labels: approved, size/XS

#880 revert debug change for the workflow limit test with graph-refresh job
  core/overlays/ocp4-stage/common/configmaps.yaml
  graph-refresh/overlays/ocp4-stage/cronjob.yaml
Labels: approved, size/XS

#881 Bump metrics-exporter to v0.11.0
  metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
  metrics-exporter/overlays/prod/imagestreamtag.yaml
  metrics-exporter/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#867 add kustomize-build presubmit job to op1st/apps repo ʕʘ̅͜ʘ̅ʔ
  prow/overlays/cnv-prod/config.yaml
Labels: approved, size/M

#882 Revert "add kustomize-build presubmit job to op1st/apps repo ʕʘ̅͜ʘ̅ʔ"
  prow/overlays/cnv-prod/config.yaml
Labels: approved, size/M

#886 using latest release of integration-tests
  prow/overlays/cnv-prod/config.yaml
Labels: approved, lgtm, sig/devops, size/XS

#888 Fix path to container image analysis results
  package-extract/base/argo-workflows/package-extract.yaml
Labels: approved, size/XS

#879 Use sendgrid in production for SLO-reporter
  slo-reporter/overlays/cnv-prod/cronjob.yaml
  slo-reporter/overlays/cnv-prod/imagestreamtag.yaml
  slo-reporter/overlays/cnv-prod/secrets.enc.yaml
Labels: approved, size/L

#890 use right datasource for cnv grafana dashboard
  grafana-dashboard/overlays/cnv-prod/thoth-knowledge-graph-content-metrics.json
  grafana-dashboard/overlays/cnv-prod/thoth-postgresql-metrics.json
  grafana-dashboard/overlays/cnv-prod/thoth-service-metrics.json
Labels: approved, size/L

#891 update slo-reporter secrets for cnv moc cluster
  slo-reporter/overlays/cnv-prod/secrets.enc.yaml
Labels: approved, size/L

#892 Adjust parameters in CM
  slo-reporter/overlays/cnv-prod/configmap.yaml
Labels: approved, size/XS

#893 test domain to send email
  slo-reporter/overlays/cnv-prod/configmap.yaml
Labels: approved, size/XS

#895 Bump User API to v0.19.0 in stage environments
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
  user-api/overlays/stage/imagestreamtag.yaml
Labels: approved, size/XS

#897 use an imagestreamtag for integration-tests
  prow/overlays/cnv-prod/config.yaml
  prow/overlays/cnv-prod/imagestreamtags.yaml
  prow/overlays/cnv-prod/label-sync-cronjob.yaml
Labels: approved, lgtm, size/M

#894 Add integration tests
  integration-tests/base/configmap.yaml
  integration-tests/base/cronjob.yaml
  integration-tests/base/imagestream.yaml
  integration-tests/base/kustomization.yaml
  integration-tests/overlays/ocp4-stage/configmap.yaml
  integration-tests/overlays/ocp4-stage/imagestreamtag.yaml
  integration-tests/overlays/ocp4-stage/kustomization.yaml
  integration-tests/overlays/ocp4-stage/put-into-infra-namespace.yaml
  integration-tests/overlays/ocp4-stage/thoth-notification.yaml
  integration-tests/overlays/test/configmap.yaml
  integration-tests/overlays/test/imagestreamtag.yaml
  integration-tests/overlays/test/kustomization.yaml
  integration-tests/overlays/test/thoth-notification.yaml
Labels: approved, size/L

#899 update integration test setup manifests
  integration-tests/base/cronjob.yaml
  integration-tests/base/kustomization.yaml
  integration-tests/overlays/ocp4-stage/cronjob.yaml
  integration-tests/overlays/ocp4-stage/kustomization.yaml
  integration-tests/overlays/ocp4-stage/put-into-infra-namespace.yaml
  integration-tests/overlays/ocp4-stage/secret-generator.yaml
  integration-tests/overlays/ocp4-stage/secrets.enc.yaml
  integration-tests/overlays/test/cronjob.yaml
  integration-tests/overlays/test/kustomization.yaml
  integration-tests/overlays/test/secret-generator.yaml
  integration-tests/overlays/test/secrets.enc.yaml
  integration-tests/overlays/test/thoth-notification.yaml
Labels: approved, size/L

#900 Bump integration-tests to use s2i application
  integration-tests/overlays/ocp4-stage/imagestreamtag.yaml
  integration-tests/overlays/test/imagestreamtag.yaml
Labels: approved, size/XS

#898 switch on all solver in the stage env
  core/overlays/ocp4-stage/common/configmaps.yaml
Labels: approved, size/XS

#904 Bump of version for prod release 15.02.2021
  advise-reporter/overlays/cnv-prod/imagestreamtag.yaml
  adviser/overlays/cnv-prod/imagestreamtag.yaml
  core/overlays/cnv-prod/common/imagestreamtags.yaml
  graph-refresh/overlays/cnv-prod/imagestreamtag.yaml
  graph-sync/overlays/cnv-prod/imagestreamtag.yaml
  kebechet/overlays/cnv-prod/imagestreamtag.yaml
  management-api/overlays/cnv-prod/imagestreamtag.yaml
  metrics-exporter/overlays/cnv-prod/imagestreamtag.yaml
  package-extract/overlays/cnv-prod/imagestreamtag.yaml
  package-update/overlays/cnv-prod/imagestreamtag.yaml
  user-api/overlays/cnv-prod/imagestreamtag.yaml
Labels: approved, size/S

#913 User API does not use Amun
  user-api/base/configmap.yaml
  user-api/base/deploymentconfig.yaml
Labels: approved, size/XS

#910 Rename environment variable for sending integration test reports
  integration-tests/base/configmap.yaml
  integration-tests/base/cronjob.yaml
Labels: approved, lgtm, size/XS

#917 Introduce kafka env var update all across the envs
  core/base/argo-workflows/send-message.yaml
  core/base/argo-workflows/send-messages.yaml
  graph-refresh/base/cronjob.yaml
  graph-refresh/overlays/ocp4-stage/cronjob.yaml
  graph-refresh/overlays/test/cronjob.yaml
  investigator/overlays/ocp4-stage/deploymentconfig.yaml
  investigator/overlays/ocp4-stage/kustomization.yaml
  package-releases/base/cronjob.yaml
  package-releases/overlays/ocp4-stage/cronjob.yaml
  package-releases/overlays/test/cronjob.yaml
  package-update/base/cronjob.yaml
  package-update/overlays/ocp4-stage/cronjob.yaml
  package-update/overlays/test/cronjob.yaml
Labels: approved, size/XL

#918 Enable preparing environment in adviser container
  adviser/base/argo-workflows/advise.yaml
  adviser/base/argo-workflows/dependency-monkey.yaml
  adviser/base/argo-workflows/provenance-check.yaml
Labels: approved, lgtm, size/M

#919 Use prepared files in adviser container runs
  adviser/overlays/test/argo-workflows/advise.yaml
  adviser/overlays/test/argo-workflows/dependency-monkey.yaml
  adviser/overlays/test/argo-workflows/provenance-check.yaml
  adviser/overlays/test/kustomization.yaml
Labels: approved, size/XL

#903 all the roles and rolebindungs to use the test-pods namespace
  prow/overlays/cnv-prod-test-prods/crier_rbac.yaml
  prow/overlays/cnv-prod-test-prods/deck_rbac.yaml
  prow/overlays/cnv-prod-test-prods/kustomization.yaml
  prow/overlays/cnv-prod-test-prods/sinker_rbac.yaml
Labels: approved, lgtm, size/M

#909 Include sprint cycle release template
  .github/ISSUE_TEMPLATE/sprint-prod-release.md
Labels: approved, size/S

#922 set amun inspection time-to-live for 15min
  amun/overlays/cnv-prod/amun-inspection/configmaps.yaml
  amun/overlays/ocp4-stage/amun-inspection/configmaps.yaml
Labels: approved, deployment_name/moc, lgtm, sig/devops, size/XS

#923 Use SMTP TLS in prod
  slo-reporter/base/cronjob.yaml
  slo-reporter/overlays/cnv-prod/configmap.yaml
  slo-reporter/overlays/cnv-prod/cronjob.yaml
  slo-reporter/overlays/cnv-prod/imagestreamtag.yaml
  slo-reporter/overlays/cnv-prod/secrets.enc.yaml
Labels: approved, deployment_name/moc, sig/devops, sig/slo, size/M

#926 Re-encrypt secret of moc environment for thoth components
  .sops.yaml
  amun/overlays/cnv-prod/amun-api/kustomization.yaml
  amun/overlays/cnv-prod/amun-api/secrets.enc.yaml
  core/overlays/cnv-prod/common/kustomization.yaml
  core/overlays/cnv-prod/common/secrets.enc.yaml
  core/overlays/cnv-prod/infra-prod/kustomization.yaml
  core/overlays/cnv-prod/infra-prod/secrets.enc.yaml
  kebechet/overlays/cnv-prod/secrets.enc.yaml
  management-api/overlays/cnv-prod/kustomization.yaml
  management-api/overlays/cnv-prod/route.enc.yaml
  qeb-hwt-github-app/overlays/cnv-prod/secrets.enc.yaml
  sefkhet-abwy/overlays/cnv-prod/secrets.enc.yaml
  slo-reporter/overlays/cnv-prod/secrets.enc.yaml
  user-api/overlays/cnv-prod/khemenu.route.enc.yaml
  user-api/overlays/cnv-prod/kustomization.yaml
  user-api/overlays/cnv-prod/route.enc.yaml
Labels: approved, sig/devops, size/XXL

#927 re-encrypt amun certs secrets for moc environment
  amun/overlays/cnv-prod/amun-api/route.enc.yaml
Labels: approved, size/L

#928 secrets are base64 encoded
  slo-reporter/overlays/cnv-prod/secrets.enc.yaml
Labels: approved, size/L

#925 Enable integration tests
  integration-tests/overlays/ocp4-stage/cronjob.yaml
  integration-tests/overlays/test/cronjob.yaml
Labels: approved, size/XS

#929 smtp server information to be picked from configmap
  slo-reporter/overlays/cnv-prod/configmap.yaml
  slo-reporter/overlays/cnv-prod/cronjob.yaml
Labels: approved, size/XS

#931 Bump integration tests to v0.5.0
  integration-tests/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#933 Bump integration-tests to v0.6.0 in stage environment
  integration-tests/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#786 add to inspection to send messages upon completion
  amun/base/argo-workflows/create-inspection-complete-message.yaml
  amun/base/argo-workflows/send-messages.yaml
  amun/base/imagestream.yaml
  amun/base/kustomization.yaml
  amun/overlays/ocp4-stage/amun-api/imagestreamtag.yaml
  amun/overlays/ocp4-stage/amun-api/kustomization.yaml
  amun/overlays/ocp4-stage/amun-api/openshift-templates/inspection-with-cpu-workflow.yaml
  amun/overlays/ocp4-stage/amun-api/openshift-templates/inspection-workflow.yaml
  amun/overlays/test/imagestreamtag.yaml
  amun/overlays/test/kustomization.yaml
  amun/overlays/test/openshift-templates/inspection-with-cpu-workflow.yaml
  amun/overlays/test/openshift-templates/inspection-workflow.yaml
Labels: approved, size/XL

#942 Correct labels to use templating
  grafana-dashboard/overlays/cnv-prod/thoth-sli-slo.json
Labels: approved, size/XS

#936 Increase resources for Amun API
  amun/base/deploymentconfig.yaml
Labels: approved, size/XS

#937 Bump adviser to v0.25.1 in stage environment
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#943 Enable generating report in integration-tests
  integration-tests/base/configmap.yaml
  integration-tests/base/cronjob.yaml
Labels: approved, size/XS

#948 Select only relevant integration-tests in cnv-prod
  integration-tests/overlays/cnv-prod-ocp4-stage/README.rst
  integration-tests/overlays/cnv-prod-ocp4-stage/configmap.yaml
  integration-tests/overlays/cnv-prod-ocp4-stage/cronjob.yaml
  integration-tests/overlays/cnv-prod-ocp4-stage/imagestreamtag.yaml
  integration-tests/overlays/cnv-prod-ocp4-stage/job-generate-name.yaml
  integration-tests/overlays/cnv-prod-ocp4-stage/kustomization.yaml
  integration-tests/overlays/cnv-prod-ocp4-stage/secret-generator.yaml
  integration-tests/overlays/cnv-prod-ocp4-stage/secrets.enc.yaml
  integration-tests/overlays/cnv-prod-ocp4-stage/thoth-notification.yaml
Labels: approved, size/L

#935 Adjust command for integration-tests in Prow
  prow/overlays/cnv-prod/config.yaml
Labels: approved, size/S

#951 Provide Amun inspection namespace to management-api
  management-api/base/deploymentconfig.yaml
Labels: approved, size/XS

#953 Bump management-api to v0.14.0 in stage environment
  management-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#952 Bump integration tests to v0.7.0
  integration-tests/overlays/cnv-prod-ocp4-stage/imagestreamtag.yaml
  integration-tests/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#947 Do not run integration tests requiring middletier namespace
  integration-tests/base/configmap.yaml
  integration-tests/base/cronjob.yaml
  integration-tests/overlays/ocp4-stage/configmap.yaml
Labels: approved, size/XS

#954 Bump management-api to v0.14.0 in prod
  management-api/overlays/cnv-prod/imagestreamtag.yaml
  management-api/overlays/prod/imagestreamtag.yaml
Labels: approved, size/XS

#959 Bump user-api to v0.19.3 in stage
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#960 Bump user-api to v0.19.3 in prod
  user-api/overlays/cnv-prod/imagestreamtag.yaml
Labels: approved, size/XS

#963 Bump version v0.25.1 for adviser prod
  adviser/overlays/cnv-prod/imagestreamtag.yaml
Labels: approved, deployment_name/moc, size/XS

#964 enable learning on the prod server
  graph-refresh/overlays/cnv-prod/cronjob.yaml
Labels: approved, deployment_name/moc, size/XS

#965 learn ubi8-py38 stack on prod cluster
  core/overlays/cnv-prod/common/configmaps.yaml
Labels: approved, deployment_name/moc, size/XS

#967 Run integration tests that use backend namespace
  integration-tests/overlays/cnv-prod-ocp4-stage/configmap.yaml
Labels: approved, size/XS

#966 Update the cnv prod argocd url with the latest
  advise-reporter/overlays/cnv-prod/thoth-notification.yaml
  adviser/overlays/cnv-prod/thoth-notification.yaml
  buildlog-parser/overlays/cnv-prod/thoth-notification.yaml
  chat-notification/overlays/cnv-prod/thoth-notification.yaml
  core/overlays/cnv-prod/backend-prod/thoth-notification.yaml
  core/overlays/cnv-prod/frontend-prod/thoth-notification.yaml
  core/overlays/cnv-prod/graph-prod/thoth-notification.yaml
  core/overlays/cnv-prod/infra-prod/thoth-notification.yaml
  core/overlays/cnv-prod/middletier-prod/thoth-notification.yaml
  cve-update/overlays/cnv-prod/thoth-notification.yaml
  graph-backup-job/overlays/cnv-prod/thoth-notification.yaml
  graph-refresh/overlays/cnv-prod/thoth-notification.yaml
  graph-schema-update/overlays/cnv-prod/thoth-notification.yaml
  graph-sync/overlays/cnv-prod/thoth-notification.yaml
  investigator/overlays/cnv-prod/thoth-notification.yaml
  kebechet/overlays/cnv-prod/thoth-notification.yaml
  management-api/overlays/cnv-prod/thoth-notification.yaml
  metrics-exporter/overlays/cnv-prod/thoth-notification.yaml
  package-extract/overlays/cnv-prod/thoth-notification.yaml
  package-releases/overlays/cnv-prod/thoth-notification.yaml
  package-update/overlays/cnv-prod/thoth-notification.yaml
  qeb-hwt-github-app/overlays/cnv-prod/thoth-notification.yaml
  revsolver/overlays/cnv-prod/thoth-notification.yaml
  security-indicators/overlays/cnv-prod/thoth-notification.yaml
  slo-reporter/overlays/cnv-prod/thoth-notification.yaml
  solver/overlays/cnv-prod/thoth-notification.yaml
  user-api/overlays/cnv-prod/thoth-notification.yaml
Labels: approved, deployment_name/moc, size/L

#969 Configure liveness probe for integration-tests
  integration-tests/base/cronjob.yaml
Labels: approved, size/XS

#961 Bump integration-tests to v0.7.1 in stage
  integration-tests/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#962 Bump integration-tests to v0.7.1 in prod
  integration-tests/overlays/cnv-prod-ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#970 Adjust restart policy for integration tests
  integration-tests/base/cronjob.yaml
Labels: approved, lgtm, size/XS

#949 Add flag to optionally sync results of package-extract
  package-extract/base/openshift-templates/package-extract.yaml
Labels: approved, lgtm, size/XS

#859 migrate dependency monkey run in amun-inspection
  adviser/overlays/ocp4-stage/kustomization.yaml
  adviser/overlays/ocp4-stage/put-into-amun-inspection-namespace.yaml
  management-api/overlays/ocp4-stage/role-binding.yaml
Labels: approved, deployment_name/ocp-stage, sig/devops, size/S

#971 Bump version v0.9.2 for investigator stage
  core/overlays/ocp4-stage/common/imagestreamtags.yaml
Labels: approved, size/XS

#975 Increase cache expiration on user-api
  user-api/base/configmap.yaml
  user-api/base/deploymentconfig.yaml
Labels: approved, size/XS

#976 Bump user-api to v0.19.4 in stage
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#978 Bump management-api to v0.15.0 in stage environment
  management-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#979 Bump management-api to v0.15.0 in prod environment
  management-api/overlays/cnv-prod/imagestreamtag.yaml
Labels: approved, deployment_name/moc, size/XS

#983 Bump version v0.21.0 for sefkhet-abwy
  sefkhet-abwy/overlays/cnv-prod/imagestreamtag.yaml
  sefkhet-abwy/overlays/ocp/imagestreamtag.yaml
Labels: approved, size/XS

#972 Bump version v0.9.2 for investigator prod
  core/overlays/cnv-prod/common/imagestreamtags.yaml
Labels: approved, size/XS

#986 Fix syncing condition for package-extract
  package-extract/base/openshift-templates/package-extract.yaml
Labels: approved, lgtm, size/XS

#984 Bump investigator to v0.10.0 in stage
  core/overlays/ocp4-stage/common/imagestreamtags.yaml
Labels: approved, do-not-merge/hold, size/XS

#980 Bump user-api to v0.20.1 in stage environment
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#988 Bump user-api to v0.20.2 in stage environment
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#989 Use data stored on Ceph in adviser containers in stage
  adviser/overlays/ocp4-stage/argo-workflows/advise.yaml
  adviser/overlays/ocp4-stage/argo-workflows/dependency-monkey.yaml
  adviser/overlays/ocp4-stage/argo-workflows/provenance-check.yaml
  adviser/overlays/ocp4-stage/kustomization.yaml
Labels: approved, lgtm, size/XL

#992 Adjust web concurrency for user-api
  user-api/base/deploymentconfig.yaml
Labels: approved, lgtm, size/XS

#994 Update ocp4 stage slo-reporter
  slo-reporter/overlays/ocp4-stage/cronjob.yaml
  slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/L

#995 Handle restarts of integration-tests
  integration-tests/base/cronjob.yaml
Labels: approved, size/XS
