Repository thoth-station/thoth-application, pull requests merged in 2021-03, with the labels that each got.

#990 Bump user-api to v0.20.2 in prod environment
  user-api/overlays/cnv-prod/imagestreamtag.yaml
Labels: approved, deployment_name/moc, size/XS

#1001 Fix restart policy for integration-tests
  integration-tests/base/cronjob.yaml
Labels: approved, size/XS

#1002 state backofflimit inside jobtemplate for cronjob
  integration-tests/base/cronjob.yaml
Labels: approved, size/XS

#1003 Include build-analysis template with package-extract component
  package-extract/base/kustomization.yaml
  package-extract/base/openshift-templates/build-analysis.yaml
Labels: approved, size/XS

#982 Start using inputs prepared by argo to adviser container
  adviser/base/argo-workflows/advise.yaml
  adviser/base/argo-workflows/dependency-monkey.yaml
  adviser/base/argo-workflows/provenance-check.yaml
  adviser/base/openshift-templates/adviser.yaml
  adviser/base/openshift-templates/dependency-monkey.yaml
  adviser/base/openshift-templates/provenance-checker.yaml
  adviser/overlays/ocp4-stage/argo-workflows/advise.yaml
  adviser/overlays/ocp4-stage/argo-workflows/dependency-monkey.yaml
  adviser/overlays/ocp4-stage/argo-workflows/provenance-check.yaml
  adviser/overlays/ocp4-stage/kustomization.yaml
  adviser/overlays/test/argo-workflows/advise.yaml
  adviser/overlays/test/argo-workflows/dependency-monkey.yaml
  adviser/overlays/test/argo-workflows/provenance-check.yaml
  adviser/overlays/test/kustomization.yaml
Labels: approved, size/XXL

#1007 Execute dependency monkey in amun-inspection namespace for thoth
  adviser/base/openshift-templates/dependency-monkey.yaml
  adviser/overlays/cnv-prod/kustomization.yaml
  adviser/overlays/cnv-prod/put-into-amun-inspection-namespace.yaml
Labels: approved, size/XS

#1008 Enable management-api to query back logs of dependency-monkey
  management-api/base/role.yaml
  management-api/overlays/cnv-prod/role-binding.yaml
  management-api/overlays/ocp4-stage/role-binding.yaml
Labels: approved, size/M

#1009 remove todo which was already fixed
  amun/overlays/ocp4-stage/amun-api/openshift-templates/inspection-workflow.yaml
Labels: approved, size/XS

#1010 Add knowledge path to parameters
  mi-scheduler/base/argo-workflows/mi-workflow-template.yaml
  mi-scheduler/base/openshift-templates/mi-run-template.yaml
Labels: approved, size/S

#1012 Schedule graph-sync for dependency monkey only if not dry run
  adviser/base/openshift-templates/dependency-monkey.yaml
Labels: approved, size/XS

#973 debug the new-solver with s2i based images in test
  solver/overlays/test/argo-workflows/solver-template.yaml
  solver/overlays/test/kustomization.yaml
Labels: approved, lgtm, size/L, ¯\_(ツ)_/¯

#968 Revert "Run integration tests that use backend namespace"
  integration-tests/overlays/cnv-prod-ocp4-stage/configmap.yaml
Labels: approved, size/XS

#1019 Bump integration-tests to v0.8.0 in stage environment
  integration-tests/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1014 Update grafana dashboard to include new changes and metrics
  grafana-dashboard/overlays/cnv-prod/thoth-knowledge-graph-content-metrics.json
Labels: approved, size/XL

#993 Adjust web concurrency for management-api and amun-api
  amun/base/deploymentconfig.yaml
  management-api/base/deploymentconfig.yaml
Labels: approved, size/XS

#1020 Bump adviser to v0.26.0 in stage
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1021 Bump version v0.8.1 for graph-backup-job
  graph-backup-job/overlays/cnv-prod/imagestreamtag.yaml
  graph-backup-job/overlays/ocp4-stage/imagestreamtag.yaml
  graph-backup-job/overlays/test/thoth-notification.yaml
Labels: approved, size/XS

#1023 chore: Operate First repos use .prow.yaml now
  prow/overlays/cnv-prod/config.yaml
Labels: approved, size/M

#987 add new workflow helper to update kebechet installation details
  kebechet/base/argo-workflows/update_keb_installation.yaml
  kebechet/base/kustomization.yaml
  kebechet/overlays/test/kebechet.yaml
  kebechet/overlays/test/kustomization.yaml
Labels: approved, size/L

#1024 :sparkles: add a kind/demo label
  prow/overlays/cnv-prod/labels_thoth-station.yaml
  prow/overlays/cnv-prod/plugins.yaml
Labels: approved, size/XS

#1026 switch back on graph-refresh in the stage
  graph-refresh/overlays/ocp4-stage/cronjob.yaml
Labels: approved, size/XS

#1022 Execute solvers with app script
  solver/overlays/test/argo-workflows/solver-template.yaml
Labels: approved, size/XS

#1028 Bump version v0.21.1 for sefkhet-abwy
  sefkhet-abwy/overlays/cnv-prod/imagestreamtag.yaml
  sefkhet-abwy/overlays/ocp/imagestreamtag.yaml
Labels: approved, size/XS

#1030 Add build analysis metrics
  package-extract/base/argo-workflows/package-extract.yaml
  package-extract/base/openshift-templates/build-analysis.yaml
Labels: approved, size/M

#1031 suspend data ingestion in prod till upgrade
  graph-refresh/overlays/cnv-prod/cronjob.yaml
  package-releases/overlays/cnv-prod/cronjob.yaml
  package-update/overlays/cnv-prod/cronjob.yaml
Labels: approved, size/XS

#1032 Add kebechet cronjob
  mi-scheduler/base/cronjob.yaml
  mi-scheduler/overlays/cnv-prod/cronjob.yaml
  mi-scheduler/overlays/ocp4-stage/cronjob.yaml
  mi-scheduler/overlays/test/cronjob.yaml
Labels: approved, size/M

#1027 updated the certs for thoth routes
  .sops.yaml
  amun/overlays/cnv-prod/amun-api/route.enc.yaml
  amun/overlays/ocp4-stage/amun-api/route.enc.yaml
  amun/overlays/test/route.enc.yaml
  management-api/overlays/cnv-prod/route.enc.yaml
  management-api/overlays/ocp4-stage/route.enc.yaml
  management-api/overlays/test/route.enc.yaml
  user-api/overlays/cnv-prod/route.enc.yaml
  user-api/overlays/ocp4-stage/route.enc.yaml
  user-api/overlays/test/route.enc.yaml
Labels: size/XXL

#1034 Add graph database envs
  mi-scheduler/base/cronjob.yaml
Labels: approved, size/S

#1035 Add host variable
  mi-scheduler/base/cronjob.yaml
Labels: approved, size/XS

#1033 update CI/CD configuration
  prow/overlays/cnv-prod/config.yaml
Labels: size/S

#1042 component migration from cnv-moc to zero-moc in prod
  amun/overlays/cnv-prod/amun-api/configmaps.yaml
  amun/overlays/cnv-prod/amun-api/secrets.enc.yaml
  core/overlays/cnv-prod/backend-prod/configmaps.yaml
  core/overlays/cnv-prod/common/configmaps.yaml
  core/overlays/cnv-prod/graph-prod/ceph-storage.yaml
  core/overlays/cnv-prod/infra-prod/prometheus-config.yaml
  core/overlays/cnv-prod/infra-prod/secrets.enc.yaml
  core/overlays/cnv-prod/middletier-prod/configmaps.yaml
  grafana-dashboard/overlays/cnv-prod/thoth-kafka-argo-metrics.json
  grafana-dashboard/overlays/cnv-prod/thoth-knowledge-graph-content-metrics.json
  grafana-dashboard/overlays/cnv-prod/thoth-postgresql-metrics.json
  grafana-dashboard/overlays/cnv-prod/thoth-service-metrics.json
  grafana-dashboard/overlays/cnv-prod/thoth-sli-slo.json
  grafana-dashboard/overlays/cnv-prod/thoth-user-api-metrics.json
  grafana-dashboard/overlays/cnv-prod/thoth-workflow-controllers-metrics.json
  integration-tests/overlays/cnv-prod-ocp4-stage/README.rst
  integration-tests/overlays/cnv-prod-ocp4-stage/configmap.yaml
  kebechet/overlays/cnv-prod/configmap.yaml
  prow/add-ist
  prow/overlays/cnv-prod/config.yaml
  qeb-hwt-github-app/overlays/cnv-prod/configmap.yaml
  sefkhet-abwy/overlays/cnv-prod/configmap.yaml
  slo-reporter/overlays/cnv-prod/configmap.yaml
Labels: approved, size/L

#1038 Run SLO-reporter prod from stage
  slo-reporter/Pipfile
  slo-reporter/Pipfile.lock
  slo-reporter/overlays/cnv-prod/configmap.yaml
  slo-reporter/overlays/cnv-prod/secrets.enc.yaml
  slo-reporter/overlays/zero-prod-ocp4-stage/configmap.yaml
  slo-reporter/overlays/zero-prod-ocp4-stage/cronjob.yaml
  slo-reporter/overlays/zero-prod-ocp4-stage/imagestreamtag.yaml
  slo-reporter/overlays/zero-prod-ocp4-stage/job-generate-name.yaml
  slo-reporter/overlays/zero-prod-ocp4-stage/kustomization.yaml
  slo-reporter/overlays/zero-prod-ocp4-stage/secret-generator.yaml
  slo-reporter/overlays/zero-prod-ocp4-stage/secrets.enc.yaml
  slo-reporter/overlays/zero-prod-ocp4-stage/thoth-notification.yaml
  slo-reporter/test-sendgrid.py
Labels: approved, do-not-merge/hold, size/L

#1046 Updated the image and remove required_context for optional arg
  prow/overlays/cnv-prod/config.yaml
  prow/overlays/cnv-prod/imagestreamtags.yaml
Labels: approved, size/S

#1045 Push SLO-reporter to v0.11.0 in stage and prod-stage
  slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml
  slo-reporter/overlays/zero-prod-ocp4-stage/imagestreamtag.yaml
Labels: approved, lgtm, size/XS

#1044 run integration-test v0.8 as a periodic prow job targeting {zero|cnv}-prod
  prow/overlays/cnv-prod/config.yaml
Labels: size/XS

#985 Bump investigator to v0.10.0 in prod environment
  core/overlays/cnv-prod/common/imagestreamtags.yaml
Labels: size/XS

#1048 manage pr checks with prow jobs
  .prow.yaml
  prow/overlays/cnv-prod/config.yaml
Labels: size/M

#1049 increase mem resource for the postgresql deployment
  core/overlays/cnv-prod/graph-prod/postgresql.yaml
  core/overlays/ocp4-stage/graph-stage/postgresql.yaml
Labels: approved, deployment_name/moc, sig/devops, size/XS

#1050 upgrade solvers to latest version and decommision solver-f32-py37
  core/overlays/ocp4-stage/common/configmaps.yaml
  solver/overlays/cnv-prod/imagestreamtag.yaml
  solver/overlays/ocp4-stage/imagestreamtag.yaml
  solver/overlays/test/imagestreamtag.yaml
Labels: approved, size/M

#809 Change solver virtual env location
  solver/base/argo-workflows/solver-template.yaml
Labels: approved, size/XS

#1053 SLO reporter stage and prod can send emails
  slo-reporter/overlays/ocp4-stage/cronjob.yaml
  slo-reporter/overlays/zero-prod-ocp4-stage/cronjob.yaml
Labels: approved, size/XS

#1051 Make sure exceptions are reported on API when running in test/stage
  user-api/base/configmap.yaml
  user-api/base/deploymentconfig.yaml
  user-api/overlays/ocp4-stage/configmap.yaml
  user-api/overlays/test/configmap.yaml
Labels: approved, size/XS

#1055 Bump metrics-exporter to v0.13.0
  metrics-exporter/overlays/cnv-prod/imagestreamtag.yaml
  metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, lgtm, size/XS

#1056 increase cpu for the postgresql in stage
  core/overlays/ocp4-stage/graph-stage/postgresql.yaml
Labels: approved, size/XS

#1057 Remove branch protection for operate-first org
  prow/overlays/cnv-prod/config.yaml
Labels: approved, lgtm, size/S

#1016 Remove ENABLE_PREPARE specific configuration for adviser
  adviser/base/argo-workflows/advise.yaml
  adviser/base/argo-workflows/dependency-monkey.yaml
  adviser/base/argo-workflows/provenance-check.yaml
Labels: approved, lgtm, size/XS

#1064 Solve metrics exporter schema check alarm for stage
  metrics-exporter/overlays/cnv-prod/imagestreamtag.yaml
  metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1067 allow metrics-exporter to check Kafka connection
  metrics-exporter/base/deploymentconfig.yaml
Labels: approved, size/S

#1068 configure admin user for the postgresql instance
  core/overlays/test/postgresql.yaml
  core/overlays/test/secrets.enc.yaml
Labels: approved, size/L

#1070 alert manager and monitoring for thoth production
  monitoring/README.md
  monitoring/base/alertmanager-monitoring.yaml
  monitoring/base/github-receiver.yaml
  monitoring/base/kustomization.yaml
  monitoring/base/prometheus-rules.yaml
  monitoring/overlays/cnv-prod/kustomization.yaml
Labels: approved, size/L

#1071 Bump up version for management-api v0.15.1
  management-api/overlays/cnv-prod/imagestreamtag.yaml
  management-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: size/XS

#1072 introduce a new ceph setup and cofnigured amun with it
  amun/overlays/cnv-prod/amun-api/configmaps.yaml
  amun/overlays/cnv-prod/amun-api/secrets.enc.yaml
  core/overlays/cnv-prod/graph-prod/ceph-storage.yaml
Labels: size/L

#1074 Send prod email to AICoE
  slo-reporter/overlays/zero-prod-ocp4-stage/configmap.yaml
Labels: approved, size/XS

#1075 increase the ttl for amun-inspection workflows to 1hr
  amun/overlays/cnv-prod/amun-inspection/configmaps.yaml
Labels: size/XS

#1073 configure thoth prod cluster with updated ceph
  core/overlays/cnv-prod/common/configmaps.yaml
  core/overlays/cnv-prod/common/secrets.enc.yaml
Labels: approved, deployment_name/zero-prod, size/L

#1077 Add prescription-sync cronjob
  prescription-sync-job/base/cronjob.yaml
  prescription-sync-job/base/imagestream.yaml
  prescription-sync-job/base/kustomization.yaml
  prescription-sync-job/overlays/cnv-prod/cronjob.yaml
  prescription-sync-job/overlays/cnv-prod/imagestreamtag.yaml
  prescription-sync-job/overlays/cnv-prod/job-generate-name.yaml
  prescription-sync-job/overlays/cnv-prod/kustomization.yaml
  prescription-sync-job/overlays/cnv-prod/thoth-notification.yaml
  prescription-sync-job/overlays/ocp4-stage/cronjob.yaml
  prescription-sync-job/overlays/ocp4-stage/imagestreamtag.yaml
  prescription-sync-job/overlays/ocp4-stage/job-generate-name.yaml
  prescription-sync-job/overlays/ocp4-stage/kustomization.yaml
  prescription-sync-job/overlays/ocp4-stage/thoth-notification.yaml
  prescription-sync-job/overlays/test/cronjob.yaml
  prescription-sync-job/overlays/test/imagestreamtag.yaml
  prescription-sync-job/overlays/test/job-generate-name.yaml
  prescription-sync-job/overlays/test/kustomization.yaml
  prescription-sync-job/overlays/test/thoth-notification.yaml
Labels: approved, size/L

#1079 Remove old prod deployment of graph-backup-job
  graph-backup-job/overlays/prod/cronjob.yaml
  graph-backup-job/overlays/prod/imagestreamtag.yaml
  graph-backup-job/overlays/prod/job-generate-name.yaml
  graph-backup-job/overlays/prod/kustomization.yaml
  graph-backup-job/overlays/prod/thoth-notification.yaml
Labels: approved, size/M

#1080 Fix links in graph-backup job
  graph-backup-job/overlays/ocp4-stage/thoth-notification.yaml
Labels: approved, size/XS

#1082 updated the khemenu certs
  user-api/overlays/cnv-prod/khemenu.route.enc.yaml
  user-api/overlays/ocp4-stage/khemenu.route.enc.yaml
Labels: approved, size/L

#1083 Add missing knowledge_path parameter
  mi-scheduler/base/argo-workflows/mi-workflow-template.yaml
  mi-scheduler/base/openshift-templates/mi-run-template.yaml
Labels: approved, size/XS

#1084 Use new version for slo-reporter
  slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml
  slo-reporter/overlays/zero-prod-ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1089 feat: Setup prow for aicoe-aiops
  prow/overlays/cnv-prod/config.yaml
  prow/overlays/cnv-prod/label-sync-cronjob.yaml
  prow/overlays/cnv-prod/labels_aicoe-aiops.yaml
Labels: approved, size/L

#1088 :arrow_up: update the container image tags used to decorate prow jobs
  prow/overlays/cnv-prod/config.yaml
Labels: approved, size/XS

#1087 :sparkles: add the #B4mad Minecraft project
  prow/overlays/cnv-prod/config.yaml
  prow/overlays/cnv-prod/plugins.yaml
Labels: approved, size/M

#1090 Add logging envs
  mi-scheduler/base/argo-workflows/mi-workflow-template.yaml
  mi-scheduler/base/cronjob.yaml
  mi-scheduler/base/openshift-templates/mi-run-template.yaml
Labels: approved, lgtm, size/M

#1091 Remove mi-scheduler env from run-mi template
  mi-scheduler/base/openshift-templates/mi-run-template.yaml
Labels: approved, size/XS

#1092 increase the resources for adviser run in the production environment
  adviser/overlays/cnv-prod/advise-resources-patch.yaml
  adviser/overlays/cnv-prod/kustomization.yaml
Labels: approved, size/S

#1093 debug increase of the resources for adviser run in the production
  adviser/overlays/cnv-prod/advise-resources-patch.yaml
Labels: approved, size/XS

#1094 Fix logging to use THOTH_ADJUST_LOGGING
  mi-scheduler/base/argo-workflows/mi-workflow-template.yaml
  mi-scheduler/base/cronjob.yaml
  mi-scheduler/base/openshift-templates/mi-run-template.yaml
Labels: approved, lgtm, size/M

#1095 parameters are not part of mi scheduler cronjob
  mi-scheduler/base/cronjob.yaml
Labels: approved, size/S

#1096 Fix incorrect name of mi-scheduler in logging envvar
  mi-scheduler/base/cronjob.yaml
Labels: approved, size/XS

#1097 Add max number of workflows limit
  mi-scheduler/base/argo-workflows/mi-workflow-template.yaml
Labels: approved, size/XS

#1098 Add ADDITIONAL_CONFIGURATION to passed parameters
  mi-scheduler/base/argo-workflows/mi-workflow-template.yaml
  mi-scheduler/base/cronjob.yaml
  mi-scheduler/base/openshift-templates/mi-run-template.yaml
Labels: approved, size/S

#1099 bump resources for the qebhwt workflow
  qeb-hwt-github-app/base/argo-workflows/qeb-hwt-integration.yaml
Labels: approved, size/XS

#1103 manage required checks for repos
  prow/overlays/cnv-prod/config.yaml
Labels: approved, size/S

#1105 Run prescription sync command
  prescription-sync-job/base/cronjob.yaml
Labels: approved, size/XS

#1078 Supply prescription.yaml to adviser container
  adviser/base/argo-workflows/advise.yaml
  adviser/base/argo-workflows/dependency-monkey.yaml
Labels: approved, lgtm, size/M

#1106 Prescription syncing does not require knowledge graph
  prescription-sync-job/base/cronjob.yaml
Labels: approved, size/S

#1107 Change thoth flag to be setup with envvar
  mi-scheduler/base/argo-workflows/mi-workflow-template.yaml
  mi-scheduler/base/openshift-templates/mi-run-template.yaml
Labels: approved, size/S

#1108 Give full path to perscription file
  adviser/base/argo-workflows/advise.yaml
  adviser/base/argo-workflows/dependency-monkey.yaml
Labels: size/XS

#1109 chore: Update operate first labels
  prow/overlays/cnv-prod/labels_operate-first.yaml
Labels: approved, size/S

#1115 Mi scheduler/reduce parallelism
  mi-scheduler/base/argo-workflows/mi-workflow-template.yaml
Labels: approved, size/XS

#1114 Fix parameter setup from ${..} to {{..}}
  mi-scheduler/base/argo-workflows/mi-workflow-template.yaml
Labels: approved, size/XS

#1118 templates are to be placed on the infra namespace
  package-extract/overlays/cnv-prod/kustomization.yaml
  package-extract/overlays/ocp4-stage/kustomization.yaml
Labels: approved, size/S

#1119 Bump up version for messaging v0.12.0 for stage and prod
  core/overlays/cnv-prod/common/imagestreamtags.yaml
  core/overlays/ocp4-stage/common/imagestreamtags.yaml
Labels: approved, size/XS

#1116 enable max time for prow jobs via sinker
  prow/overlays/cnv-prod/config.yaml
Labels: approved, lgtm, size/XS

#1124 Bump adviser to 0.27.0 in stage
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1127 access the logs in different namespace than api
  management-api/overlays/cnv-prod/role-binding.yaml
  management-api/overlays/ocp4-stage/role-binding.yaml
  user-api/overlays/cnv-prod/role-binding.yaml
  user-api/overlays/ocp4-stage/role-binding.yaml
Labels: approved, size/M

#1128 chore: Add triage labels for Operate First
  prow/overlays/cnv-prod/labels_operate-first.yaml
Labels: approved, size/M

#1134 Fix advise reporter talking to kafka
  advise-reporter/base/cronjob.yaml
Labels: approved, size/XS

#1132 Run graph-sync in advises only when authenticated
  adviser/base/openshift-templates/adviser.yaml
Labels: approved, size/XS

#1135 updated kafka certs for prod cluster
  core/overlays/cnv-prod/common/secrets.enc.yaml
Labels: approved, size/L

#1136 Revert "updated kafka certs for prod cluster"
  core/overlays/cnv-prod/common/secrets.enc.yaml
Labels: size/L
