Repository thoth-station/thoth-application, pull requests merged in 2021-07, with the labels that each got.

#1783 switch on only the solver needed for the ingestion
  core/overlays/ocp4-stage/common/configmaps.yaml
Labels: approved, size/XS

#1784 switch on only the ubi8 solver for the ingestion
  core/overlays/ocp4-stage/common/configmaps.yaml
Labels: approved, size/XS

#1781 cleanup: Remove labels sync and peribolos
  prow/overlays/cnv-prod/kustomization.yaml
  prow/overlays/cnv-prod/label-sync-cronjob.yaml
  prow/overlays/cnv-prod/labels.yaml
  prow/overlays/cnv-prod/labels_aicoe-aiops.yaml
  prow/overlays/cnv-prod/labels_thoth-station.yaml
  prow/overlays/cnv-prod/org_thoth-station.yaml
  prow/overlays/cnv-prod/peribolos.yaml
Labels: approved, size/XXL

#1786 Bump metrics-exporter to v0.16.2
  metrics-exporter/overlays/cnv-prod/imagestreamtag.yaml
  metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1789 Add thoth deployment name envvar from thoth configmap
  mi-scheduler/base/cronjob.yaml
Labels: approved, lgtm, size/S

#1793 Bump metrics-exporter to v0.16.3
  metrics-exporter/overlays/cnv-prod/imagestreamtag.yaml
  metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1794 Bump thoth reporter to v0.10.1
  advise-reporter/overlays/cnv-prod/imagestreamtag.yaml
  advise-reporter/overlays/ocp4-stage/imagestreamtag.yaml
Labels: size/XS

#1791 Bump adviser to v0.35.0 in prod environment
  adviser/overlays/cnv-prod/imagestreamtag.yaml
Labels: approved, size/XS

#1790 Bump adviser to v0.35.0 in stage environment
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, do-not-merge/hold, kind/bug, priority/critical-urgent

#1796 Bump mng-api v0.17.6
  management-api/overlays/cnv-prod/imagestreamtag.yaml
  management-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1799 Bump adviser reporter to v0.10.2
  advise-reporter/overlays/cnv-prod/imagestreamtag.yaml
  advise-reporter/overlays/ocp4-stage/imagestreamtag.yaml
Labels: size/XS

#1797 Bump graph related component to v0.51.0 of thoth-storages
  core/overlays/cnv-prod/common/imagestreamtags.yaml
  graph-backup-job/overlays/cnv-prod/imagestreamtag.yaml
  graph-backup-job/overlays/ocp4-stage/imagestreamtag.yaml
  graph-metrics-exporter/overlays/cnv-prod/imagestreamtag.yaml
  graph-metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
  graph-refresh/overlays/cnv-prod/imagestreamtag.yaml
  graph-sync/overlays/cnv-prod/imagestreamtag.yaml
Labels: approved, size/S

#1800 Update dashbaords in prod
  grafana-dashboard/overlays/cnv-prod/thoth-kafka-argo-metrics.json
  grafana-dashboard/overlays/cnv-prod/thoth-postgresql-metrics.json
  grafana-dashboard/overlays/cnv-prod/thoth-sli-slo.json
Labels: approved, size/XXL

#1801 Add workflows rate metrics
  grafana-dashboard/overlays/cnv-prod/thoth-kafka-argo-metrics.json
Labels: approved, size/XL

#1806 update mi-scheduler to the newest v1.6.1 version
  mi-scheduler/overlays/zero-test/imagestreamtag.yaml
Labels: approved, size/XS

#1809 Add MI entities as PullRequest and Issue
  mi-scheduler/base/configmaps.yaml
  mi-scheduler/base/cronjob.yaml
Labels: approved, size/XS

#1810 Fix reference to be key instead of value
  mi-scheduler/base/cronjob.yaml
Labels: approved, size/XS

#1814 feat: Enable override to bypass failing CI if necessary
  prow/overlays/cnv-prod/plugins.yaml
Labels: approved, size/XS

#1815 Changing org list to not contain spaces
  mi-scheduler/base/configmaps.yaml
Labels: approved, lgtm, size/XS

#1818 Fix thoth logging for mi-github cronjob
  mi-scheduler/base/cronjob.yaml
Labels: approved, lgtm, size/XS

#1819 Make entities consistent with other string lists
  mi-scheduler/base/configmaps.yaml
Labels: approved, size/XS

#1782 feat: Use ACME operator for routes
  prow/overlays/cnv-prod/kustomization.yaml
  prow/overlays/cnv-prod/routes.enc.yaml
  prow/overlays/cnv-prod/routes.yaml
  prow/overlays/cnv-prod/secret-generator.yaml
Labels: approved, size/L

#1821 feat: Enable tide on meteor and require approved on common
  prow/overlays/cnv-prod/config.yaml
Labels: approved, lgtm, size/S

#1826 Deprecate prescriptions-gh-release-notes job
  prescriptions-gh-release-notes-job/base/imagestream.yaml
  prescriptions-gh-release-notes-job/base/kustomization.yaml
  prescriptions-gh-release-notes-job/base/openshift-templates/prescriptions-gh-release-notes.yaml
  prescriptions-gh-release-notes-job/overlays/zero-prod/imagestreamtag.yaml
  prescriptions-gh-release-notes-job/overlays/zero-prod/job-generate-name.yaml
  prescriptions-gh-release-notes-job/overlays/zero-prod/kustomization.yaml
  prescriptions-gh-release-notes-job/overlays/zero-prod/thoth-notification.yaml
Labels: approved, size/L

#1834 Add operate-first as an organization
  mi-scheduler/base/configmaps.yaml
Labels: approved, size/XS

#1836 Use prescriptions in Dependency Monkey runs
  adviser/base/argo-workflows/dependency-monkey.yaml
Labels: approved, size/M

#1828 :sparkles: do not include area/rel-eng issues from filter
  triage-party/overlays/zero-prod/config.yaml
Labels: approved, lgtm, size/XS

#1832 Bump adviser to v0.36.0 in stage environment
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1837 switch on the graph-refresh job for stage
  graph-refresh/overlays/ocp4-stage/cronjob.yaml
Labels: approved, size/XS

#1833 Bump prescriptions to v0.2.0 in stage environment
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1807 add new step in purge job for creating upstream issues
  purge-job/base/argo-workflows/purge-issues.yaml
  purge-job/base/kustomization.yaml
  purge-job/base/openshift-templates/purge.yaml
Labels: approved, size/M

#1840 Bump metric-exporter to v0.17.0
  grafana-dashboard/overlays/cnv-prod/thoth-knowledge-graph-content-metrics.json
  metrics-exporter/overlays/cnv-prod/imagestreamtag.yaml
  metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1838 updates from the template project
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
  .github/ISSUE_TEMPLATE/redeliver_container_image.md
Labels: approved, bot, size/M

#1842 add secrets for meta-informa
  mi-scheduler/overlays/zero-test/secrets.enc.yaml
Labels: approved, size/L

#1846 Bump up versions of thoth components in prod for release v19.07.2021
  adviser/overlays/cnv-prod/imagestreamtag.yaml
  core/overlays/cnv-prod/common/imagestreamtags.yaml
  mi-scheduler/overlays/cnv-prod/imagestreamtag.yaml
  package-extract/overlays/cnv-prod/imagestreamtag.yaml
  package-update/overlays/cnv-prod/imagestreamtag.yaml
  revsolver/overlays/cnv-prod/imagestreamtag.yaml
  slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml
  slo-reporter/overlays/zero-prod-ocp4-stage/imagestreamtag.yaml
  user-api/overlays/cnv-prod/imagestreamtag.yaml
Labels: approved, size/S

#1820 Solver project url job
  solver-project-url-job/base/cronjob.yaml
  solver-project-url-job/base/imagestream.yaml
  solver-project-url-job/base/kustomization.yaml
  solver-project-url-job/overlays/test/buildConfig.yaml
  solver-project-url-job/overlays/test/cronjob.yaml
  solver-project-url-job/overlays/test/imagestreamtag.yaml
  solver-project-url-job/overlays/test/job-generate-name.yaml
  solver-project-url-job/overlays/test/kustomization.yaml
  solver-project-url-job/overlays/test/thoth-notification.yaml
Labels: approved, lgtm, size/L

#1854 Bump pulp-pypi-sync-job to v0.1.0 in stage environment
  pulp-pypi-sync-job/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1857 setup kebehcet github token secrets for metrics-exporter
  metrics-exporter/overlays/cnv-prod/kustomization.yaml
  metrics-exporter/overlays/cnv-prod/secret-generator.yaml
  metrics-exporter/overlays/cnv-prod/secrets.enc.yaml
  metrics-exporter/overlays/ocp4-stage/kustomization.yaml
  metrics-exporter/overlays/ocp4-stage/secret-generator.yaml
  metrics-exporter/overlays/ocp4-stage/secrets.enc.yaml
  metrics-exporter/overlays/test/kustomization.yaml
  metrics-exporter/overlays/test/secret-generator.yaml
  metrics-exporter/overlays/test/secrets.enc.yaml
Labels: approved, size/L

#1845 update of grafana with the opf-prometheus datasource
  grafana-dashboard/overlays/cnv-prod/argocd.json
  grafana-dashboard/overlays/cnv-prod/thoth-kafka-argo-metrics.json
  grafana-dashboard/overlays/cnv-prod/thoth-knowledge-graph-content-metrics.json
  grafana-dashboard/overlays/cnv-prod/thoth-postgresql-metrics.json
  grafana-dashboard/overlays/cnv-prod/thoth-service-metrics.json
  grafana-dashboard/overlays/cnv-prod/thoth-sli-slo.json
  grafana-dashboard/overlays/cnv-prod/thoth-user-api-metrics.json
  grafana-dashboard/overlays/cnv-prod/thoth-workflow-controllers-metrics.json
Labels: approved, size/XL

#1858 Bump up version for metrics-exporter
  metrics-exporter/base/deploymentconfig.yaml
  metrics-exporter/overlays/cnv-prod/deploymentconfig.yaml
  metrics-exporter/overlays/cnv-prod/imagestreamtag.yaml
  metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/S

#1859 Add merge path to openshift and argo templates
  mi-scheduler/base/argo-workflows/mi-workflow-template.yaml
  mi-scheduler/base/openshift-templates/mi-run-template.yaml
Labels: approved, size/S

#1856 Bump adviser to v0.38.0 in stage environment
  adviser/overlays/test/imagestreamtag.yaml
Labels: approved, size/XS

#1862 Bump adviser to v0.38.1 in stage environment
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, lgtm, size/XS
