Repository thoth-station/thoth-application, pull requests merged in 2021-11, with the labels that each got.

#2108 Infra-prod service-monitor creates field label on balrog
  core/overlays/aws-prod/infra-prod/kustomization.yaml
  core/overlays/aws-prod/infra-prod/service-monitor.yaml
Labels: size/M, approved

#2104 Backend service-monitor creates field label on balrog
  core/overlays/aws-prod/backend-prod/kustomization.yaml
  core/overlays/aws-prod/backend-prod/service-monitor.yaml
Labels: approved, size/S

#2103 Graph service-monitor creates field label on balrog
  core/overlays/aws-prod/graph-prod/kustomization.yaml
  core/overlays/aws-prod/graph-prod/service-monitor.yaml
Labels: approved, size/S

#2105 Frontend service-monitor creates field label on balrog
  core/overlays/aws-prod/frontend-prod/kustomization.yaml
  core/overlays/aws-prod/frontend-prod/service-monitor.yaml
Labels: approved, size/S

#2106 Middletier service-monitor creates field label on balrog
  core/overlays/aws-prod/middletier-prod/kustomization.yaml
  core/overlays/aws-prod/middletier-prod/service-monitor.yaml
Labels: approved, size/S

#2093 Make monitored container images by prescriptions-refresh configurable
  prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-quay.yaml
  prescriptions-refresh-job/base/configmap.yaml
  prescriptions-refresh-job/base/kustomization.yaml
Labels: approved, size/S

#2107 applying overlays for grafana dashboards to balrog
  grafana-dashboard/overlays/aws-prod/argocd.json
  grafana-dashboard/overlays/aws-prod/thoth-kafka-argo-metrics.json
  grafana-dashboard/overlays/aws-prod/thoth-knowledge-graph-content-metrics.json
  grafana-dashboard/overlays/aws-prod/thoth-postgresql-metrics.json
  grafana-dashboard/overlays/aws-prod/thoth-service-metrics.json
  grafana-dashboard/overlays/aws-prod/thoth-sli-slo.json
  grafana-dashboard/overlays/aws-prod/thoth-user-api-metrics.json
  grafana-dashboard/overlays/aws-prod/thoth-workflow-controllers-metrics.json
Labels: approved, size/XXL

#2109 use emptyDir for cloning git repo
  kebechet/base/argo-workflows/kebechet-run-url.yaml
  kebechet/base/argo-workflows/kebechet.yaml
  kebechet/base/openshift-templates/kebechet-run-url.yaml
  kebechet/base/openshift-templates/kebechet.yaml
Labels: approved, size/S

#2101 Create adviser configmap with all the configuration options
  adviser/base/argo-workflows/advise.yaml
  adviser/base/configmap.yaml
  adviser/base/kustomization.yaml
  adviser/overlays/aws-prod/configmap.yaml
  adviser/overlays/aws-prod/kustomization.yaml
  adviser/overlays/moc-prod/configmap.yaml
  adviser/overlays/moc-prod/kustomization.yaml
  adviser/overlays/ocp4-stage/configmap.yaml
  adviser/overlays/ocp4-stage/kustomization.yaml
  adviser/overlays/test/configmap.yaml
  adviser/overlays/test/kustomization.yaml
Labels: size/M, approved

#2112 use https based url in the pre-commit
  .pre-commit-config.yaml
Labels: approved, size/XS, lgtm

#2110 Simplify alerting rule
  monitoring/overlays/moc-prod/alerting-rules.yaml
Labels: approved, size/S

#2092 set the pulp pypi sync job prod overlay
  pulp-pypi-sync-job/overlays/cnv-prod/kustomization.yaml
  pulp-pypi-sync-job/overlays/cnv-prod/thoth-notification.yaml
  pulp-pypi-sync-job/overlays/moc/cronjob.yaml
  pulp-pypi-sync-job/overlays/moc/imagestreamtag.yaml
  pulp-pypi-sync-job/overlays/moc/kustomization.yaml
  pulp-pypi-sync-job/overlays/moc/thoth-notification.yaml
  pulp-pypi-sync-job/overlays/ocp4-stage/cronjob.yaml
  pulp-pypi-sync-job/overlays/ocp4-stage/imagestreamtag.yaml
  pulp-pypi-sync-job/overlays/test/cronjob.yaml
  pulp-pypi-sync-job/overlays/test/kustomization.yaml
Labels: approved, size/L

#1965 create new workflow for repo initialization
  core/base/configmaps.yaml
  thoth-repo-init/base/argo-workflows/thoth-repo-init.yaml
  thoth-repo-init/base/imagestream.yaml
  thoth-repo-init/base/kustomization.yaml
  thoth-repo-init/base/openshift-templates/thoth-repo-init.yaml
  thoth-repo-init/overlays/test/imagestreamtag.yaml
  thoth-repo-init/overlays/test/kustomization.yaml
  thoth-repo-init/overlays/test/thoth-notification.yaml
Labels: approved, size/L

#2114 updating name of datasource in dashboards
  grafana-dashboard/overlays/aws-prod/thoth-kafka-argo-metrics.json
  grafana-dashboard/overlays/aws-prod/thoth-knowledge-graph-content-metrics.json
  grafana-dashboard/overlays/aws-prod/thoth-sli-slo.json
Labels: approved, size/L

#2115 change name of template to thoth-repo-init
  thoth-repo-init/base/openshift-templates/thoth-repo-init.yaml
Labels: approved, size/XS

#2117 Fix the datasource
  grafana-dashboard/overlays/moc-prod/argocd.json
  grafana-dashboard/overlays/moc-prod/thoth-postgresql-metrics.json
  grafana-dashboard/overlays/moc-prod/thoth-service-metrics.json
  grafana-dashboard/overlays/moc-prod/thoth-user-api-metrics.json
  grafana-dashboard/overlays/moc-prod/thoth-workflow-controllers-metrics.json
Labels: approved, size/L

#2118 Remove job field from the grafana dashbaord
  grafana-dashboard/overlays/aws-prod/argocd.json
  grafana-dashboard/overlays/aws-prod/thoth-knowledge-graph-content-metrics.json
  grafana-dashboard/overlays/aws-prod/thoth-sli-slo.json
Labels: approved, size/L

#2119 removing ports
  grafana-dashboard/overlays/aws-prod/argocd.json
  grafana-dashboard/overlays/aws-prod/thoth-kafka-argo-metrics.json
  grafana-dashboard/overlays/aws-prod/thoth-knowledge-graph-content-metrics.json
  grafana-dashboard/overlays/aws-prod/thoth-postgresql-metrics.json
  grafana-dashboard/overlays/aws-prod/thoth-sli-slo.json
  grafana-dashboard/overlays/aws-prod/thoth-user-api-metrics.json
  grafana-dashboard/overlays/aws-prod/thoth-workflow-controllers-metrics.json
  grafana-dashboard/overlays/moc-prod/argocd.json
  grafana-dashboard/overlays/moc-prod/thoth-kafka-argo-metrics.json
  grafana-dashboard/overlays/moc-prod/thoth-knowledge-graph-content-metrics.json
  grafana-dashboard/overlays/moc-prod/thoth-postgresql-metrics.json
  grafana-dashboard/overlays/moc-prod/thoth-sli-slo.json
  grafana-dashboard/overlays/moc-prod/thoth-user-api-metrics.json
  grafana-dashboard/overlays/moc-prod/thoth-workflow-controllers-metrics.json
Labels: approved, size/L

#2120 clean up the legacy way of setting up the prometheus
  core/overlays/aws-prod/infra-prod/kustomization.yaml
  core/overlays/aws-prod/infra-prod/prometheus-config.yaml
  core/overlays/aws-prod/infra-prod/secret-generator.yaml
  core/overlays/aws-prod/infra-prod/secrets.enc.yaml
  core/overlays/moc-prod/infra-prod/kustomization.yaml
  core/overlays/moc-prod/infra-prod/prometheus-config.yaml
  core/overlays/moc-prod/infra-prod/secret-generator.yaml
  core/overlays/moc-prod/infra-prod/secrets.enc.yaml
Labels: approved, size/L

#2128 Bump revsolver to v0.2.10 in stage
  revsolver/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2121 patch the smaug secrets for slo-reportor
  slo-reporter/overlays/moc-prod-ocp4-stage/configmap.yaml
  slo-reporter/overlays/moc-prod-ocp4-stage/secrets.enc.yaml
Labels: approved, size/L

#2132 Bump user-api to v0.27.2 in stage environment
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2122 Bump cve-update to v0.5.0 in stage environment
  cve-update/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2127 Bump package-releases to v0.11.5 in stage
  package-releases/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2131 Bump graph-sync to v0.10.16 in stage
  graph-sync/overlays/ocp4-stage/common/imagestreamtag.yaml
Labels: approved

#2133 Bump management-api to v0.17.14 in stage
  management-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2123 Bump adviser to v0.47.0 in stage environment
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2124 Bump metrics-exporter to v0.19.0 in stage environment
  metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2125 Bump package-update to v0.8.14 in stage environment
  package-update/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2134 Bump up the images based on the version update v2021.11.08
  adviser/overlays/aws-prod/imagestreamtag.yaml
  adviser/overlays/moc-prod/imagestreamtag.yaml
  core/overlays/aws-prod/common/imagestreamtags.yaml
  core/overlays/moc-prod/common/imagestreamtags.yaml
  core/overlays/ocp4-stage/common/imagestreamtags.yaml
  core/overlays/rick-test/imagestreamtags.yaml
  cve-update/overlays/aws-prod/imagestreamtag.yaml
  cve-update/overlays/moc-prod/imagestreamtag.yaml
  graph-backup-job/overlays/aws-prod/imagestreamtag.yaml
  graph-backup-job/overlays/moc-prod/imagestreamtag.yaml
  graph-metrics-exporter/overlays/aws-prod/imagestreamtag.yaml
  graph-metrics-exporter/overlays/moc-prod/imagestreamtag.yaml
  graph-metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
  graph-refresh/overlays/aws-prod/imagestreamtag.yaml
  graph-refresh/overlays/moc-prod/imagestreamtag.yaml
  graph-sync/overlays/aws-prod/common/imagestreamtag.yaml
  graph-sync/overlays/moc-prod/common/imagestreamtag.yaml
  management-api/overlays/aws-prod/imagestreamtag.yaml
  management-api/overlays/moc-prod/imagestreamtag.yaml
  metrics-exporter/overlays/aws-prod/imagestreamtag.yaml
  metrics-exporter/overlays/moc-prod/imagestreamtag.yaml
  package-releases/overlays/aws-prod/imagestreamtag.yaml
  package-releases/overlays/moc-prod/imagestreamtag.yaml
  package-update/overlays/aws-prod/imagestreamtag.yaml
  package-update/overlays/moc-prod/imagestreamtag.yaml
  prescriptions-refresh-job/overlays/moc/imagestreamtag.yaml
  revsolver/overlays/aws-prod/imagestreamtag.yaml
  revsolver/overlays/moc-prod/imagestreamtag.yaml
  slo-reporter/overlays/moc-prod-ocp4-stage/imagestreamtag.yaml
  slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml
  thoth-repo-init/overlays/test/imagestreamtag.yaml
  user-api/overlays/aws-prod/imagestreamtag.yaml
  user-api/overlays/moc-prod/imagestreamtag.yaml
  user-api/overlays/rick-test/imagestreamtag.yaml
Labels: size/M, approved

#2042 Add cve-warning prescriptions-refresh task
  prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-pg.yaml
  prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh.yaml
Labels: size/L

#2138 Decommission solver-project-url-job
  solver-project-url-job/base/cronjob.yaml
  solver-project-url-job/base/imagestream.yaml
  solver-project-url-job/base/kustomization.yaml
  solver-project-url-job/overlays/test/buildConfig.yaml
  solver-project-url-job/overlays/test/cronjob.yaml
  solver-project-url-job/overlays/test/imagestreamtag.yaml
  solver-project-url-job/overlays/test/kustomization.yaml
  solver-project-url-job/overlays/test/thoth-notification.yaml
Labels: approved, size/L, lgtm

#2144 chore: add aicoe/seraph to tide
  prow/overlays/smaug/config.yaml
Labels: approved, size/XS

#2143 service monitor to expose prow metrics to smaug grafana
  prow/overlays/smaug/kustomization.yaml
  prow/overlays/smaug/service-monitor.yaml
Labels: size/S

#2146 removing jobs from smaug dashboards
  grafana-dashboard/overlays/moc-prod/argocd.json
  grafana-dashboard/overlays/moc-prod/thoth-knowledge-graph-content-metrics.json
  grafana-dashboard/overlays/moc-prod/thoth-sli-slo.json
Labels: approved, size/L

#2147 Bump user-api stage to v0.28.0
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2148 Bump up the kebechet version to v1.6.2
  kebechet/overlays/aws-prod/imagestreamtag.yaml
  kebechet/overlays/moc-prod/imagestreamtag.yaml
  kebechet/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2150 Bump up the kebechet version to v1.6.3
  kebechet/overlays/aws-prod/imagestreamtag.yaml
  kebechet/overlays/moc-prod/imagestreamtag.yaml
  kebechet/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2151 Bump up the kebechet version to v1.6.4
  kebechet/overlays/aws-prod/imagestreamtag.yaml
  kebechet/overlays/moc-prod/imagestreamtag.yaml
  kebechet/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2152 Bump up the kebechet version to v1.6.5
  kebechet/overlays/aws-prod/imagestreamtag.yaml
  kebechet/overlays/moc-prod/imagestreamtag.yaml
  kebechet/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2153 Bump up the kebechet version to v1.6.6
  kebechet/overlays/aws-prod/imagestreamtag.yaml
  kebechet/overlays/moc-prod/imagestreamtag.yaml
  kebechet/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2154 bump user-api stage to v0.28.1
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2155 Bump up the images based on the version update v2021.11.22
  prescriptions-refresh-job/overlays/moc/imagestreamtag.yaml
  user-api/overlays/aws-prod/imagestreamtag.yaml
  user-api/overlays/moc-prod/imagestreamtag.yaml
  user-api/overlays/rick-test/imagestreamtag.yaml
Labels: approved, size/XS

#2159 Update mi to v2.10.1
  mi-scheduler/overlays/test/imagestreamtag.yaml
Labels: approved, size/XS

#2166 Bump kebechet to version v1.6.7 for the tag issue fix
  kebechet/overlays/aws-prod/imagestreamtag.yaml
  kebechet/overlays/moc-prod/imagestreamtag.yaml
  kebechet/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2163 Fix dashboard metrics labels
  grafana-dashboard/overlays/moc-prod/thoth-sli-slo.json
Labels: approved, size/L

#2169 Enable prow/tide for the aicoe/donkeycar repo
  prow/overlays/smaug/config.yaml
Labels: approved, size/XS

#2167 Bump adviser to v0.48.0 in stage environment
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2173 Update mi-scheduler to v1.7.1
  mi-scheduler/overlays/test/imagestreamtag.yaml
Labels: approved, size/XS
