Repository thoth-station/thoth-application, pull requests merged in 2021-10, with the labels that each got.

#1994 updating sops with my gpg pub
  .sops.yaml
Labels: approved, size/XS

#1989 Update triage-party configuration
  triage-party/base/deployment.yaml
  triage-party/overlays/moc/config.yaml
  triage-party/overlays/moc/pcache.yaml
Labels: approved, size/XS

#1999 patch the moc secrets for the new contributors
  core/overlays/moc-prod/common/secrets.enc.yaml
Labels: approved, size/L

#2001 Bump package release to v0.11.4 in test and stage
  package-releases/overlays/ocp4-stage/imagestreamtag.yaml
  package-releases/overlays/test/imagestreamtag.yaml
Labels: approved, size/XS

#2000 Update secret documentation
  docs/secret_management.md
Labels: size/M, approved

#2002 Patch the service with annotations to refer imagestreams
  advise-reporter/base/cronjob.yaml
  advise-reporter/overlays/aws-prod/cronjob.yaml
  advise-reporter/overlays/moc-prod/cronjob.yaml
  advise-reporter/overlays/test/cronjob.yaml
  adviser/base/argo-workflows/advise.yaml
  adviser/base/argo-workflows/dependency-monkey.yaml
  adviser/base/argo-workflows/kebechet-run-results.yaml
  adviser/base/argo-workflows/parse-adviser-output.yaml
  adviser/base/argo-workflows/parse-provenance-checker-output.yaml
  adviser/base/argo-workflows/provenance-check.yaml
  adviser/base/argo-workflows/trigger-integration.yaml
  management-api/base/deploymentconfig.yaml
Labels: size/M, approved

#2006 fix the chat-notification resolve for newer kustomize
  investigator/overlays/aws-prod/job-generate-name.yaml
  investigator/overlays/aws-prod/kustomization.yaml
  investigator/overlays/aws-prod/thoth-notification.yaml
  investigator/overlays/moc-prod/job-generate-name.yaml
  investigator/overlays/moc-prod/kustomization.yaml
  investigator/overlays/moc-prod/thoth-notification.yaml
  investigator/overlays/ocp4-stage/job-generate-name.yaml
  investigator/overlays/ocp4-stage/kustomization.yaml
  investigator/overlays/ocp4-stage/thoth-notification.yaml
  investigator/overlays/rick-test/job-generate-name.yaml
  investigator/overlays/rick-test/kustomization.yaml
  investigator/overlays/rick-test/thoth-notification.yaml
  investigator/overlays/test/job-generate-name.yaml
  investigator/overlays/test/kustomization.yaml
  investigator/overlays/test/thoth-notification.yaml
Labels: approved, size/L

#2009 Don't declare namespace value explicitly in kustomize file
  adviser/overlays/ocp4-stage/kustomization.yaml
  chat-notification/overlays/ocp4-stage/kustomization.yaml
  chat-notification/overlays/test/kustomization.yaml
  cve-update/overlays/aws-prod/kustomization.yaml
  cve-update/overlays/moc-prod/kustomization.yaml
  cve-update/overlays/ocp4-stage/kustomization.yaml
  cve-update/overlays/test/kustomization.yaml
  graph-refresh/overlays/test/kustomization.yaml
  package-releases/overlays/ocp4-stage/kustomization.yaml
  package-releases/overlays/test/kustomization.yaml
  pulp-pypi-sync-job/overlays/test/kustomization.yaml
  solver-project-url-job/overlays/test/kustomization.yaml
Labels: approved, size/S, lgtm
