Repository thoth-station/thoth-application, pull requests merged in 2021-04, with the labels that each got.

#1137 updated thoth secrets across the board
  amun/overlays/cnv-prod/amun-api/secrets.enc.yaml
  amun/overlays/ocp4-stage/amun-api/secrets.enc.yaml
  amun/overlays/test/secrets.enc.yaml
  core/overlays/cnv-prod/common/secrets.enc.yaml
  core/overlays/ocp4-stage/common/secrets.enc.yaml
  core/overlays/test/secrets.enc.yaml
Labels: approved, size/XL

#1138 Bump SLO-reporter to v0.13.0
  slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml
  slo-reporter/overlays/zero-prod-ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1140 Fix parallel limit to use semaphore instead of parallelism
  mi-scheduler/base/argo-workflows/mi-workflow-template.yaml
  mi-scheduler/base/configmaps.yaml
Labels: approved, size/XS

#1141 use argo v2.12.5 in prod deployment
  amun/overlays/cnv-prod/amun-inspection/argo-namespace-install.yaml
  amun/overlays/ocp4-stage/amun-inspection/argo-namespace-install.yaml
  amun/overlays/prod/amun-inspection/argo-namespace-install.yaml
  core/overlays/cnv-prod/backend-prod/argo-namespace-install.yaml
  core/overlays/cnv-prod/middletier-prod/argo-namespace-install.yaml
Labels: approved, size/M

#1143 updated new kafka certs for the prod
  core/overlays/cnv-prod/common/secrets.enc.yaml
Labels: approved, size/L

#1144 Suspend prescription-sync-job in prod and stage
  prescription-sync-job/overlays/cnv-prod/cronjob.yaml
  prescription-sync-job/overlays/ocp4-stage/cronjob.yaml
Labels: approved, size/XS

#1145 created separate overlay for zero-test
  core/overlays/zero-test/argo-namespace-install.yaml
  core/overlays/zero-test/argo-ui-route.yaml
  core/overlays/zero-test/argo-workflow-controller-metrics.yaml
  core/overlays/zero-test/argo-workflows/send-message.yaml
  core/overlays/zero-test/argo-workflows/send-messages.yaml
  core/overlays/zero-test/buildConfig.yaml
  core/overlays/zero-test/configmaps.yaml
  core/overlays/zero-test/imagestreamtags.yaml
  core/overlays/zero-test/job-generate-name.yaml
  core/overlays/zero-test/kustomization.yaml
  core/overlays/zero-test/pgbouncer.yaml
  core/overlays/zero-test/postgresql-metrics-exporter.yaml
  core/overlays/zero-test/postgresql.yaml
  core/overlays/zero-test/secret-generator.yaml
  core/overlays/zero-test/secrets.enc.yaml
  core/overlays/zero-test/thoth-notification.yaml
Labels: approved, size/XXL

#1104 add message metrics deployment
  investigator_message_metrics/README.md
  investigator_message_metrics/base/deploymentconfig.yaml
  investigator_message_metrics/base/kustomization.yaml
  investigator_message_metrics/base/route.yaml
  investigator_message_metrics/base/service.yaml
  investigator_message_metrics/base/serviceaccount.yaml
  investigator_message_metrics/overlays/ocp4-stage/job-generate-name.yaml
  investigator_message_metrics/overlays/ocp4-stage/kustomization.yaml
  investigator_message_metrics/overlays/ocp4-stage/thoth-notification.yaml
  investigator_message_metrics/overlays/test/deploymentconfig.yaml
  investigator_message_metrics/overlays/test/job-generate-name.yaml
  investigator_message_metrics/overlays/test/kustomization.yaml
  investigator_message_metrics/overlays/test/thoth-notification.yaml
  investigator_message_metrics/overlays/zero-prod/job-generate-name.yaml
  investigator_message_metrics/overlays/zero-prod/kustomization.yaml
  investigator_message_metrics/overlays/zero-prod/thoth-notification.yaml
Labels: approved, size/XL

#1148 Zero test fix
  core/overlays/zero-test/argo-namespace-install.yaml
  core/overlays/zero-test/postgresql.yaml
Labels: approved, size/XS

#1150 updated the secrets based on the renew sops file
  chat-notification/overlays/test/secrets.enc.yaml
  kebechet/overlays/test/secrets.enc.yaml
  mi-scheduler/overlays/test/secrets.enc.yaml
Labels: approved, size/L

#1152 fix defaults
  slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml
  slo-reporter/overlays/zero-prod-ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1156 update the certs for the prow.thoth-station.ninja
  prow/overlays/cnv-prod/routes.enc.yaml
Labels: approved, size/L

#1157 bump up adviser to 0.27.0 for zero-prod
  adviser/overlays/cnv-prod/imagestreamtag.yaml
Labels: approved, size/XS

#1162 set prow ssh cerds for private repo support
  prow/overlays/cnv-prod/config.yaml
  prow/overlays/cnv-prod/secrets.enc.yaml
Labels: approved, lgtm, size/L

#1163 Add missing User API token
  user-api/base/deploymentconfig.yaml
Labels: approved, size/XS

#1164 Fix parameters in the template
  adviser/base/openshift-templates/adviser.yaml
  adviser/base/openshift-templates/provenance-checker.yaml
Labels: approved, size/XS

#1165 set different secret for app-secret from thoth token
  amun/overlays/cnv-prod/amun-api/secrets.enc.yaml
  amun/overlays/ocp4-stage/amun-api/secrets.enc.yaml
  amun/overlays/test/secrets.enc.yaml
  core/overlays/cnv-prod/common/secrets.enc.yaml
  core/overlays/ocp4-stage/common/secrets.enc.yaml
  core/overlays/test/secrets.enc.yaml
  core/overlays/zero-test/secrets.enc.yaml
  integration-tests/overlays/cnv-prod-ocp4-stage/secrets.enc.yaml
  integration-tests/overlays/ocp4-stage/secrets.enc.yaml
  integration-tests/overlays/test/secrets.enc.yaml
  management-api/base/deploymentconfig.yaml
  user-api/base/deploymentconfig.yaml
Labels: approved, size/XXL

#1146 Enable prescription sync job in stage environment
  prescription-sync-job/overlays/ocp4-stage/cronjob.yaml
Labels: approved, size/XS

#1167 Additionally restrict unauthenticated parts of the workflows
  adviser/base/openshift-templates/adviser.yaml
  adviser/base/openshift-templates/provenance-checker.yaml
Labels: approved, size/XS

#1168 Bump adviser to v0.28.0 in stage environment
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1170 Bump User API to v0.24.1 in stage environment
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1172 update integration test periodic
  .github/CODEOWNERS
  prow/overlays/cnv-prod/config.yaml
  prow/overlays/cnv-prod/integration-test-configmap.yaml
  prow/overlays/cnv-prod/kustomization.yaml
  prow/overlays/cnv-prod/secrets.enc.yaml
Labels: approved, size/L

#1174 bump up the investigator and messaging for the zero-test
  core/overlays/zero-test/imagestreamtags.yaml
Labels: approved, size/XS

#1175 bump up the user-api 0.24.3 in the prod
  user-api/overlays/cnv-prod/imagestreamtag.yaml
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1176 bump up the investigator and messaging for the prod
  core/overlays/cnv-prod/common/imagestreamtags.yaml
  core/overlays/ocp4-stage/common/imagestreamtags.yaml
Labels: approved, size/XS

#1177 updated the pull request template for thoth-application
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, size/S

#1180 Modify qeb-hwt to use thamos instead of messaging
  qeb-hwt-github-app/overlays/test/argo-workflows/qeb-hwt-integration.yaml
  qeb-hwt-github-app/overlays/test/openshift-templates/qeb-hwt.yaml
Labels: approved, size/M

#1173 Store in zero-prod on s3 in Operate First
  slo-reporter/overlays/zero-prod-ocp4-stage/configmap.yaml
  slo-reporter/overlays/zero-prod-ocp4-stage/secrets.enc.yaml
Labels: approved, size/XS

#1183 Pass constraints.txt as an input to adviser
  adviser/base/argo-workflows/advise.yaml
Labels: approved, size/XS

#1186 remove the expired gpg key from the sops config
  .sops.yaml
Labels: approved, size/XS

#1187 update secrets based on the zero prod cluster
  slo-reporter/overlays/zero-prod-ocp4-stage/secrets.enc.yaml
Labels: approved, size/M

#1189 update reporting components
  advise-reporter/base/cronjob.yaml
  advise-reporter/overlays/cnv-prod/imagestreamtag.yaml
  advise-reporter/overlays/ocp4-stage/imagestreamtag.yaml
  advise-reporter/overlays/test/buildConfig.yaml
  advise-reporter/overlays/test/cronjob.yaml
  slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml
  slo-reporter/overlays/zero-prod-ocp4-stage/imagestreamtag.yaml
Labels: approved, size/S

#1191 Bump advise-reporter-v0.7.4
  advise-reporter/overlays/cnv-prod/imagestreamtag.yaml
  advise-reporter/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1188 updated the environment docs with the database and extension
  docs/environments.md
  docs/thoth_release_procedure.md
  docs/thoth_s2i_procedure.md
Labels: approved, lgtm, size/M

#1190 add Kebechet slug to openshift templates (default null)
  kebechet/base/openshift-templates/kebechet.yaml
  kebechet/overlays/test/kebechet.yaml
Labels: approved, size/S

#1192 Revert "remove the expired gpg key from the sops config"
  .sops.yaml
Labels: approved, size/XS

#1194 Bump slo-reporter to v0.14.1
  slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml
  slo-reporter/overlays/zero-prod-ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1206 Deploy user-api v0.25.0 to test environment
  user-api/overlays/test/imagestreamtag.yaml
Labels: approved, size/XS

#1209 setup scrum-bot to the application component
  sefkhet-abwy/overlays/bot/configmap.yaml
  sefkhet-abwy/overlays/bot/imagestreamtag.yaml
  sefkhet-abwy/overlays/bot/kustomization.yaml
  sefkhet-abwy/overlays/bot/secret-generator.yaml
  sefkhet-abwy/overlays/bot/secrets.enc.yaml
  sefkhet-abwy/overlays/bot/thoth-friday-scrum-cronjob.yaml
  sefkhet-abwy/overlays/bot/thoth-scrum-cronjob.yaml
Labels: approved, size/L

#1201 Run kebechet-run-results only if authentication was done
  adviser/base/openshift-templates/adviser.yaml
Labels: approved, size/XS

#1207 Bump user-api to v0.25.0 in stage environment
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1205 Bump adviser to v0.29.0 in stage environment
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#1211 Bump up versions for component in stage
  amun/overlays/ocp4-stage/amun-api/message-imagestream.yaml
  amun/overlays/test/message-imagestream.yaml
  core/overlays/ocp4-stage/common/imagestreamtags.yaml
  core/overlays/zero-test/imagestreamtags.yaml
  graph-sync/overlays/ocp4-stage/imagestreamtag.yaml
  integration-tests/overlays/ocp4-stage/imagestreamtag.yaml
  kebechet/overlays/test/imagestreamtag.yaml
  mi-scheduler/overlays/ocp4-stage/imagestreamtag.yaml
  security-indicators/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/S

#1213 Push new mi release
  mi-scheduler/overlays/test/imagestreamtag.yaml
Labels: approved, size/XS

#1216 feat(operate-first): Make tide to require lgtm label on merge
  prow/overlays/cnv-prod/config.yaml
Labels: approved, size/S
