Repository thoth-station/thoth-application, pull requests merged in 2022-04, with the labels that each got.

#2483 Keep DM sync up-to-date which uses graph-sync image
  amun/overlays/aws-prod/amun-api/argo-workflows/sync-template.yaml
  amun/overlays/aws-prod/amun-api/kustomization.yaml
  amun/overlays/aws-prod/amun-inspection/kustomization.yaml
  amun/overlays/moc-prod/amun-api/argo-workflows/sync-template.yaml
  amun/overlays/moc-prod/amun-api/kustomization.yaml
  amun/overlays/moc-prod/amun-inspection/kustomization.yaml
  amun/overlays/ocp4-stage/amun-api/argo-workflows/sync-template.yaml
  amun/overlays/ocp4-stage/amun-api/kustomization.yaml
  amun/overlays/ocp4-stage/amun-inspection/kustomization.yaml
Labels: size/M, approved

#2486 Upgrade kafka to version 3.0.0 for strimzi 0.26.0
  kafka/base/kafka-metrics.yaml
  kafka/base/kustomization.yaml
  kafka/base/thoth-kafka.yaml
  kafka/base/zookeeper-metrics.yaml
  kafka/overlays/ocp-stage/deployment.yaml
  kafka/overlays/ocp-stage/kustomization.yaml
  kafka/overlays/zero-prod/deployment.yaml
  kafka/overlays/zero-prod/kustomization.yaml
Labels: approved, size/L

#2487 Upgrade the kafka secrets for the stage deployments
  amun/overlays/ocp4-stage/amun-api/secrets.enc.yaml
  amun/overlays/test/secrets.enc.yaml
  core/overlays/ocp4-stage/common/secrets.enc.yaml
  core/overlays/test/secrets.enc.yaml
Labels: approved, size/XL

#2490 Fix the stage deployment of dm graph-sync
  amun/overlays/ocp4-stage/amun-api/kustomization.yaml
Labels: approved, size/XS

#2492 Fix the configmap in amun-api
  amun/overlays/aws-prod/amun-api/kustomization.yaml
  amun/overlays/moc-prod/amun-api/kustomization.yaml
  amun/overlays/ocp4-stage/amun-api/kustomization.yaml
Labels: approved, size/XS

#2495 Bump Amun API to v0.10.2 in stage environment
  amun/overlays/ocp4-stage/amun-api/imagestreamtag.yaml
Labels: approved, size/XS

#2499 Bump Amun API to v0.10.3 in stage
  amun/overlays/ocp4-stage/amun-api/imagestreamtag.yaml
Labels: approved, size/XS

#2500 Bump Amun API to v0.10.4 in stage
  amun/overlays/ocp4-stage/amun-api/imagestreamtag.yaml
Labels: approved, size/XS

#2502 Update mi to 2.10.7 and mi-scheduler to 1.7.5
  mi-scheduler/overlays/test/imagestreamtag.yaml
Labels: approved, size/XS

#2504 Bump integration-tests to v0.11.1
  integration-tests/overlays/aws-prod-ocp4-stage/imagestreamtag.yaml
  integration-tests/overlays/moc-prod-ocp4-stage/imagestreamtag.yaml
  integration-tests/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2505 Bump management-api to v0.18.2 in stage
  management-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2507 Bump Amun API to v0.10.5
  amun/overlays/ocp4-stage/amun-api/imagestreamtag.yaml
Labels: approved, size/XS

#2510 Authorize maya to view/edit secrets and update prescription secrets
  .sops.yaml
  prescriptions-refresh-job/base/secret.enc.yaml
Labels: approved, size/L

#2506 Bump management-api to v0.18.3 in stage
  management-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2509 Update pre-commit image tag
  .prow.yaml
Labels: approved, size/XS

#2514 Bump integration tests to v0.11.2 in stage
  integration-tests/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2517 Increase the parallel wf run limit and reduce ttl in stage for backend
  core/overlays/aws-prod/backend-prod/configmaps.yaml
  core/overlays/ocp4-stage/backend-stage/configmaps.yaml
Labels: approved, size/S

#2518 Update mi-scheduler to v1.7.6
  mi-scheduler/overlays/test/imagestreamtag.yaml
Labels: approved, size/XS

#2519 Update certs for the stage and test apps
  amun/overlays/ocp4-stage/amun-api/route.enc.yaml
  amun/overlays/ocp4-stage/amun-api/secrets.enc.yaml
  amun/overlays/test/route.enc.yaml
  amun/overlays/test/secrets.enc.yaml
  management-api/overlays/ocp4-stage/route.enc.yaml
  management-api/overlays/test/route.enc.yaml
  user-api/overlays/ocp4-stage/route.enc.yaml
  user-api/overlays/test/route.enc.yaml
Labels: approved, size/XXL

#2520 Bump up the images based on the version update v2022.04.18
  amun/overlays/aws-prod/amun-api/imagestreamtag.yaml
  amun/overlays/moc-prod/amun-api/imagestreamtag.yaml
  core/overlays/aws-prod/common/imagestreamtags.yaml
  core/overlays/moc-prod/common/imagestreamtags.yaml
  core/overlays/ocp4-stage/common/imagestreamtags.yaml
  integration-tests/overlays/aws-prod-ocp4-stage/imagestreamtag.yaml
  integration-tests/overlays/moc-prod-ocp4-stage/imagestreamtag.yaml
  management-api/overlays/aws-prod/imagestreamtag.yaml
  management-api/overlays/moc-prod/imagestreamtag.yaml
  user-api/overlays/aws-prod/imagestreamtag.yaml
  user-api/overlays/moc-prod/imagestreamtag.yaml
Labels: approved, size/S

#2526 [prow] Fix typo in current milestone configuration
  prow/overlays/smaug/plugins.yaml
Labels: approved, size/XS
