Repository thoth-station/thoth-application, pull requests merged in 2022-01, with the labels that each got.

#2239 Update sprint prod release template
  .github/ISSUE_TEMPLATE/sprint-prod-release.md
Labels: approved, size/XS

#2235 Solver error classifier yaml files
  solver-error-classifier-job/base/cronjob.yaml
  solver-error-classifier-job/base/imagestream.yaml
  solver-error-classifier-job/base/kustomization.yaml
  solver-error-classifier-job/overlays/test/buildConfig.yaml
  solver-error-classifier-job/overlays/test/cronjob.yaml
  solver-error-classifier-job/overlays/test/imagestreamtag.yaml
  solver-error-classifier-job/overlays/test/kustomization.yaml
  solver-error-classifier-job/overlays/test/thoth-notification.yaml
Labels: approved, size/L

#2237 Bump user-api to v0.31.0 in stage
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2240 Bump user-api to v0.32.0 in stage environment
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2241 Bump integration-tests to v0.9.0 in stage
  integration-tests/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2242 Bump integration-tests for moc-prod
  integration-tests/overlays/moc-prod-ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2244 Synced up the version of grafana dashboard with the listed dashboard
  grafana-dashboard/overlays/aws-prod/argocd.json
  grafana-dashboard/overlays/aws-prod/thoth-kafka-argo-metrics.json
  grafana-dashboard/overlays/aws-prod/thoth-knowledge-graph-content-metrics.json
  grafana-dashboard/overlays/aws-prod/thoth-postgresql-metrics.json
  grafana-dashboard/overlays/aws-prod/thoth-service-metrics.json
  grafana-dashboard/overlays/aws-prod/thoth-sli-slo.json
  grafana-dashboard/overlays/aws-prod/thoth-user-api-metrics.json
  grafana-dashboard/overlays/aws-prod/thoth-workflow-controllers-metrics.json
  grafana-dashboard/overlays/moc-prod/argocd.json
  grafana-dashboard/overlays/moc-prod/thoth-kafka-argo-metrics.json
  grafana-dashboard/overlays/moc-prod/thoth-knowledge-graph-content-metrics.json
  grafana-dashboard/overlays/moc-prod/thoth-postgresql-metrics.json
  grafana-dashboard/overlays/moc-prod/thoth-service-metrics.json
  grafana-dashboard/overlays/moc-prod/thoth-sli-slo.json
  grafana-dashboard/overlays/moc-prod/thoth-user-api-metrics.json
  grafana-dashboard/overlays/moc-prod/thoth-workflow-controllers-metrics.json
Labels: approved, size/XXL

#2247 Adjust links to Thoth search UI based on deployment
  adviser/base/configmap.yaml
  adviser/base/openshift-templates/adviser.yaml
  adviser/overlays/aws-prod/configmap.yaml
  adviser/overlays/moc-prod/configmap.yaml
  adviser/overlays/ocp4-stage/configmap.yaml
Labels: approved, size/XS

#2246 Disable insecure agro artifact submission
  core/overlays/moc-prod/backend-prod/configmaps.yaml
  core/overlays/moc-prod/middletier-prod/configmaps.yaml
Labels: approved, size/XS

#2248 Remove the required context as the presubmit are not run always
  prow/overlays/smaug/config.yaml
Labels: approved, size/XS

#2250 Place adviser search URL configuration to environment section
  adviser/base/argo-workflows/advise.yaml
  adviser/base/openshift-templates/adviser.yaml
Labels: approved, size/S

#2254 Introduce image patch for the amun deploymentconfig
  amun/overlays/aws-prod/amun-api/kustomization.yaml
  amun/overlays/moc-prod/amun-api/kustomization.yaml
  amun/overlays/ocp4-stage/amun-api/kustomization.yaml
  amun/overlays/test/kustomization.yaml
Labels: approved, size/S

#2252 Bump adviser to v0.50.0 in stage environment
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2253 Bump metrics-exporter to v0.20.0 for Kebechet monitoring dashboard
  metrics-exporter/overlays/aws-prod/imagestreamtag.yaml
  metrics-exporter/overlays/moc-prod/imagestreamtag.yaml
  metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2255 Moved the logging-no-json env var to amun cm
  amun/base/deploymentconfig.yaml
  amun/overlays/aws-prod/amun-api/configmaps.yaml
  amun/overlays/moc-prod/amun-api/configmaps.yaml
  amun/overlays/ocp4-stage/amun-api/configmaps.yaml
  amun/overlays/test/configmaps.yaml
Labels: approved, size/XS

#2251 Bump user-api to v0.33.0 in stage
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2257 Bump user-api to v0.33.1 in stage environment
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2256 Bump workflow helpers to update schema in stage
  core/overlays/ocp4-stage/common/imagestreamtags.yaml
Labels: approved, size/XS

#2260 Add metrics to kebechet-run-results task
  adviser/base/argo-workflows/kebechet-run-results.yaml
Labels: size/M, approved

#2261 Add a triage-party view to highlight inconsistencies
  triage-party/overlays/moc/config.yaml
Labels: size/M, approved

#2263 Bump up the images based on the version update v2022.01.17
  adviser/overlays/aws-prod/imagestreamtag.yaml
  adviser/overlays/moc-prod/imagestreamtag.yaml
  amun/overlays/aws-prod/amun-api/imagestreamtag.yaml
  amun/overlays/moc-prod/amun-api/imagestreamtag.yaml
  core/overlays/aws-prod/common/imagestreamtags.yaml
  core/overlays/moc-prod/common/imagestreamtags.yaml
  core/overlays/ocp4-stage/common/imagestreamtags.yaml
  cve-update/overlays/aws-prod/imagestreamtag.yaml
  cve-update/overlays/moc-prod/imagestreamtag.yaml
  graph-backup-job/overlays/aws-prod/imagestreamtag.yaml
  graph-backup-job/overlays/moc-prod/imagestreamtag.yaml
  graph-metrics-exporter/overlays/aws-prod/imagestreamtag.yaml
  graph-metrics-exporter/overlays/moc-prod/imagestreamtag.yaml
  graph-refresh/overlays/aws-prod/imagestreamtag.yaml
  graph-refresh/overlays/moc-prod/imagestreamtag.yaml
  graph-sync/overlays/aws-prod/common/imagestreamtag.yaml
  graph-sync/overlays/moc-prod/common/imagestreamtag.yaml
  kebechet/overlays/aws-prod/imagestreamtag.yaml
  kebechet/overlays/moc-prod/imagestreamtag.yaml
  kebechet/overlays/ocp4-stage/imagestreamtag.yaml
  management-api/overlays/aws-prod/imagestreamtag.yaml
  management-api/overlays/moc-prod/imagestreamtag.yaml
  package-releases/overlays/aws-prod/imagestreamtag.yaml
  package-releases/overlays/moc-prod/imagestreamtag.yaml
Labels: size/M, approved

#2267 Update triage-party configuration with more views
  triage-party/overlays/moc/config.yaml
Labels: size/M, approved

#2271 Set the pulp sync job in stage cluster
  pulp-pypi-sync-job/overlays/ocp4-stage/cronjob.yaml
  pulp-pypi-sync-job/overlays/ocp4-stage/imagestreamtag.yaml
  pulp-pypi-sync-job/overlays/ocp4-stage/kustomization.yaml
  pulp-pypi-sync-job/overlays/ocp4-stage/thoth-notification.yaml
Labels: approved, size/XS

#2274 Bump up kebechet for fixing the release issue
  kebechet/overlays/aws-prod/imagestreamtag.yaml
  kebechet/overlays/moc-prod/imagestreamtag.yaml
  kebechet/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2276 Deploy pulp-metrics-exporter
  pulp-metrics-exporter/README.md
  pulp-metrics-exporter/application-stage.yaml
  pulp-metrics-exporter/base/configmap.yaml
  pulp-metrics-exporter/base/deploymentconfig.yaml
  pulp-metrics-exporter/base/imagestream.yaml
  pulp-metrics-exporter/base/kustomization.yaml
  pulp-metrics-exporter/base/route.yaml
  pulp-metrics-exporter/base/secret.yaml
  pulp-metrics-exporter/base/service.yaml
  pulp-metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
  pulp-metrics-exporter/overlays/ocp4-stage/kustomization.yaml
  pulp-metrics-exporter/overlays/ocp4-stage/secret-generator.yaml
  pulp-metrics-exporter/overlays/ocp4-stage/secrets.enc.yaml
  pulp-metrics-exporter/overlays/ocp4-stage/thoth-notification.yaml
Labels: approved, size/L

#2277 Turn off auto reviewers in operate-first
  prow/overlays/smaug/plugins.yaml
Labels: approved, size/XS, lgtm

#2278 Bump up kebechet v1.7.3 for fixing the release issue
  kebechet/overlays/aws-prod/imagestreamtag.yaml
  kebechet/overlays/moc-prod/imagestreamtag.yaml
  kebechet/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2280 Include the secrets required for the pulp-metrics-exporter
  pulp-metrics-exporter/base/kustomization.yaml
  pulp-metrics-exporter/base/secret.yaml
  pulp-metrics-exporter/overlays/ocp4-stage/secrets.enc.yaml
Labels: approved, size/L

#2279 Include the secrets required for the pulp-sync-job
  pulp-pypi-sync-job/overlays/ocp4-stage/imagestreamtag.yaml
  pulp-pypi-sync-job/overlays/ocp4-stage/kustomization.yaml
  pulp-pypi-sync-job/overlays/ocp4-stage/secret-generator.yaml
  pulp-pypi-sync-job/overlays/ocp4-stage/secrets.enc.yaml
  pulp-pypi-sync-job/overlays/test/imagestreamtag.yaml
  pulp-pypi-sync-job/overlays/test/kustomization.yaml
  pulp-pypi-sync-job/overlays/test/secret-generator.yaml
  pulp-pypi-sync-job/overlays/test/secrets.enc.yaml
Labels: approved, size/L

#2284 Clarify process for generating and publishing GPG keys
  docs/secret_management.md
Labels: size/M, approved, ok-to-test

#2286 Set up document sync job for the thoth-station
  document-sync-job/base/cronjob.yaml
  document-sync-job/base/imagestream.yaml
  document-sync-job/base/kustomization.yaml
  document-sync-job/base/secret-generator.yaml
  document-sync-job/base/secrets.enc.yaml
  document-sync-job/overlays/ocp4-stage/cronjob.yaml
  document-sync-job/overlays/ocp4-stage/imagestreamtag.yaml
  document-sync-job/overlays/ocp4-stage/kustomization.yaml
  document-sync-job/overlays/ocp4-stage/thoth-notification.yaml
  document-sync-job/overlays/test/cronjob.yaml
  document-sync-job/overlays/test/imagestreamtag.yaml
  document-sync-job/overlays/test/kustomization.yaml
  document-sync-job/overlays/test/thoth-notification.yaml
Labels: approved, size/L

#2287 Add gpg key for sops
  .sops.yaml
Labels: approved, size/XS

#2289 sync up secret based on new gpg key addition
  core/overlays/aws-prod/common/secrets.enc.yaml
  core/overlays/moc-prod/common/secrets.enc.yaml
  core/overlays/ocp4-stage/common/secrets.enc.yaml
  slo-reporter/overlays/moc-prod-ocp4-stage/secrets.enc.yaml
  slo-reporter/overlays/ocp4-stage/secrets.enc.yaml
Labels: approved, size/XL

#2285 Clean up non managed overlays from thoth-station
  kebechet/overlays/bot/configmap.yaml
  kebechet/overlays/bot/imagestreamtag.yaml
  kebechet/overlays/bot/kebechet-aicoe-cronjob.yaml
  kebechet/overlays/bot/kebechet-thoth-cronjob.yaml
  kebechet/overlays/bot/kustomization.yaml
  kebechet/overlays/bot/secret-generator.yaml
  kebechet/overlays/bot/secrets.enc.yaml
  kebechet/overlays/bot/thoth-notification.yaml
  prescriptions-refresh-job/overlays/moc/cronworkflow.yaml
  prescriptions-refresh-job/overlays/moc/imagestreamtag.yaml
  prescriptions-refresh-job/overlays/moc/kustomization.yaml
  prescriptions-refresh-job/overlays/moc/thoth-notification.yaml
  pulp-opf/overlays/moc/kustomization.yaml
  pulp-opf/overlays/moc/routes.yaml
  sefkhet-abwy-chatbot/overlays/rh-us-east-1/kustomization.yaml
  sefkhet-abwy-chatbot/overlays/rh-us-east-1/secret-generator.yaml
  sefkhet-abwy-chatbot/overlays/rh-us-east-1/secrets.enc.yaml
  user-api/overlays/paas/imagestreamtag.yaml
  user-api/overlays/paas/kustomization.yaml
  user-api/overlays/paas/resources_patch.yaml
  user-api/overlays/paas/route.yaml
Labels: approved, size/XL

#2291 updates certs for the stage routes
  amun/overlays/ocp4-stage/amun-api/route.enc.yaml
  amun/overlays/test/route.enc.yaml
  management-api/overlays/ocp4-stage/route.enc.yaml
  management-api/overlays/test/route.enc.yaml
  sefkhet-abwy-chatbot/overlays/moc/kustomization.yaml
  sefkhet-abwy-chatbot/overlays/moc/route.yaml
  sefkhet-abwy-chatbot/overlays/moc/route53.enc.yaml
  sefkhet-abwy-chatbot/overlays/moc/secret-generator.yaml
  user-api/overlays/ocp4-stage/route.enc.yaml
  user-api/overlays/test/route.enc.yaml
Labels: approved, size/XXL

#2292 patch the buildlog parser image
  buildlog-parser/base/argo-workflows/buildlog-parser.yaml
  buildlog-parser/overlays/moc-prod/kustomization.yaml
  buildlog-parser/overlays/ocp4-stage/kustomization.yaml
  buildlog-parser/overlays/test/kustomization.yaml
Labels: size/M, approved

#2293 Fix labels in alarms
  monitoring/overlays/aws-prod/alerting-rules.yaml
  monitoring/overlays/moc-prod/alerting-rules.yaml
Labels: size/M, approved
