Repository thoth-station/thoth-application, pull requests merged in 2022-07, with the labels that each got.

#2603 Temporarily suspend prescriptions
  prescriptions-refresh-job/overlays/ocp4-stage/cronworkflow.yaml
Labels: size/S

#2608 Bump management-api to v0.18.5 in stage
  management-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS, lgtm

#2610 Include the thoth-advise-metadata env to the kebechet-run-result
  adviser/base/argo-workflows/kebechet-run-results.yaml
Labels: approved, size/XS

#2613 :arrow_up: Bump up the versions for the release of v2022.07.11
  kebechet/overlays/aws-prod/imagestreamtag.yaml
  kebechet/overlays/moc-prod/imagestreamtag.yaml
  kebechet/overlays/ocp4-stage/imagestreamtag.yaml
  management-api/overlays/aws-prod/imagestreamtag.yaml
  management-api/overlays/moc-prod/imagestreamtag.yaml
  prescriptions-refresh-job/overlays/ocp4-stage/imagestreamtag.yaml
  solver/overlays/aws-prod/imagestreamtag.yaml
  solver/overlays/moc-prod/imagestreamtag.yaml
  solver/overlays/test/imagestreamtag.yaml
  user-api/overlays/aws-prod/imagestreamtag.yaml
  user-api/overlays/moc-prod/imagestreamtag.yaml
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: size/M, approved
