Repository thoth-station/thoth-application, pull requests merged in 2022-10, with the labels that each got.

#2666 :turtle: Use aws s3 for moc deployments
  amun/overlays/moc-prod/amun-api/secrets.enc.yaml
  amun/overlays/moc-prod/common/configmaps.yaml
  core/overlays/moc-prod/common/configmaps.yaml
  core/overlays/moc-prod/common/secrets.enc.yaml
Labels: approved, size/XL

#2668 :ship: Bump up version of the updated component in release v2022.10.03
  graph-sync/overlays/moc-prod/common/imagestreamtag.yaml
  management-api/overlays/moc-prod/imagestreamtag.yaml
  prescriptions-refresh-job/overlays/ocp4-stage/imagestreamtag.yaml
  purge-job/overlays/moc-prod/imagestreamtag.yaml
  solver/overlays/moc-prod/imagestreamtag.yaml
Labels: approved, size/S

#2672 Minor fixes for argo-workflow template send-webhooks
  adviser/base/openshift-templates/adviser.yaml
  core/base/argo-workflows/send-webhooks.yaml
  core/overlays/moc-prod/backend-prod/configmaps.yaml
  core/overlays/moc-prod/middletier-prod/configmaps.yaml
Labels: size/S

#2673 Patch image ref of send-webhook based on namespace
  core/overlays/moc-prod/backend-prod/kustomization.yaml
  core/overlays/moc-prod/middletier-prod/configmaps.yaml
  core/overlays/moc-prod/middletier-prod/kustomization.yaml
Labels: size/S

#2674 :whale: Update the certs for the stage and test urls
  amun/overlays/ocp4-stage/amun-api/route.enc.yaml
  amun/overlays/test/route.enc.yaml
  core/overlays/moc-prod/backend-prod/configmaps.yaml
  core/overlays/moc-prod/backend-prod/kustomization.yaml
  management-api/overlays/ocp4-stage/route.enc.yaml
  management-api/overlays/test/route.enc.yaml
  user-api/overlays/ocp4-stage/route.enc.yaml
  user-api/overlays/test/route.enc.yaml
Labels: approved, size/XXL

#2675 Update the investigator image with latest storages
  core/overlays/moc-prod/common/imagestreamtags.yaml
  core/overlays/ocp4-stage/common/imagestreamtags.yaml
Labels: approved, size/XS

#2676 fixed thoth search ur
  adviser/base/configmap.yaml
  adviser/overlays/moc-prod/configmap.yaml
  adviser/overlays/ocp4-stage/configmap.yaml
Labels: approved, size/XS, lgtm

#2661 Use emptydir for db pg_dump
  graph-backup-job/base/cronjob.yaml
  graph-backup-job/overlays/moc-prod/kustomization.yaml
  graph-backup-job/overlays/ocp4-stage/kustomization.yaml
  graph-backup-job/overlays/ocp4-stage/pvc.yaml
Labels: size/M, approved, lgtm

#2678 Bump up with version of management-api
  management-api/overlays/moc-prod/imagestreamtag.yaml
  management-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2679 :lock: Update the thanos reader token for slo-reporter
  core/overlays/moc-prod/common/secrets.enc.yaml
  slo-reporter/overlays/moc-prod-ocp4-stage/secrets.enc.yaml
Labels: approved, size/L

#2680 Update mi to 2.12.0 and mi-scheduler to 1.7.7
  mi-scheduler/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2681 Update mi to 2.12.0 and mi-s to 1.7.7 [test nmspc]
  mi-scheduler/overlays/test/imagestreamtag.yaml
Labels: approved, size/XS

#2682 :books: Updated and removed balrog panels from grafana dashboards
  grafana-dashboard/base/thoth-kafka-argo-metrics.json
  grafana-dashboard/base/thoth-knowledge-graph-content-metrics.json
  grafana-dashboard/base/thoth-postgresql-metrics.json
  grafana-dashboard/base/thoth-service-metrics.json
  grafana-dashboard/base/thoth-sli-slo.json
  grafana-dashboard/base/thoth-user-api-metrics.json
  grafana-dashboard/base/thoth-workflow-controllers-metrics.json
Labels: approved, size/L

#2683 :boat: Bump the version of integration-tests and solver
  .pre-commit-config.yaml
  .thoth.yaml
  OWNERS
  integration-tests/overlays/moc-prod-ocp4-stage/imagestreamtag.yaml
  integration-tests/overlays/ocp4-stage/imagestreamtag.yaml
  integration-tests/overlays/test/imagestreamtag.yaml
  solver/overlays/moc-prod/imagestreamtag.yaml
  solver/overlays/ocp4-stage/imagestreamtag.yaml
  solver/overlays/test/imagestreamtag.yaml
Labels: size/M, approved

#2684 :boat: Bump the version of graph-metrics-exporter
  graph-metrics-exporter/overlays/moc-prod/imagestreamtag.yaml
  graph-metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
Labels: size/XS

#2688 Update mi-scheduler to 1.7.8
  mi-scheduler/overlays/ocp4-stage/imagestreamtag.yaml
  mi-scheduler/overlays/test/imagestreamtag.yaml
Labels: approved, size/XS, lgtm

#2691 Bump prescriptions-refresh-job to v0.8.0 in ocp4-stage
  prescriptions-refresh-job/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS, lgtm

#2692 Revert to weekly scorecard prescriptions
  prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-scorecards.yaml
Labels: approved, size/XS, lgtm
