Repository thoth-station/thoth-application, pull requests merged in 2022-02, with the labels that each got.

#2296 Bump up the images based on the version update v2022.01.31
  advise-reporter/overlays/aws-prod/imagestreamtag.yaml
  advise-reporter/overlays/moc-prod/imagestreamtag.yaml
  advise-reporter/overlays/ocp4-stage/imagestreamtag.yaml
  core/overlays/aws-prod/common/imagestreamtags.yaml
  core/overlays/moc-prod/common/imagestreamtags.yaml
  core/overlays/ocp4-stage/common/imagestreamtags.yaml
  cve-update/overlays/aws-prod/imagestreamtag.yaml
  cve-update/overlays/moc-prod/imagestreamtag.yaml
  cve-update/overlays/ocp4-stage/imagestreamtag.yaml
  graph-backup-job/overlays/aws-prod/imagestreamtag.yaml
  graph-backup-job/overlays/moc-prod/imagestreamtag.yaml
  graph-backup-job/overlays/ocp4-stage/imagestreamtag.yaml
  graph-metrics-exporter/overlays/aws-prod/imagestreamtag.yaml
  graph-metrics-exporter/overlays/moc-prod/imagestreamtag.yaml
  graph-metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
  graph-refresh/overlays/aws-prod/imagestreamtag.yaml
  graph-refresh/overlays/moc-prod/imagestreamtag.yaml
  graph-refresh/overlays/ocp4-stage/imagestreamtag.yaml
  graph-sync/overlays/aws-prod/common/imagestreamtag.yaml
  graph-sync/overlays/moc-prod/common/imagestreamtag.yaml
  graph-sync/overlays/ocp4-stage/common/imagestreamtag.yaml
  management-api/overlays/aws-prod/imagestreamtag.yaml
  management-api/overlays/moc-prod/imagestreamtag.yaml
  management-api/overlays/ocp4-stage/imagestreamtag.yaml
  metrics-exporter/overlays/aws-prod/imagestreamtag.yaml
  metrics-exporter/overlays/moc-prod/imagestreamtag.yaml
  metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
  package-releases/overlays/aws-prod/imagestreamtag.yaml
  package-releases/overlays/moc-prod/imagestreamtag.yaml
  package-releases/overlays/ocp4-stage/imagestreamtag.yaml
  package-update/overlays/aws-prod/imagestreamtag.yaml
  package-update/overlays/moc-prod/imagestreamtag.yaml
  package-update/overlays/ocp4-stage/imagestreamtag.yaml
  revsolver/overlays/aws-prod/imagestreamtag.yaml
  revsolver/overlays/moc-prod/imagestreamtag.yaml
  revsolver/overlays/ocp4-stage/imagestreamtag.yaml
  slo-reporter/overlays/aws-prod-ocp4-stage/imagestreamtag.yaml
  slo-reporter/overlays/moc-prod-ocp4-stage/imagestreamtag.yaml
  slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml
  user-api/overlays/aws-prod/imagestreamtag.yaml
  user-api/overlays/moc-prod/imagestreamtag.yaml
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: size/M, approved

#2295 fix the pulp metrics exporter secrets
  pulp-metrics-exporter/overlays/ocp4-stage/secrets.enc.yaml
Labels: approved, size/L

#2300 Do not use port in instance name for Prometheus
  slo-reporter/overlays/aws-prod-ocp4-stage/configmap.yaml
Labels: approved, size/S

#2303 Fix postgresql grafana dashboard fieldlabel
  grafana-dashboard/overlays/aws-prod/thoth-postgresql-metrics.json
Labels: approved, size/XXL

#2302 Add pg dump missing alarm
  monitoring/overlays/aws-prod/alerting-rules.yaml
  monitoring/overlays/moc-prod/alerting-rules.yaml
Labels: size/M, approved

#2306 Bump metrics exporter to v0.20.2 in stage
  metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2309 Add bloat table or index alerts for prod
  monitoring/overlays/aws-prod/alerting-rules.yaml
  monitoring/overlays/moc-prod/alerting-rules.yaml
Labels: size/M, approved

#2299 Fix Grafana dashboards in prod
  grafana-dashboard/overlays/aws-prod/thoth-kafka-argo-metrics.json
  grafana-dashboard/overlays/aws-prod/thoth-knowledge-graph-content-metrics.json
  grafana-dashboard/overlays/aws-prod/thoth-service-metrics.json
  grafana-dashboard/overlays/aws-prod/thoth-sli-slo.json
Labels: approved, size/L

#2307 Bump user-api to v0.34.1 in stage
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2313 Bump user-api to v0.34.2 in stage
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2315 update pulp-pypi-sync-job image tag
  pulp-pypi-sync-job/overlays/test/imagestreamtag.yaml
Labels: approved, size/XS

#2311 Bump document-sync-job to v0.2.0 in stage environment
  document-sync-job/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2317 Bump user-api to v0.34.3 in stage
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2316 Bump user-api to v0.34.3 in prod
  user-api/overlays/aws-prod/imagestreamtag.yaml
  user-api/overlays/moc-prod/imagestreamtag.yaml
Labels: approved, size/XS, lgtm

#2319 Increase document-sync deadline to 12 hours
  document-sync-job/base/cronjob.yaml
Labels: approved, size/XS

#2320 Adjust sync concurrency based on urllib3 connection pool configured
  document-sync-job/base/cronjob.yaml
Labels: approved, size/XS

#2318 Respect JSON logging configuration
  pulp-pypi-sync-job/base/cronjob.yaml
Labels: approved, size/XS

#2310 Bump pulp-pypi-sync-job to v0.1.1 in stage
  pulp-pypi-sync-job/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2324 Increase document sync to 3 days
  document-sync-job/base/cronjob.yaml
Labels: approved, size/XS

#2325 Bump document-sync to v0.3.0 in stage environment
  document-sync-job/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2327 Increase memory for document-sync-job
  document-sync-job/base/cronjob.yaml
Labels: approved, size/XS

#2329 Bump user-api to v0.34.4 in stage environment
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS, lgtm

#2328 Supply configured solvers for document-sync to sync solvers
  document-sync-job/base/cronjob.yaml
Labels: approved, size/XS

#2332 Bump document-sync-job to v0.3.1 in stage
  document-sync-job/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2326 Save Pulp Grafana Dashboard
  grafana-dashboard/overlays/moc-prod/pulp-metrics.json
Labels: approved, size/XXL

#2330 Provide port configuration to all deployment configs
  amun/base/deploymentconfig.yaml
  build-watcher/base/deploymentconfig.yaml
  investigator/base/deploymentconfig.yaml
  investigator_message_metrics/base/deploymentconfig.yaml
  management-api/base/deploymentconfig.yaml
  metrics-exporter/base/deploymentconfig.yaml
  pulp-metrics-exporter/base/deploymentconfig.yaml
  sefkhet-abwy-chatbot/base/deploymentconfig.yaml
  sefkhet-abwy/base/deploymentconfig.yaml
  user-api/base/deploymentconfig.yaml
Labels: approved, size/S

#2335 feat(prow): Enable override in open-services-group
  prow/overlays/smaug/plugins.yaml
Labels: size/XS

#2337 Enable CVE update job in prod deployments
  cve-update/overlays/aws-prod/cronjob.yaml
  cve-update/overlays/moc-prod/cronjob.yaml
Labels: approved, size/XS

#2339 Bump solvers to v1.11.0 in stage environment
  solver/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2338 Bump adviser to v0.51.0 in stage environment
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2344 Bump investigator to v0.16.0 in stage
  core/overlays/ocp4-stage/common/imagestreamtags.yaml
Labels: approved, size/XS

#2336 Allow passing indexes where package dependencies should be looked up
  solver/base/openshift-templates/solve_and_sync-template.yaml
  solver/overlays/test/argo-workflows/solver-template.yaml
Labels: approved, size/S

#2345 Add missing dependency indexes env var for solver
  solver/base/argo-workflows/solver-template.yaml
Labels: size/XS

#2347 Add missing env variables for graph-metrics-exporter
  graph-metrics-exporter/base/cronjob.yaml
Labels: approved, size/S

#2349 Remove old solvers from deployment manifests
  solver/base/imagestreams.yaml
  solver/overlays/aws-prod/imagestreamtag.yaml
  solver/overlays/moc-prod/imagestreamtag.yaml
  solver/overlays/ocp4-stage/imagestreamtag.yaml
  solver/overlays/test/imagestreamtag.yaml
Labels: size/M, approved

#2353 :books: split the changelog per year
  CHANGELOG.md
  docs/previous_releases/CHANGELOG_2021.md
Labels: approved, size/XXL

#2354 :guardsman: Attach thanos querier secrets for metrics read
  core/overlays/aws-prod/common/secrets.enc.yaml
  core/overlays/moc-prod/common/secrets.enc.yaml
Labels: approved, size/L

#2356 Add a view for backlog refining to triage-party
  triage-party/overlays/moc/config.yaml
Labels: approved

#2360 :fire: patch the prometheus url towards thanos querier
  amun/overlays/aws-prod/amun-api/configmaps.yaml
  amun/overlays/moc-prod/amun-api/configmaps.yaml
  core/overlays/aws-prod/common/configmaps.yaml
Labels: approved, size/S

#2355 Bump graph metrics exporter to v0.6.1
  graph-metrics-exporter/overlays/aws-prod/imagestreamtag.yaml
  graph-metrics-exporter/overlays/moc-prod/imagestreamtag.yaml
  graph-metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2364 triage-party: simplify the daily collection
  triage-party/overlays/moc/config.yaml
Labels: size/M, approved

#2365 :ship: Bump up the amun-api image to v0.10.1
  amun/overlays/aws-prod/amun-api/imagestreamtag.yaml
  amun/overlays/moc-prod/amun-api/imagestreamtag.yaml
  amun/overlays/ocp4-stage/amun-api/imagestreamtag.yaml
Labels: approved

#2323 Perform syncs of documents that are recent
  document-sync-job/base/cronjob.yaml
Labels: approved, size/XS

#2312 Split prescriptions-refresh CronWorkflow to multiple CronWorkflows
  prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-gh.yaml
  prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-image-analysis.yaml
  prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-pg.yaml
  prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-pypi.yaml
  prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-quay.yaml
  prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-scorecards.yaml
  prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh.yaml
  prescriptions-refresh-job/base/big-query-service-account.yaml
  prescriptions-refresh-job/base/kustomization.yaml
  prescriptions-refresh-job/base/secret-generator.yaml
  prescriptions-refresh-job/base/secrets.enc.yaml
  prescriptions-refresh-job/overlays/ocp4-stage/cronworkflow.yaml
  prescriptions-refresh-job/overlays/ocp4-stage/kustomization.yaml
  prescriptions-refresh-job/overlays/test/cronworkflow.yaml
  prescriptions-refresh-job/overlays/test/kustomization.yaml
Labels: approved, size/XXL

#2369 Bump integration-tests to v0.9.1 in ocp4-stage
  integration-tests/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2370 Bump integration-tests to v0.9.1 in moc-prod
  integration-tests/overlays/moc-prod-ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2371 Bump user-api to v0.34.6 in stage
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2342 Add stress-tests cronjob
  stress-tests/base/configmap.yaml
  stress-tests/base/cronjob.yaml
  stress-tests/base/imagestream.yaml
  stress-tests/base/kustomization.yaml
  stress-tests/overlays/test/configmap.yaml
  stress-tests/overlays/test/cronjob.yaml
  stress-tests/overlays/test/imagestreamtag.yaml
  stress-tests/overlays/test/kustomization.yaml
  stress-tests/overlays/test/thoth-notification.yaml
Labels: approved, size/L

#2376 Fix the prow with Thoth OBC from rick cluster
  prow/base/statusreconciler.yaml
  prow/base/tide.yaml
  prow/overlays/smaug/config.yaml
  prow/overlays/smaug/secrets.enc.yaml
Labels: size/L

#2374 Bump user-api to v0.34.7 in stage environment
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2377 Bump integration-tests to v0.9.2 in moc-prod-ocp4-stage
  integration-tests/overlays/moc-prod-ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2378 Bump integration-tests to v0.9.2 in ocp4-stage
  integration-tests/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2379 Bump package-releases to v0.11.8 in stage environment
  package-releases/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2380 Bump adviser to v0.51.1 in stage environment
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2381 Fix integration-tests OOM
  integration-tests/base/cronjob.yaml
Labels: approved, size/XS

#2362 Merge overlays dashboards using variables
  grafana-dashboard/README.md
  grafana-dashboard/base/pulp-metrics.json
  grafana-dashboard/base/thoth-kafka-argo-metrics.json
  grafana-dashboard/base/thoth-knowledge-graph-content-metrics.json
  grafana-dashboard/base/thoth-posgresql-metrics.json
  grafana-dashboard/base/thoth-service-metrics.json
  grafana-dashboard/base/thoth-sli-slo.json
  grafana-dashboard/base/thoth-user-api-metrics.json
  grafana-dashboard/base/thoth-workflow-controller-metrics.json
  grafana-dashboard/overlays/aws-prod/thoth-kafka-argo-metrics.json
  grafana-dashboard/overlays/aws-prod/thoth-knowledge-graph-content-metrics.json
  grafana-dashboard/overlays/aws-prod/thoth-service-metrics.json
  grafana-dashboard/overlays/aws-prod/thoth-user-api-metrics.json
  grafana-dashboard/overlays/aws-prod/thoth-workflow-controllers-metrics.json
  grafana-dashboard/overlays/moc-prod/thoth-postgresql-metrics.json
  grafana-dashboard/overlays/moc-prod/thoth-service-metrics.json
  grafana-dashboard/overlays/moc-prod/thoth-sli-slo.json
  grafana-dashboard/overlays/moc-prod/thoth-user-api-metrics.json
  grafana-dashboard/overlays/moc-prod/thoth-workflow-controllers-metrics.json
Labels: approved, size/XXL

#2372 bounce integration test within prow config
  prow/overlays/smaug/config.yaml
Labels: approved, size/XS

#2383 :hatched_chick: Prow storage is set to the respective cluster
  prow/base/statusreconciler.yaml
  prow/base/tide.yaml
  prow/overlays/smaug/config.yaml
  prow/overlays/smaug/secrets.enc.yaml
Labels: approved, size/L

#2385 Bump solver-rhel-8-py38 to v1.11.2 in test environment
  solver/overlays/test/imagestreamtag.yaml
Labels: approved, size/XS

#2387 Add username to approvers
  OWNERS
Labels: approved, size/XS

#2386 Increase deadline for integration-tests
  integration-tests/base/cronjob.yaml
Labels: approved, size/XS

#2384 Bump solvers to v1.11.2 in stage
  solver/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2389 :ship: Bump up the images based on the version update v2022.02.28
  metrics-exporter/overlays/aws-prod/imagestreamtag.yaml
  metrics-exporter/overlays/moc-prod/imagestreamtag.yaml
  metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
  user-api/overlays/aws-prod/imagestreamtag.yaml
  user-api/overlays/moc-prod/imagestreamtag.yaml
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/S

#2392 Fix thoth milestones
  prow/overlays/smaug/plugins.yaml
Labels: size/S

#2388 Increase memory for prescriptions-refresh jobs
  prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-gh.yaml
  prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-image-analysis.yaml
  prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-pg.yaml
  prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-pypi.yaml
  prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-quay.yaml
  prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-scorecards.yaml
Labels: approved, size/S

#2396 Bump adviser to v0.52.0 in stage environment
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2395 Set up adviser memory optimizer
  adviser/base/argo-workflows/advise.yaml
Labels: approved, size/XS
