Repository thoth-station/thoth-application, pull requests merged in 2022-05, with the labels that each got.

#2460 adding documentation on creating new integration test overlays
  integration-tests/README.md
Labels: size/M, approved, lgtm

#2525 Start the sync of the fedora35 python 3.10 solvers
  core/overlays/aws-prod/common/configmaps.yaml
  core/overlays/moc-prod/common/configmaps.yaml
  core/overlays/ocp4-stage/common/configmaps.yaml
  solver/overlays/aws-prod/imagestreamtag.yaml
  solver/overlays/moc-prod/imagestreamtag.yaml
  solver/overlays/ocp4-stage/imagestreamtag.yaml
  solver/overlays/test/imagestreamtag.yaml
Labels: size/M, approved

#2543 feat(prow): OSG Peribolos needs Tide stop skipping checks
  prow/overlays/smaug/config.yaml
Labels: approved, size/XS

#2546 Patch prescription refresh job secrets for big query
  prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-pypi.yaml
  prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-scorecards.yaml
  prescriptions-refresh-job/base/secret.enc.yaml
  prescriptions-refresh-job/base/secrets.enc.yaml
  prescriptions-refresh-job/overlays/test/secrets.env.yaml
Labels: approved, size/XL

#2548 feat: Disable branch protection on peribolos repo
  prow/overlays/smaug/config.yaml
Labels: approved, size/XS, lgtm

#2547 [prow] Add an additional 'epic' label
  prow/overlays/smaug/plugins.yaml
Labels: approved, size/XS

#2524 creating cron-workflow to invoke job template for the sync-job
  sync-job/base/cron-workflow.yaml
  sync-job/base/kustomization.yaml
  sync-job/base/workflow-template.yaml
  sync-job/overlays/common/imagestreamtag.yaml
  sync-job/overlays/common/kustomization.yaml
  sync-job/overlays/prod-to-stage/kustomization.yaml
  sync-job/overlays/stage-to-prod/kustomization.yaml
Labels: approved, size/L, lgtm

#2550 Bump up the images based on the version update v2022.05.09
  advise-reporter/overlays/aws-prod/imagestreamtag.yaml
  advise-reporter/overlays/moc-prod/imagestreamtag.yaml
  advise-reporter/overlays/ocp4-stage/imagestreamtag.yaml
  core/overlays/aws-prod/common/imagestreamtags.yaml
  core/overlays/moc-prod/common/imagestreamtags.yaml
  core/overlays/ocp4-stage/common/imagestreamtags.yaml
  cve-update/overlays/aws-prod/imagestreamtag.yaml
  cve-update/overlays/moc-prod/imagestreamtag.yaml
  cve-update/overlays/ocp4-stage/imagestreamtag.yaml
  cve-update/overlays/test/imagestreamtag.yaml
  graph-backup-job/overlays/aws-prod/imagestreamtag.yaml
  graph-backup-job/overlays/moc-prod/imagestreamtag.yaml
  graph-backup-job/overlays/ocp4-stage/imagestreamtag.yaml
  graph-metrics-exporter/overlays/aws-prod/imagestreamtag.yaml
  graph-metrics-exporter/overlays/moc-prod/imagestreamtag.yaml
  graph-metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
  graph-refresh/overlays/aws-prod/imagestreamtag.yaml
  graph-refresh/overlays/moc-prod/imagestreamtag.yaml
  graph-refresh/overlays/ocp4-stage/imagestreamtag.yaml
  graph-sync/overlays/aws-prod/common/imagestreamtag.yaml
  graph-sync/overlays/moc-prod/common/imagestreamtag.yaml
  graph-sync/overlays/ocp4-stage/common/imagestreamtag.yaml
  management-api/overlays/aws-prod/imagestreamtag.yaml
  management-api/overlays/moc-prod/imagestreamtag.yaml
  management-api/overlays/ocp4-stage/imagestreamtag.yaml
  metrics-exporter/overlays/aws-prod/imagestreamtag.yaml
  metrics-exporter/overlays/moc-prod/imagestreamtag.yaml
  metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
  package-releases/overlays/aws-prod/imagestreamtag.yaml
  package-releases/overlays/moc-prod/imagestreamtag.yaml
  package-releases/overlays/ocp4-stage/imagestreamtag.yaml
  package-update/overlays/aws-prod/imagestreamtag.yaml
  package-update/overlays/moc-prod/imagestreamtag.yaml
  package-update/overlays/ocp4-stage/imagestreamtag.yaml
  revsolver/overlays/aws-prod/imagestreamtag.yaml
  revsolver/overlays/moc-prod/imagestreamtag.yaml
  revsolver/overlays/ocp4-stage/imagestreamtag.yaml
  slo-reporter/overlays/aws-prod-ocp4-stage/imagestreamtag.yaml
  slo-reporter/overlays/moc-prod-ocp4-stage/imagestreamtag.yaml
  slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml
  user-api/overlays/aws-prod/imagestreamtag.yaml
  user-api/overlays/moc-prod/imagestreamtag.yaml
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: size/M, approved

#2549 adding argo workflow and modifying template
  sync-job/base/workflow-template.yaml
  sync-job/base/workflow.yaml
Labels: size/M, approved

#2559 Patch the messaging image for all the environments
  amun/overlays/aws-prod/amun-api/kustomization.yaml
  amun/overlays/aws-prod/amun-api/message-imagestream.yaml
  amun/overlays/moc-prod/amun-api/kustomization.yaml
  amun/overlays/moc-prod/amun-api/message-imagestream.yaml
  amun/overlays/ocp4-stage/amun-api/kustomization.yaml
  amun/overlays/ocp4-stage/amun-api/message-imagestream.yaml
  amun/overlays/test/kustomization.yaml
  amun/overlays/test/message-imagestream.yaml
Labels: approved, size/L

#2560 Upgrade workflow-helper and graph-sync for sync fix
  core/overlays/aws-prod/common/imagestreamtags.yaml
  core/overlays/moc-prod/common/imagestreamtags.yaml
  core/overlays/ocp4-stage/common/imagestreamtags.yaml
  graph-sync/overlays/aws-prod/common/imagestreamtag.yaml
  graph-sync/overlays/moc-prod/common/imagestreamtag.yaml
  graph-sync/overlays/ocp4-stage/common/imagestreamtag.yaml
Labels: approved, size/S

#2564 Bump user-api to v0.35.2 in stage
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2561 Bump adviser to v0.55.0 in stage environment
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2567 Bump prescriptions-refresh-job to v0.7.0 in stage
  prescriptions-refresh-job/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2568 Update solver images in stage
  solver/overlays/ocp4-stage/imagestreamtag.yaml
Labels: size/XS

#2573 Enable auto offset reset to latest for resolving offset issues
  investigator/base/deploymentconfig.yaml
  investigator/overlays/aws-prod/deploymentconfig.yaml
  investigator/overlays/moc-prod/deploymentconfig.yaml
  investigator/overlays/ocp4-stage/deploymentconfig.yaml
  investigator/overlays/rick-test/deploymentconfig.yaml
  investigator/overlays/test/deploymentconfig.yaml
  investigator_message_metrics/base/deploymentconfig.yaml
  investigator_message_metrics/overlays/aws-prod/deploymentconfig.yaml
  investigator_message_metrics/overlays/moc-prod/deploymentconfig.yaml
  investigator_message_metrics/overlays/test/deploymentconfig.yaml
Labels: size/S

#2576 Adjusted slo-reporter config for moc run to use its own config
  slo-reporter/overlays/moc-prod-ocp4-stage/configmap.yaml
  slo-reporter/overlays/moc-prod-ocp4-stage/cronjob.yaml
  slo-reporter/overlays/moc-prod-ocp4-stage/kustomization.yaml
Labels: size/M, approved

#2578 Bump up the images based on the version update v2022.05.30
  adviser/overlays/aws-prod/imagestreamtag.yaml
  adviser/overlays/moc-prod/imagestreamtag.yaml
  kebechet/overlays/aws-prod/imagestreamtag.yaml
  kebechet/overlays/moc-prod/imagestreamtag.yaml
  kebechet/overlays/ocp4-stage/imagestreamtag.yaml
  user-api/overlays/aws-prod/imagestreamtag.yaml
  user-api/overlays/moc-prod/imagestreamtag.yaml
Labels: approved, size/S
