Repository thoth-station/thoth-application, pull requests merged in 2022-11, with the labels that each got.

#2693 Update mi-scheduler to 1.7.9
  mi-scheduler/overlays/ocp4-stage/imagestreamtag.yaml
  mi-scheduler/overlays/test/imagestreamtag.yaml
Labels: approved, size/XS, lgtm

#2695 Upgrade sefkhet abwy image version to v0.23.1
  sefkhet-abwy-chatbot/overlays/moc/imagestreamtag.yaml
  sefkhet-abwy/overlays/moc/imagestreamtag.yaml
  sefkhet-abwy/overlays/ocp/imagestreamtag.yaml
Labels: approved, size/XS, lgtm

#2696 Upgrade sefkhet-abwy image version to v0.23.2
  sefkhet-abwy-chatbot/overlays/moc/imagestreamtag.yaml
  sefkhet-abwy/overlays/moc/imagestreamtag.yaml
  sefkhet-abwy/overlays/ocp/imagestreamtag.yaml
Labels: approved, size/XS, lgtm

#2697 :ship: Bump up version of the updated component in release v2022.11.14
  kebechet/overlays/moc-prod/imagestreamtag.yaml
  kebechet/overlays/ocp4-stage/imagestreamtag.yaml
Labels: size/XS

#2699 :ship: Release of v2022.11.14
  CHANGELOG.md
  version.py
Labels: size/S

#2701 Fix the amun-api deployment with web concurrency set
  amun/overlays/test/deploymentconfig.yaml
Labels: size/XS

#2706 upgrade kebechet for the release fix
  kebechet/overlays/moc-prod/imagestreamtag.yaml
  kebechet/overlays/ocp4-stage/imagestreamtag.yaml
Labels: size/XS

#2703 :chart_with_downwards_trend: Setup monitoring for stage systems
  monitoring/base/kustomization.yaml
  monitoring/base/prometheusrule.yaml
  monitoring/overlays/moc-prod/alerting-rules.yaml
  monitoring/overlays/moc-prod/github-receiver.yaml
  monitoring/overlays/moc-prod/kustomization.yaml
  monitoring/overlays/moc-prod/prometheusrule.yaml
  monitoring/overlays/ocp4-stage/grafana/grafana-config.yaml
  monitoring/overlays/ocp4-stage/grafana/grafana-pvc.yaml
  monitoring/overlays/ocp4-stage/grafana/grafana-route.yaml
  monitoring/overlays/ocp4-stage/grafana/grafana-sa.yaml
  monitoring/overlays/ocp4-stage/grafana/grafana-secrets.enc.yaml
  monitoring/overlays/ocp4-stage/grafana/grafana-service.yaml
  monitoring/overlays/ocp4-stage/grafana/grafana.yaml
  monitoring/overlays/ocp4-stage/grafana/kustomization.yaml
  monitoring/overlays/ocp4-stage/grafana/secret-generator.yaml
  monitoring/overlays/ocp4-stage/kustomization.yaml
  monitoring/overlays/ocp4-stage/prometheus/alertmanager-secrets.enc.yaml
  monitoring/overlays/ocp4-stage/prometheus/alertmanager-svc.yaml
  monitoring/overlays/ocp4-stage/prometheus/alerts-svc.yaml
  monitoring/overlays/ocp4-stage/prometheus/kustomization.yaml
  monitoring/overlays/ocp4-stage/prometheus/prometheus-config.yaml
  monitoring/overlays/ocp4-stage/prometheus/prometheus-pvc.yaml
  monitoring/overlays/ocp4-stage/prometheus/prometheus-sa.yaml
  monitoring/overlays/ocp4-stage/prometheus/prometheus-secrets.enc.yaml
  monitoring/overlays/ocp4-stage/prometheus/prometheus-svc.yaml
  monitoring/overlays/ocp4-stage/prometheus/prometheus.yaml
  monitoring/overlays/ocp4-stage/prometheus/secret-generator.yaml
  monitoring/overlays/ocp4-stage/pushgateway/kustomization.yaml
  monitoring/overlays/ocp4-stage/pushgateway/pushgateway.yaml
Labels: approved, size/XXL, lgtm

#2705 :package: Use the new monitoring deployment in thoth-station component
  amun/overlays/ocp4-stage/common/configmaps.yaml
  build-watcher/overlays/amun-api/configmap.yaml
  build-watcher/overlays/test/configmap.yaml
  core/overlays/ocp4-stage/common/configmaps.yaml
  core/overlays/ocp4-stage/common/secrets.enc.yaml
  core/overlays/quicklab/configmaps.yaml
  core/overlays/test/configmaps.yaml
  core/overlays/test/secrets.enc.yaml
  slo-reporter/overlays/ocp4-stage/configmap.yaml
  slo-reporter/overlays/ocp4-stage/secrets.enc.yaml
  slo-reporter/overlays/test/configmap.yaml
  slo-reporter/overlays/test/secrets.enc.yaml
Labels: size/XL

#2708 Fix imagestream issue for workflow-helper
  core/overlays/ocp4-stage/backend-stage/kustomization.yaml
  core/overlays/ocp4-stage/middletier-stage/kustomization.yaml
  core/overlays/test/kustomization.yaml
Labels: approved, size/S
