Repository thoth-station/thoth-application, pull requests merged in 2022-03, with the labels that each got.

#2400 Bump prescriptions-refresh to v0.6.0 in stage
  prescriptions-refresh-job/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2397 Increase memory for prescriptions-refresh-pypi
  prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-pypi.yaml
Labels: approved, size/XS

#2398 Increase memory for prescriptions-refresh-pg
  prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-pg.yaml
Labels: approved, size/XS

#2403 Adjust adviser's memory optimizer configuration
  adviser/base/argo-workflows/advise.yaml
Labels: approved, size/XS

#2401 Increase deadline for prescriptions-refresh jobs
  prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-gh.yaml
  prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-image-analysis.yaml
  prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-pg.yaml
  prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-pypi.yaml
  prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-quay.yaml
  prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-scorecards.yaml
Labels: approved, size/S

#2404 Run all the steps in prescriptions-refresh PyPI workflow
  prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-gh.yaml
  prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-pypi.yaml
  prescriptions-refresh-job/overlays/ocp4-stage/kustomization.yaml
  prescriptions-refresh-job/overlays/test/kustomization.yaml
Labels: size/M, approved

#2402 Increase memory for prescriptions-refresh jobs to 1Gi to avoid OOM
  prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-gh.yaml
  prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-image-analysis.yaml
  prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-pypi.yaml
  prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-quay.yaml
  prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-scorecards.yaml
Labels: size/M, approved

#2405 Bump integration-tests to v0.9.3 in stage environment
  integration-tests/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2406 Bump user-api to v0.34.9 in stage environment
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2407 Bump adviser to v0.52.1 in stage environment
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2408 Adjust adviser's memory optimizer limit
  adviser/base/argo-workflows/advise.yaml
Labels: approved, size/XS

#2409 Document where to find container images used by Prow
  prow/README.md
Labels: approved, size/XS

#2410 Bump up user-api v0.34.10 to fix current openapi issue
  user-api/overlays/aws-prod/imagestreamtag.yaml
  user-api/overlays/moc-prod/imagestreamtag.yaml
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2412 add os-climate base config/plugins
  prow/overlays/smaug/config.yaml
  prow/overlays/smaug/plugins.yaml
Labels: size/M, approved

#2394 Reduce CPU used by adviser on AWS prod
  adviser/overlays/aws-prod/advise-resources-patch.yaml
Labels: approved, size/XS

#2411 [prow] remove some repos from needs-triage label management
  prow/overlays/smaug/plugins.yaml
Labels: size/M, approved

#2413 update prow config.yaml for os-climate repos
  prow/overlays/smaug/config.yaml
Labels: approved, size/S, ok-to-test

#2416 Fix the image patching of dm
  adviser/base/argo-workflows/dependency-monkey.yaml
  adviser/base/argo-workflows/kebechet-run-results.yaml
  adviser/overlays/aws-prod/kustomization.yaml
  adviser/overlays/moc-prod/kustomization.yaml
  adviser/overlays/ocp4-stage/kustomization.yaml
  adviser/overlays/test/kustomization.yaml
Labels: size/M, approved

#2414 Bump adviser to v0.52.2 in stage
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2418 Do not send message by default after Amun inspections
  amun/base/openshift-templates/inspection-workflow.yaml
Labels: approved, size/XS

#2417 Bump adviser to v0.52.2 in prod environment
  adviser/overlays/aws-prod/imagestreamtag.yaml
  adviser/overlays/moc-prod/imagestreamtag.yaml
Labels: approved, size/XS

#2419 bump adviser to v0.52.3 in all environments
  adviser/overlays/aws-prod/imagestreamtag.yaml
  adviser/overlays/moc-prod/imagestreamtag.yaml
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
  adviser/overlays/test/imagestreamtag.yaml
Labels: approved, size/XS, lgtm

#2420 Bump integration tests to v0.10.0
  integration-tests/overlays/moc-prod-ocp4-stage/imagestreamtag.yaml
  integration-tests/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2421 Revert "Do not send message by default after Amun inspections"
  amun/base/openshift-templates/inspection-workflow.yaml
Labels: approved, size/XS

#2422 Fix the kafka secrets issue for amun
  amun/overlays/aws-prod/amun-api/secrets.enc.yaml
  amun/overlays/moc-prod/amun-api/secrets.enc.yaml
  amun/overlays/ocp4-stage/amun-api/secrets.enc.yaml
Labels: approved, size/XL

#2423 Patch the kafka secrets to amun-inspection namespace
  amun/overlays/aws-prod/amun-api/secrets.enc.yaml
  amun/overlays/moc-prod/amun-api/secrets.enc.yaml
  amun/overlays/ocp4-stage/amun-api/secrets.enc.yaml
Labels: approved, size/XL

#2424 Bump user-api to v0.34.11 in stage
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2425 Bump integration-tests to v0.10.1
  integration-tests/overlays/moc-prod-ocp4-stage/imagestreamtag.yaml
  integration-tests/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2426 Patch the amun await step with retry strategy
  amun/base/argo-workflows/inspection-build-with-cpu.yaml
  amun/base/argo-workflows/inspection-build.yaml
Labels: approved, size/XS

#2427 Bump adviser to v0.52.4 in stage environment
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2430 Bump integration-tests to v0.11.0
  integration-tests/overlays/moc-prod-ocp4-stage/imagestreamtag.yaml
  integration-tests/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2433 Patch mi prod deployment in smaug cluster
  core/overlays/moc-prod/middletier-prod/configmaps.yaml
  mi-scheduler/overlays/moc-prod/cronjob.yaml
  mi-scheduler/overlays/moc-prod/imagestreamtag.yaml
  mi-scheduler/overlays/moc-prod/kustomization.yaml
  mi-scheduler/overlays/moc-prod/role-binding.yaml
  mi-scheduler/overlays/ocp4-stage/imagestreamtag.yaml
  mi-scheduler/overlays/ocp4-stage/kustomization.yaml
  mi-scheduler/overlays/ocp4-stage/role-binding.yaml
  mi-scheduler/overlays/test/imagestreamtag.yaml
Labels: size/M, approved

#2435 Bump user-api to v0.34.12 in stage
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2428 Add job specs to the mi-scheduler
  mi-scheduler/base/job.yaml
Labels: approved, size/L

#2434 Remove RSYSLOG_HOST and RSYSLOG_PORT from deployment manifests
  advise-reporter/base/cronjob.yaml
  advise-reporter/overlays/aws-prod/cronjob.yaml
  advise-reporter/overlays/moc-prod/cronjob.yaml
  advise-reporter/overlays/test/cronjob.yaml
  core/overlays/aws-prod/common/configmaps.yaml
  core/overlays/moc-prod/common/configmaps.yaml
  core/overlays/ocp4-stage/common/configmaps.yaml
  core/overlays/quicklab/configmaps.yaml
  core/overlays/rick-test/configmaps.yaml
  core/overlays/test/configmaps.yaml
  cve-update/base/cronjob.yaml
  cve-update/overlays/aws-prod/cronjob.yaml
  cve-update/overlays/moc-prod/cronjob.yaml
  document-sync-job/base/cronjob.yaml
  graph-backup-job/base/cronjob.yaml
  graph-metrics-exporter/base/cronjob.yaml
  graph-refresh/base/cronjob.yaml
  graph-refresh/overlays/aws-prod/cronjob.yaml
  graph-refresh/overlays/moc-prod/cronjob.yaml
  management-api/base/deploymentconfig.yaml
  metrics-exporter/base/deploymentconfig.yaml
  metrics-exporter/overlays/aws-prod/deploymentconfig.yaml
  metrics-exporter/overlays/moc-prod/deploymentconfig.yaml
  package-releases/base/cronjob.yaml
  package-releases/overlays/aws-prod/cronjob.yaml
  package-releases/overlays/moc-prod/cronjob.yaml
  package-update/base/cronjob.yaml
  package-update/overlays/aws-prod/cronjob.yaml
  package-update/overlays/moc-prod/cronjob.yaml
  user-api/base/deploymentconfig.yaml
  user-api/overlays/aws-prod/deploymentconfig.yaml
  user-api/overlays/moc-prod/deploymentconfig.yaml
  user-api/overlays/rick-test/deploymentconfig.yaml
Labels: approved, size/L

#2436 Run graph-refresh every 40 mins, instead of every hour
  graph-refresh/base/cronjob.yaml
Labels: approved, size/XS

#2437 bump reporter to v0.11.1
  advise-reporter/overlays/aws-prod/imagestreamtag.yaml
  advise-reporter/overlays/moc-prod/imagestreamtag.yaml
  advise-reporter/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2444 Fix name of dashboards for Grafana CRDs URL
  grafana-dashboard/base/thoth-postgresql-metrics.json
  grafana-dashboard/base/thoth-workflow-controllers-metrics.json
Labels: approved, size/XS

#2445 Bump adviser to v0.53.0 in stage environment
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2446 Bump adviser to v0.53.0 in prod deployments
  adviser/overlays/aws-prod/imagestreamtag.yaml
  adviser/overlays/moc-prod/imagestreamtag.yaml
Labels: approved, size/XS

#2448 Bump user-api to v0.34.13 in prod
  user-api/overlays/aws-prod/imagestreamtag.yaml
  user-api/overlays/moc-prod/imagestreamtag.yaml
Labels: approved, size/XS

#2432 add CREATE_KNOWLEDGE flag
  mi-scheduler/base/argo-workflows/mi-workflow-template.yaml
  mi-scheduler/base/openshift-templates/mi-run-template.yaml
  mi-scheduler/overlays/moc-prod/imagestreamtag.yaml
  mi-scheduler/overlays/test/imagestreamtag.yaml
Labels: approved, size/S

#2450 [prow] Add configuration for the projectmanager prow plugin
  prow/overlays/smaug/plugins.yaml
Labels: size/M, approved

#2453 Show date last db backup
  grafana-dashboard/base/thoth-postgresql-metrics.json
Labels: approved, size/L

#2449 adding thoth solver f35-py310 image to imagestream in test overlay
  solver/base/imagestreams.yaml
  solver/overlays/test/imagestreamtag.yaml
Labels: approved, size/S, lgtm, sig/devsecops

#2454 Propagate URL to Thoth Search UI in deployments
  user-api/base/deploymentconfig.yaml
  user-api/overlays/aws-prod/deploymentconfig.yaml
  user-api/overlays/moc-prod/deploymentconfig.yaml
  user-api/overlays/rick-test/deploymentconfig.yaml
Labels: approved, size/S

#2456 Fix user-api Thoth Search UI environment variable in deployments
  user-api/base/deploymentconfig.yaml
  user-api/overlays/aws-prod/deploymentconfig.yaml
  user-api/overlays/moc-prod/deploymentconfig.yaml
  user-api/overlays/rick-test/deploymentconfig.yaml
Labels: approved, size/S

#2458 creating aws-prod-ocp4-stage overlay for thoth-integration tests
  integration-tests/overlays/aws-prod-ocp4-stage/README.rst
  integration-tests/overlays/aws-prod-ocp4-stage/configmap.yaml
  integration-tests/overlays/aws-prod-ocp4-stage/cronjob.yaml
  integration-tests/overlays/aws-prod-ocp4-stage/imagestreamtag.yaml
  integration-tests/overlays/aws-prod-ocp4-stage/kustomization.yaml
  integration-tests/overlays/aws-prod-ocp4-stage/secret-generator.yaml
  integration-tests/overlays/aws-prod-ocp4-stage/secrets.enc.yaml
  integration-tests/overlays/aws-prod-ocp4-stage/thoth-notification.yaml
Labels: approved, size/L

#2462 set the pending workflow limit for the investigator
  investigator/overlays/ocp4-stage/deploymentconfig.yaml
Labels: approved, size/XS

#2461 [prow] project map: SIG User Experience instead of Kebechet
  prow/overlays/smaug/plugins.yaml
Labels: approved, size/XS

#2465 patch up the moc-prod s3 for amun
  amun/overlays/moc-prod/amun-api/configmaps.yaml
  amun/overlays/moc-prod/amun-api/secrets.enc.yaml
Labels: approved, size/L

#2466 include the graph-sync template for the dm
  amun/overlays/aws-prod/amun-api/argo-workflows/sync-template.yaml
  amun/overlays/aws-prod/amun-api/configmaps.yaml
  amun/overlays/aws-prod/amun-api/kustomization.yaml
  amun/overlays/aws-prod/amun-api/secrets.enc.yaml
  amun/overlays/moc-prod/amun-api/argo-workflows/sync-template.yaml
  amun/overlays/moc-prod/amun-api/configmaps.yaml
  amun/overlays/moc-prod/amun-api/kustomization.yaml
  amun/overlays/moc-prod/amun-api/secrets.enc.yaml
  amun/overlays/ocp4-stage/amun-api/argo-workflows/sync-template.yaml
  amun/overlays/ocp4-stage/amun-api/configmaps.yaml
  amun/overlays/ocp4-stage/amun-api/kustomization.yaml
  amun/overlays/ocp4-stage/amun-api/secrets.enc.yaml
Labels: approved, size/XXL

#2464 Downgrade amun api cpu limit for usability
  amun/base/deploymentconfig.yaml
Labels: approved, size/XS

#2467 Drop web concurrency for amun-api
  amun/base/deploymentconfig.yaml
Labels: approved, size/XS

#2468 configmap amun is required by both amun-api and amun-wf
  amun/base/openshift-templates/inspection-with-cpu-workflow.yaml
  amun/base/openshift-templates/inspection-workflow.yaml
  amun/overlays/aws-prod/amun-api/argo-workflows/sync-template.yaml
  amun/overlays/aws-prod/amun-api/kustomization.yaml
  amun/overlays/aws-prod/amun-api/secrets.enc.yaml
  amun/overlays/aws-prod/amun-inspection/configmaps.yaml
  amun/overlays/aws-prod/amun-inspection/kustomization.yaml
  amun/overlays/aws-prod/common/configmaps.yaml
  amun/overlays/aws-prod/common/kustomization.yaml
  amun/overlays/moc-prod/amun-api/argo-workflows/sync-template.yaml
  amun/overlays/moc-prod/amun-api/kustomization.yaml
  amun/overlays/moc-prod/amun-api/secrets.enc.yaml
  amun/overlays/moc-prod/amun-inspection/configmaps.yaml
  amun/overlays/moc-prod/amun-inspection/kustomization.yaml
  amun/overlays/moc-prod/common/configmaps.yaml
  amun/overlays/moc-prod/common/kustomization.yaml
  amun/overlays/ocp4-stage/amun-api/argo-workflows/sync-template.yaml
  amun/overlays/ocp4-stage/amun-api/kustomization.yaml
  amun/overlays/ocp4-stage/amun-api/secrets.enc.yaml
  amun/overlays/ocp4-stage/amun-inspection/configmaps.yaml
  amun/overlays/ocp4-stage/amun-inspection/kustomization.yaml
  amun/overlays/ocp4-stage/common/configmaps.yaml
  amun/overlays/ocp4-stage/common/kustomization.yaml
Labels: approved, size/XL

#2463 set mi-scheduler-cm configmap for mi-scheduler cronjob
  mi-scheduler/base/configmaps.yaml
  mi-scheduler/base/cronjob.yaml
Labels: approved, size/XS

#2474 Set kafka configmap for the amun-inspection
  amun/overlays/aws-prod/amun-inspection/configmaps.yaml
  amun/overlays/moc-prod/amun-inspection/configmaps.yaml
  amun/overlays/ocp4-stage/amun-inspection/configmaps.yaml
Labels: size/S, lgtm

#2476 switch on the document-sync in stage
  document-sync-job/overlays/ocp4-stage/cronjob.yaml
Labels: approved, size/XS

#2480 Fixed Image patch to use correct ns in prod
  graph-sync/overlays/aws-prod/middletier/kustomization.yaml
  graph-sync/overlays/moc-prod/middletier/kustomization.yaml
Labels: approved, size/XS

#2481 Keep DM up-to-date which uses adviser image
  amun/overlays/aws-prod/amun-inspection/kustomization.yaml
  amun/overlays/moc-prod/amun-inspection/kustomization.yaml
  amun/overlays/ocp4-stage/amun-inspection/kustomization.yaml
Labels: size/M, approved

#2482 Exit prescriptions-refresh-gh containers when too many requests to GitHub API
  prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-gh.yaml
Labels: approved, size/S
