Repository thoth-station/thoth-application, pull requests merged in 2022-08, with the labels that each got.

#2623 :arrow_up: Updated the version of kebechet v0.10.2
  kebechet/overlays/aws-prod/imagestreamtag.yaml
  kebechet/overlays/moc-prod/imagestreamtag.yaml
  kebechet/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2624 :arrow_up: Updated the version of kebechet v0.10.3
  kebechet/overlays/aws-prod/imagestreamtag.yaml
  kebechet/overlays/moc-prod/imagestreamtag.yaml
  kebechet/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2625 :ship: Bump up version of the updated component in release v2022.08.01
  adviser/overlays/aws-prod/imagestreamtag.yaml
  adviser/overlays/moc-prod/imagestreamtag.yaml
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
  core/overlays/aws-prod/common/imagestreamtags.yaml
  core/overlays/moc-prod/common/imagestreamtags.yaml
  core/overlays/ocp4-stage/common/imagestreamtags.yaml
  core/overlays/rick-test/imagestreamtags.yaml
  integration-tests/overlays/aws-prod-ocp4-stage/imagestreamtag.yaml
  integration-tests/overlays/moc-prod-ocp4-stage/imagestreamtag.yaml
  integration-tests/overlays/ocp4-stage/imagestreamtag.yaml
  prescriptions-refresh-job/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/S

#2630 Re-enable prescriptions-refresh-job
  prescriptions-refresh-job/overlays/ocp4-stage/cronworkflow.yaml
Labels: approved, size/S

#2606 migrating Prow manifefsts to operate-first/apps
  prow/OWNERS
  prow/README.md
  prow/add-ist
  prow/base/branchprotector.yaml
  prow/base/crier.yaml
  prow/base/deck.yaml
  prow/base/hook.yaml
  prow/base/horologium.yaml
  prow/base/imagestreams.yaml
  prow/base/ingress.yaml
  prow/base/kustomization.yaml
  prow/base/label_sync_job.yaml
  prow/base/needs-rebase.yaml
  prow/base/pipeline.yaml
  prow/base/plank.yaml
  prow/base/prow-controller-manager.yaml
  prow/base/sinker.yaml
  prow/base/statusreconciler.yaml
  prow/base/tide.yaml
  prow/overlays/smaug-test-pods/crier_rbac.yaml
  prow/overlays/smaug-test-pods/deck_rbac.yaml
  prow/overlays/smaug-test-pods/kustomization.yaml
  prow/overlays/smaug-test-pods/prow-controller-manager_rbac.yaml
  prow/overlays/smaug-test-pods/sinker_rbac.yaml
  prow/overlays/smaug/config.yaml
  prow/overlays/smaug/ghproxy.yaml
  prow/overlays/smaug/imagestreamtags.yaml
  prow/overlays/smaug/integration-test-configmap.yaml
  prow/overlays/smaug/kustomization.yaml
  prow/overlays/smaug/plugins.yaml
  prow/overlays/smaug/route-ghproxy-metrics.yaml
  prow/overlays/smaug/routes.yaml
  prow/overlays/smaug/s3-storage.yaml
  prow/overlays/smaug/secret-generator.yaml
  prow/overlays/smaug/secrets.enc.yaml
  prow/overlays/smaug/service-monitor.yaml
  prow/overlays/smaug/unsuspend_branchprotector.yaml
Labels: approved, size/XXL, lgtm

#2631 Fix cache expiration value
  user-api/base/configmap.yaml
Labels: size/XS, lgtm

#2632 :ship: Bump up version of the updated component in release v2022.08.22
  adviser/overlays/aws-prod/imagestreamtag.yaml
  adviser/overlays/moc-prod/imagestreamtag.yaml
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
  core/overlays/aws-prod/common/imagestreamtags.yaml
  core/overlays/moc-prod/common/imagestreamtags.yaml
  core/overlays/ocp4-stage/common/imagestreamtags.yaml
  cve-update/overlays/aws-prod/imagestreamtag.yaml
  cve-update/overlays/moc-prod/imagestreamtag.yaml
  cve-update/overlays/ocp4-stage/imagestreamtag.yaml
  graph-backup-job/overlays/aws-prod/imagestreamtag.yaml
  graph-backup-job/overlays/moc-prod/imagestreamtag.yaml
  graph-backup-job/overlays/ocp4-stage/imagestreamtag.yaml
  graph-metrics-exporter/overlays/aws-prod/imagestreamtag.yaml
  graph-metrics-exporter/overlays/moc-prod/imagestreamtag.yaml
  graph-metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
  graph-refresh/overlays/aws-prod/imagestreamtag.yaml
  graph-refresh/overlays/moc-prod/imagestreamtag.yaml
  graph-refresh/overlays/ocp4-stage/imagestreamtag.yaml
  graph-sync/overlays/aws-prod/common/imagestreamtag.yaml
  graph-sync/overlays/moc-prod/common/imagestreamtag.yaml
  graph-sync/overlays/ocp4-stage/common/imagestreamtag.yaml
  management-api/overlays/aws-prod/imagestreamtag.yaml
  management-api/overlays/moc-prod/imagestreamtag.yaml
  management-api/overlays/ocp4-stage/imagestreamtag.yaml
  metrics-exporter/overlays/aws-prod/imagestreamtag.yaml
  metrics-exporter/overlays/moc-prod/imagestreamtag.yaml
  metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
  package-releases/overlays/aws-prod/imagestreamtag.yaml
  package-releases/overlays/moc-prod/imagestreamtag.yaml
  package-releases/overlays/ocp4-stage/imagestreamtag.yaml
  package-update/overlays/aws-prod/imagestreamtag.yaml
  package-update/overlays/moc-prod/imagestreamtag.yaml
  package-update/overlays/ocp4-stage/imagestreamtag.yaml
  revsolver/overlays/aws-prod/imagestreamtag.yaml
  revsolver/overlays/moc-prod/imagestreamtag.yaml
  revsolver/overlays/ocp4-stage/imagestreamtag.yaml
  slo-reporter/overlays/aws-prod-ocp4-stage/imagestreamtag.yaml
  slo-reporter/overlays/moc-prod-ocp4-stage/imagestreamtag.yaml
  slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml
  user-api/overlays/aws-prod/imagestreamtag.yaml
  user-api/overlays/moc-prod/imagestreamtag.yaml
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: size/M, approved

#2636 :arrow_up: Upgrade the resource cpu for investigator deployment
  investigator/base/deploymentconfig.yaml
  investigator/overlays/aws-prod/deploymentconfig.yaml
  investigator/overlays/moc-prod/deploymentconfig.yaml
  investigator/overlays/ocp4-stage/deploymentconfig.yaml
  investigator/overlays/test/deploymentconfig.yaml
Labels: size/S

#2639 :ant: Update the timeout for readinessprobe
  investigator/base/deploymentconfig.yaml
  investigator/overlays/aws-prod/deploymentconfig.yaml
  investigator/overlays/moc-prod/deploymentconfig.yaml
  investigator/overlays/ocp4-stage/deploymentconfig.yaml
  investigator/overlays/test/deploymentconfig.yaml
Labels: size/M, approved, lgtm

#2640 :ant: Update the memory resource for investigator
  investigator/base/deploymentconfig.yaml
  investigator/overlays/aws-prod/deploymentconfig.yaml
  investigator/overlays/moc-prod/deploymentconfig.yaml
  investigator/overlays/ocp4-stage/deploymentconfig.yaml
  investigator/overlays/test/deploymentconfig.yaml
Labels: size/M, approved

#2641 Add a rule to triage-party to highlight issues without a SIG
  triage-party/overlays/moc/config.yaml
Labels: approved, size/S

#2638 removing all rick-test overlays
  core/overlays/rick-test/argo-deployments.yaml
  core/overlays/rick-test/argo-imagestreams.yaml
  core/overlays/rick-test/argo-management.yaml
  core/overlays/rick-test/argo-role.yaml
  core/overlays/rick-test/argo-ui-controller.yaml
  core/overlays/rick-test/argo-workflow-controller.yaml
  core/overlays/rick-test/argo-workflows/send-message.yaml
  core/overlays/rick-test/argo-workflows/send-messages.yaml
  core/overlays/rick-test/buildConfig.yaml
  core/overlays/rick-test/configmaps.yaml
  core/overlays/rick-test/imagestreamtags.yaml
  core/overlays/rick-test/kustomization.yaml
  core/overlays/rick-test/pgbouncer.yaml
  core/overlays/rick-test/postgresql-metrics-exporter.yaml
  core/overlays/rick-test/postgresql.yaml
  core/overlays/rick-test/s3-storage.yaml
  core/overlays/rick-test/secret-generator.yaml
  core/overlays/rick-test/secrets.enc.yaml
  core/overlays/rick-test/thoth-notification.yaml
  investigator/overlays/rick-test/deploymentconfig.yaml
  investigator/overlays/rick-test/kustomization.yaml
  investigator/overlays/rick-test/role.yaml
  investigator/overlays/rick-test/role_binding.yaml
  investigator/overlays/rick-test/route.yaml
  investigator/overlays/rick-test/service.yaml
  investigator/overlays/rick-test/thoth-notification.yaml
  mi-scheduler/overlays/rick-test/buildConfig.yaml
  mi-scheduler/overlays/rick-test/cronjob.yaml
  mi-scheduler/overlays/rick-test/imagestreamtag.yaml
  mi-scheduler/overlays/rick-test/kustomization.yaml
  mi-scheduler/overlays/rick-test/role-binding.yaml
  mi-scheduler/overlays/rick-test/secret-generator.yaml
  mi-scheduler/overlays/rick-test/secrets.enc.yaml
  mi-scheduler/overlays/rick-test/thoth-notification.yaml
  user-api/overlays/rick-test/configmap.yaml
  user-api/overlays/rick-test/deploymentconfig.yaml
  user-api/overlays/rick-test/imagestreamtag.yaml
  user-api/overlays/rick-test/kustomization.yaml
  user-api/overlays/rick-test/resources_patch.yaml
  user-api/overlays/rick-test/role-binding.yaml
  user-api/overlays/rick-test/route.enc.yaml
  user-api/overlays/rick-test/secret-generator.yaml
  user-api/overlays/rick-test/thoth-notification.yaml
Labels: approved, size/XXL, lgtm

#2643 :fire: switch insecure false for the agro-worflows
  adviser/base/argo-workflows/advise.yaml
  adviser/base/argo-workflows/dependency-monkey.yaml
  adviser/base/argo-workflows/provenance-check.yaml
  buildlog-parser/base/argo-workflows/buildlog-parser.yaml
  core/overlays/aws-prod/backend-prod/configmaps.yaml
  core/overlays/aws-prod/middletier-prod/configmaps.yaml
  core/overlays/ocp4-stage/backend-stage/configmaps.yaml
  core/overlays/ocp4-stage/middletier-stage/configmaps.yaml
  core/overlays/test/configmaps.yaml
  package-extract/base/argo-workflows/package-extract.yaml
  revsolver/base/argo-workflows/revsolver-template.yaml
  security-indicators/base/argo-workflows/aggregator-template.yaml
  security-indicators/base/argo-workflows/bandit-template.yaml
  security-indicators/base/argo-workflows/cloc-template.yaml
  solver/base/argo-workflows/solver-template.yaml
  solver/overlays/test/argo-workflows/solver-template.yaml
Labels: approved, size/S

#2644 :recycle: Switch v1 rbac from v1beta1 as its deprecated
  amun/overlays/aws-prod/amun-api/role_binding.yaml
  amun/overlays/moc-prod/amun-api/role_binding.yaml
  amun/overlays/ocp4-stage/amun-api/role_binding.yaml
  amun/overlays/power9/amun-api/role_binding.yaml
  amun/overlays/prod/amun-api/role_binding.yaml
  amun/overlays/test/role_binding.yaml
  build-watcher/overlays/amun-api/role-binding.yaml
  graph-refresh/overlays/aws-prod/rolebindings.yaml
  graph-refresh/overlays/moc-prod/rolebindings.yaml
  graph-refresh/overlays/ocp4-stage/rolebindings.yaml
  graph-refresh/overlays/test/rolebindings.yaml
  init-job/base/role.yaml
  init-job/base/role_binding.yaml
  investigator/overlays/aws-prod/role_binding.yaml
  investigator/overlays/moc-prod/role_binding.yaml
  investigator/overlays/ocp4-stage/role_binding.yaml
  investigator/overlays/test/role_binding.yaml
  management-api/overlays/aws-prod/role-binding.yaml
  management-api/overlays/moc-prod/role-binding.yaml
  management-api/overlays/ocp4-stage/role-binding.yaml
  management-api/overlays/test/role-binding.yaml
  metrics-exporter/base/rolebinding.yaml
  metrics-exporter/overlays/aws-prod/role_bindings.yaml
  metrics-exporter/overlays/moc-prod/role_bindings.yaml
  metrics-exporter/overlays/ocp4-stage/role_bindings.yaml
  mi-scheduler/overlays/moc-prod/role-binding.yaml
  mi-scheduler/overlays/ocp4-stage/role-binding.yaml
  mi-scheduler/overlays/test/role-binding.yaml
  revsolver/overlays/aws-prod/rolebinding.yaml
  revsolver/overlays/moc-prod/rolebinding.yaml
  revsolver/overlays/ocp4-stage/rolebinding.yaml
  revsolver/overlays/test/rolebinding.yaml
  user-api/overlays/aws-prod/role-binding.yaml
  user-api/overlays/moc-prod/role-binding.yaml
  user-api/overlays/ocp4-stage/role-binding.yaml
  user-api/overlays/test/role-binding.yaml
Labels: approved, size/L
