Repository thoth-station/thoth-application, pull requests merged in 2022-12, with the labels that each got.

#2709 Upgrade kebechet image version to v1.11.2
  kebechet/overlays/moc-prod/imagestreamtag.yaml
  kebechet/overlays/ocp4-stage/imagestreamtag.yaml
Labels: size/XS

#2710 Upgrade workflow helper image version to v0.9.15
  core/overlays/moc-prod/common/imagestreamtags.yaml
  core/overlays/ocp4-stage/common/imagestreamtags.yaml
Labels: approved, size/XS, lgtm

#2702 make callback secret optional
  adviser/base/openshift-templates/adviser.yaml
  core/base/argo-management.yaml
  core/base/kustomization.yaml
  core/base/send-webhooks-sa.yaml
  core/overlays/ocp4-stage/backend-stage/argo-management.yaml
  core/overlays/test/argo-management.yaml
Labels: approved, size/L, lgtm

#2712 Disable pulp index sync job for temporary fix
  pulp-pypi-sync-job/overlays/ocp4-stage/cronjob.yaml
Labels: size/XS

#2713 Upgrade management-api in prod to get storage v0.73.6 changes
  management-api/overlays/moc-prod/imagestreamtag.yaml
Labels: size/XS

#2715 :ship: Bump up version of the updated component in release v2022.12.05
  cve-update/overlays/moc-prod/imagestreamtag.yaml
  cve-update/overlays/ocp4-stage/imagestreamtag.yaml
Labels: size/XS

#2717 :ship: Release of version 2022.12.05
  CHANGELOG.md
  version.py
Labels: size/S
