Repository thoth-station/thoth-application, pull requests merged in 2022-06, with the labels that each got.

#2585 add create, and update permissions for secret resources 4 user-api
  user-api/base/role.yaml
Labels: approved, size/S, lgtm

#2587 Bump prescriptions-refresh-job to v0.7.1 in stage
  prescriptions-refresh-job/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS, lgtm

#2586 feat: Disable branch protection on probot-extensions repo
  prow/overlays/smaug/config.yaml
Labels: approved, size/XS, lgtm

#2589 Bump adviser to v0.56.0 in stage
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS, lgtm

#2590 Suspend scorecards handler and schedule refresh job monthly
  prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-scorecards.yaml
  prescriptions-refresh-job/overlays/ocp4-stage/cronworkflow.yaml
Labels: approved, size/XS, lgtm

#2592 Fix the kafka connection of ocp4 test
  core/overlays/test/secrets.enc.yaml
Labels: size/L

#2595 Bump up version of the updated component in release v2022.06.20
  adviser/overlays/aws-prod/imagestreamtag.yaml
  adviser/overlays/moc-prod/imagestreamtag.yaml
  kebechet/overlays/aws-prod/imagestreamtag.yaml
  kebechet/overlays/moc-prod/imagestreamtag.yaml
  kebechet/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/S

#2600 feat: Disable branch protection on probot-template repo
  prow/overlays/smaug/config.yaml
Labels: approved, size/XS

#2601 feat: Relocate Probot repositories to Operate First
  prow/overlays/smaug/config.yaml
Labels: approved, size/XS, lgtm

#2602 include operate first website repo again
  prow/overlays/smaug/config.yaml
Labels: approved, size/XS, lgtm, ok-to-test
