Repository thoth-station/thoth-application, pull requests merged in 2022-09, with the labels that each got.

#2646 Fix README typo
  README.md
Labels: approved, size/XS

#2645 Add the prometheus gateway to sync job
  sync-job/base/workflow-template.yaml
Labels: size/XS

#2607 add new role and role binding for adviser
  core/base/kustomization.yaml
  core/base/send-webhooks-sa.yaml
Labels: size/M, approved, lgtm

#2650 :ship: Bump up version of the updated component in release v2022.09.12
  kebechet/overlays/aws-prod/imagestreamtag.yaml
  kebechet/overlays/moc-prod/imagestreamtag.yaml
  kebechet/overlays/ocp4-stage/imagestreamtag.yaml
  prescriptions-refresh-job/overlays/ocp4-stage/imagestreamtag.yaml
  user-api/overlays/aws-prod/imagestreamtag.yaml
  user-api/overlays/moc-prod/imagestreamtag.yaml
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/S

#2652 Update the kebechet version v1.10.5
  kebechet/overlays/aws-prod/imagestreamtag.yaml
  kebechet/overlays/moc-prod/imagestreamtag.yaml
  kebechet/overlays/ocp4-stage/imagestreamtag.yaml
Labels: approved, size/XS

#2657 upgrade graph-sync, solver and management-api to fix the solver runs
  graph-sync/overlays/ocp4-stage/common/imagestreamtag.yaml
  management-api/overlays/ocp4-stage/imagestreamtag.yaml
  solver/overlays/ocp4-stage/imagestreamtag.yaml
  solver/overlays/test/imagestreamtag.yaml
Labels: approved, size/S

#2659 Update the components to fix the alerts
  adviser/overlays/aws-prod/imagestreamtag.yaml
  adviser/overlays/moc-prod/imagestreamtag.yaml
  adviser/overlays/ocp4-stage/imagestreamtag.yaml
  core/overlays/aws-prod/common/imagestreamtags.yaml
  core/overlays/moc-prod/common/imagestreamtags.yaml
  core/overlays/ocp4-stage/common/imagestreamtags.yaml
  cve-update/overlays/aws-prod/imagestreamtag.yaml
  cve-update/overlays/moc-prod/imagestreamtag.yaml
  cve-update/overlays/ocp4-stage/imagestreamtag.yaml
  graph-backup-job/overlays/aws-prod/imagestreamtag.yaml
  graph-backup-job/overlays/moc-prod/imagestreamtag.yaml
  graph-backup-job/overlays/ocp4-stage/imagestreamtag.yaml
  graph-refresh/overlays/aws-prod/imagestreamtag.yaml
  graph-refresh/overlays/moc-prod/imagestreamtag.yaml
  graph-refresh/overlays/ocp4-stage/imagestreamtag.yaml
  metrics-exporter/overlays/aws-prod/imagestreamtag.yaml
  metrics-exporter/overlays/moc-prod/imagestreamtag.yaml
  metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
  package-releases/overlays/aws-prod/imagestreamtag.yaml
  package-releases/overlays/moc-prod/imagestreamtag.yaml
  package-releases/overlays/ocp4-stage/imagestreamtag.yaml
  user-api/overlays/aws-prod/imagestreamtag.yaml
  user-api/overlays/moc-prod/imagestreamtag.yaml
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: size/M, approved

#2658 Use pvc volume for graph-backup-job
  graph-backup-job/base/cronjob.yaml
  graph-backup-job/overlays/aws-prod/kustomization.yaml
  graph-backup-job/overlays/aws-prod/pvc.yaml
  graph-backup-job/overlays/moc-prod/pvc.yaml
  graph-backup-job/overlays/ocp4-stage/kustomization.yaml
  graph-backup-job/overlays/ocp4-stage/pvc.yaml
Labels: approved, size/L

#2660 Lower the limit to give space for other pvc's
  core/overlays/aws-prod/graph-prod/postgresql.yaml
Labels: approved, size/XS

#2662 Adjust the slo-reporter deployment
  advise-reporter/overlays/ocp4-stage/cronjob.yaml
  package-update/overlays/ocp4-stage/cronjob.yaml
  slo-reporter/overlays/aws-prod-ocp4-stage/cronjob.yaml
  slo-reporter/overlays/aws-prod-ocp4-stage/kustomization.yaml
  slo-reporter/overlays/moc-prod-ocp4-stage/cronjob.yaml
  slo-reporter/overlays/moc-prod-ocp4-stage/kustomization.yaml
  slo-reporter/overlays/ocp4-stage/cronjob.yaml
  slo-reporter/overlays/ocp4-stage/kustomization.yaml
Labels: approved, size/L

#2664 :turtle: Migrate hostname prod to moc deployment
  amun/overlays/aws-prod/amun-api/kustomization.yaml
  amun/overlays/aws-prod/amun-api/route53.yaml
  amun/overlays/moc-prod/amun-api/route53.yaml
  management-api/overlays/aws-prod/kustomization.yaml
  management-api/overlays/aws-prod/route53.yaml
  management-api/overlays/moc-prod/route53.yaml
  user-api/overlays/aws-prod/khemenu-route.yaml
  user-api/overlays/aws-prod/kustomization.yaml
  user-api/overlays/aws-prod/route53.yaml
  user-api/overlays/moc-prod/kustomization.yaml
  user-api/overlays/moc-prod/route53.yaml
Labels: size/M, approved

#2665 :turtle: Migration: Turn off cronjob on the balrog cluster
  advise-reporter/overlays/aws-prod/cronjob.yaml
  cve-update/overlays/aws-prod/cronjob.yaml
  document-sync-job/overlays/ocp4-stage/cronjob.yaml
  graph-backup-job/overlays/aws-prod/cronjob.yaml
  graph-metrics-exporter/overlays/aws-prod/cronjob.yaml
  integration-tests/overlays/aws-prod-ocp4-stage/cronjob.yaml
  slo-reporter/overlays/aws-prod-ocp4-stage/cronjob.yaml
Labels: approved, size/S
