Repository thoth-station/thoth-application, pull requests merged in 2023-06, with the labels that each got.

#2751 Upgrade kafka to 3.4.0 version for compatability with cluster amq
  core/overlays/ocp4-stage/common/secrets.enc.yaml
  kafka/base/thoth-kafka.yaml
Labels: size/L

#2750 update .prow.yaml
  .prow.yaml
Labels: size/M

#2704 :chart_with_downwards_trend: Persist the grafana dashboard for stage cluster
  grafana-dashboard/ocp4-stage/thoth-kafka-argo-metrics.json
  grafana-dashboard/ocp4-stage/thoth-knowledge-graph-content-metrics.json
  grafana-dashboard/ocp4-stage/thoth-postgresql-metrics.json
  grafana-dashboard/ocp4-stage/thoth-report.json
  grafana-dashboard/ocp4-stage/thoth-service-metrics.json
  grafana-dashboard/ocp4-stage/thoth-service-user-api.json
  grafana-dashboard/ocp4-stage/thoth-sli-slo.json
  grafana-dashboard/ocp4-stage/thoth-workflow-controller.json
Labels: size/XXL
