Repository thoth-station/thoth-application, pull requests merged in 2023-01, with the labels that each got.

#2719 :lock: Update the certs for the stage and test URLs
  amun/overlays/ocp4-stage/amun-api/route.enc.yaml
  amun/overlays/test/route.enc.yaml
  management-api/overlays/ocp4-stage/route.enc.yaml
  management-api/overlays/test/route.enc.yaml
  user-api/overlays/ocp4-stage/route.enc.yaml
  user-api/overlays/test/route.enc.yaml
Labels: size/XXL

#2721 :pause_button: Pause the graph-refresh job for sync period to stabilize
  graph-refresh/overlays/ocp4-stage/cronjob.yaml
Labels: size/XS

#2722 Suspend prescription refresh execution
  prescriptions-refresh-job/overlays/ocp4-stage/cronworkflow.yaml
Labels: size/S

#2723 :face_in_clouds: Updating the kafka certs for smaug cluster deployment
  core/overlays/moc-prod/common/secrets.enc.yaml
Labels: size/L

#2726 :pushpin: Upgrade the graph-sync and solver in stage cluster
  graph-sync/overlays/ocp4-stage/common/imagestreamtag.yaml
  solver/overlays/ocp4-stage/imagestreamtag.yaml
  solver/overlays/test/imagestreamtag.yaml
Labels: size/S

#2728 :pushpin: Upgrade the management-api in stage cluster
  management-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: size/XS

#2729 :pushpin: Upgrade the metrics-exporter in stage cluster
  metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
Labels: size/XS

#2730 :pushpin: Upgrade the all components using thoth-storages in stage cluster
  advise-reporter/overlays/ocp4-stage/imagestreamtag.yaml
  core/overlays/ocp4-stage/common/imagestreamtags.yaml
  cve-update/overlays/ocp4-stage/imagestreamtag.yaml
  graph-backup-job/overlays/ocp4-stage/imagestreamtag.yaml
  graph-metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
  graph-refresh/overlays/ocp4-stage/imagestreamtag.yaml
  graph-sync/overlays/ocp4-stage/common/imagestreamtag.yaml
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: size/S

#2731 :play_or_pause_button: Resume graph-refresh-job for data ingestion
  graph-refresh/overlays/ocp4-stage/cronjob.yaml
Labels: size/XS

#2727 :face_in_clouds: Remove unused env var in graph-sync job
  graph-sync/base/argo-workflows/sync-template.yaml
  graph-sync/base/openshift-templates/syncJob-template.yaml
Labels: approved, size/S, lgtm

#2732 :pushpin: Upgrade user-api in stage cluster for cachemiss error fix
  user-api/overlays/ocp4-stage/imagestreamtag.yaml
Labels: size/XS

#2733 temporarily disable message sending after adviser is complete
  adviser/base/openshift-templates/adviser.yaml
Labels: size/M, approved, lgtm

#2734 :link: Split the investigator consumer based on namespace
  investigator/base/deploymentconfig.yaml
  investigator/base/kustomization.yaml
  investigator/overlays/moc-prod/deployment.yaml
  investigator/overlays/moc-prod/deploymentconfig.yaml
  investigator/overlays/moc-prod/kustomization.yaml
  investigator/overlays/ocp4-stage/deployment.yaml
  investigator/overlays/ocp4-stage/deploymentconfig.yaml
  investigator/overlays/ocp4-stage/kustomization.yaml
  investigator/overlays/test/deployment.yaml
  investigator/overlays/test/kustomization.yaml
Labels: size/XXL

#2736 :ship: Bump up version of the updated component in release v2023.01.23
  advise-reporter/overlays/moc-prod/imagestreamtag.yaml
  core/overlays/moc-prod/common/imagestreamtags.yaml
  core/overlays/ocp4-stage/common/imagestreamtags.yaml
  cve-update/overlays/moc-prod/imagestreamtag.yaml
  graph-backup-job/overlays/moc-prod/imagestreamtag.yaml
  graph-metrics-exporter/overlays/moc-prod/imagestreamtag.yaml
  graph-refresh/overlays/moc-prod/imagestreamtag.yaml
  graph-sync/overlays/moc-prod/common/imagestreamtag.yaml
  integration-tests/overlays/moc-prod-ocp4-stage/imagestreamtag.yaml
  integration-tests/overlays/ocp4-stage/imagestreamtag.yaml
  integration-tests/overlays/test/imagestreamtag.yaml
  management-api/overlays/moc-prod/imagestreamtag.yaml
  metrics-exporter/overlays/moc-prod/imagestreamtag.yaml
  solver/overlays/moc-prod/imagestreamtag.yaml
  user-api/overlays/moc-prod/imagestreamtag.yaml
Labels: size/M
