Repository thoth-station/thoth-application, pull requests merged in 2023-02, with the labels that each got.

#2744 :sleeping: Hibernate all deployments and jobs in test cluster
  amun/overlays/test/deploymentconfig.yaml
  graph-backup-job/overlays/test/cronjob.yaml
  graph-metrics-exporter/overlays/test/cronjob.yaml
  integration-tests/overlays/test/cronjob.yaml
  investigator/overlays/test/deployment.yaml
  investigator_message_metrics/overlays/test/deploymentconfig.yaml
  management-api/overlays/test/kustomization.yaml
  metrics-exporter/overlays/test/kustomization.yaml
  mi-scheduler/overlays/test/cronjob.yaml
  stress-tests/overlays/test/cronjob.yaml
  user-api/overlays/test/kustomization.yaml
Labels: size/M, approved, lgtm

#2743 :sleeping: Hibernate the data-ingestion jobs on smaug cluster
  advise-reporter/overlays/moc-prod/cronjob.yaml
  cve-update/overlays/moc-prod/cronjob.yaml
  integration-tests/overlays/moc-prod-ocp4-stage/cronjob.yaml
  mi-scheduler/overlays/moc-prod/cronjob.yaml
  slo-reporter/overlays/moc-prod-ocp4-stage/cronjob.yaml
Labels: approved, size/S, lgtm

#2745 :recycle: Remove the deprecated overlays in amun and core components
  amun/overlays/power9/README.md
  amun/overlays/power9/amun-api/argo-role.yaml
  amun/overlays/power9/amun-api/buildconfig.yaml
  amun/overlays/power9/amun-api/configmaps.yaml
  amun/overlays/power9/amun-api/kustomization.yaml
  amun/overlays/power9/amun-api/put-into-inspection-namespace.yaml
  amun/overlays/power9/amun-api/role_binding.yaml
  amun/overlays/power9/amun-api/secret-generator.yaml
  amun/overlays/power9/amun-api/secrets.enc.yaml
  amun/overlays/power9/amun-inspection/argo-buildconfig.yaml
  amun/overlays/power9/amun-inspection/argo-imagestream.yaml
  amun/overlays/power9/amun-inspection/argo-namespace-install.yaml
  amun/overlays/power9/amun-inspection/argo-role.yaml
  amun/overlays/power9/amun-inspection/argo-ui-route.yaml
  amun/overlays/power9/amun-inspection/argo-workflow-controller-metrics.yaml
  amun/overlays/power9/amun-inspection/buildconfig.yaml
  amun/overlays/power9/amun-inspection/configmaps.yaml
  amun/overlays/power9/amun-inspection/kustomization.yaml
  amun/overlays/prod/README.md
  amun/overlays/prod/amun-api/argo-role.yaml
  amun/overlays/prod/amun-api/configmaps.yaml
  amun/overlays/prod/amun-api/imagestreamtag.yaml
  amun/overlays/prod/amun-api/kustomization.yaml
  amun/overlays/prod/amun-api/metrics-exporter-reader.yaml
  amun/overlays/prod/amun-api/put-into-inspection-namespace.yaml
  amun/overlays/prod/amun-api/role_binding.yaml
  amun/overlays/prod/amun-api/route.enc.yaml
  amun/overlays/prod/amun-api/secret-generator.yaml
  amun/overlays/prod/amun-api/secrets.enc.yaml
  amun/overlays/prod/amun-inspection/argo-namespace-install.yaml
  amun/overlays/prod/amun-inspection/argo-role.yaml
  amun/overlays/prod/amun-inspection/argo-ui-route.yaml
  amun/overlays/prod/amun-inspection/argo-workflow-controller-metrics.yaml
  amun/overlays/prod/amun-inspection/configmaps.yaml
  amun/overlays/prod/amun-inspection/kustomization.yaml
  amun/overlays/prod/amun-inspection/metrics-exporter-reader.yaml
  core/overlays/quicklab/argo-namespace-install.yaml
  core/overlays/quicklab/argo-ui-route.yaml
  core/overlays/quicklab/configmaps.yaml
  core/overlays/quicklab/kustomization.yaml
  core/overlays/quicklab/postgresql-ephemeral.yaml
  core/overlays/quicklab/secret-generator.yaml
  core/overlays/quicklab/secrets.enc.yaml
  core/overlays/quicklab/thoth-notification.yaml
Labels: approved, size/XXL, lgtm

#2742 :sleeping: Slow down the daily jobs to monthly on stage cluster
  graph-backup-job/base/cronjob.yaml
  graph-metrics-exporter/base/cronjob.yaml
  graph-refresh/base/cronjob.yaml
  integration-tests/base/cronjob.yaml
Labels: approved, size/XS, lgtm

#2741 :sleeping: Turn off sentry logging by removing sentry_dsn
  amun/overlays/moc-prod/amun-api/secrets.enc.yaml
  amun/overlays/ocp4-stage/amun-api/secrets.enc.yaml
  amun/overlays/test/secrets.enc.yaml
  core/overlays/moc-prod/common/secrets.enc.yaml
  core/overlays/ocp4-stage/common/secrets.enc.yaml
  core/overlays/test/secrets.enc.yaml
  docs/thoth_logging.md
  kebechet/overlays/moc-prod/secrets.enc.yaml
  kebechet/overlays/ocp4-stage/secrets.enc.yaml
  kebechet/overlays/test/secrets.enc.yaml
  sefkhet-abwy-chatbot/overlays/moc/secrets.enc.yaml
  sefkhet-abwy/overlays/moc/secrets.enc.yaml
  sefkhet-abwy/overlays/ocp/secrets.enc.yaml
Labels: approved, size/XXL, lgtm

#2746 remove deployment of Thoth's traige party
  triage-party/OWNERS
  triage-party/base/deployment.yaml
  triage-party/base/imagestream.yaml
  triage-party/base/kustomization.yaml
  triage-party/base/route.yaml
  triage-party/base/service.yaml
  triage-party/overlays/moc/config.yaml
  triage-party/overlays/moc/imagestreamtags.yaml
  triage-party/overlays/moc/kustomization.yaml
  triage-party/overlays/moc/pcache.yaml
  triage-party/overlays/moc/route.yaml
  triage-party/overlays/moc/secret-generator.yaml
  triage-party/overlays/moc/secrets.enc.yaml
Labels: approved, size/XL, lgtm
